### ISSUE TITLE
Fasttravel for guild halls

### ISSUE THREAD

**Issue by DarkManic** [HasKha/GWToolboxpp#100]
Add `/tp gh` for traveling to your own guild hall.
Also if its possible add `/tp gh golt` and other short handles from the ally you are in.

**Comment by Hour-of-the-Owl** [comment]
what would it do if there were 2 guilds in the alliance with the same tag?

**Comment by reduf** [comment]
Great idea.
@Hour-of-the-Owl, it will just tp to the first it find with the same tag.

**Comment by Hour-of-the-Owl** [comment]
there's no need for this to be case sensitive, right? I don't want to have to type "uDuB" correctly

**Comment by reduf** [comment]
Added.
