### ISSUE TITLE
Remove fireworks and tonic sounds

### ISSUE THREAD

**Issue by DarkManic** [HasKha/GWToolboxpp#103]
Remove fireworks (city) and tonic (pop) sounds, its annoying to hear them in kamadan.
Also maybe add an option to remove the tonic sounds in explorable areas, like kuunavangs cry.

**Comment by HasKha** [comment]
poor fireworks, they are so cute :(

**Comment by Azzurvif** [comment]
And minis' song !
I like my kuunavang but it is noisy
