### ISSUE TITLE
Running toolbox with gw.exe -dx8 Issues

### ISSUE THREAD

**Issue by philthemes** [HasKha/GWToolboxpp#107]
Gw does not work well with intel graphics chips/windows 10 (not sure which is causing the rendering issue), so I have to run it with -dx8 to get rid of huge streaks of colour (see attached). However, I can't seem to find a way to run gw with the dx8 command and toolbox. Is there anything I can do fix it?

tb++ works perfectly with DirectX9 but I get those streaks with 9, is there anything I can do on my end to get tb to work with DirectX8? Or a way to get rid of this render bug in DX9.

Pls help :(

![screenshot 9](https://cloud.githubusercontent.com/assets/28511484/25785042/39073b46-3345-11e7-9cc1-c4c09a327ead.png)

**Comment by GregLando113** [comment]
Sadly as it is, GWToolbox++ has no support for directX 8, and im not sure if we will ever make efforts to support it in the future. However if there is enough desire for dx8 support, I could look into making a dx8 hook to build compatibility

**Comment by philthemes** [comment]
I fixed it, I think the driver best buy installed for me was either corrupted or trash. I found a way around the manufacturer block on yt and everything runs seamlessly for now anyway.

Thanks :D
