### ISSUE TITLE
chat commands to load builds

### ISSUE THREAD

**Issue by Hour-of-the-Owl** [HasKha/GWToolboxpp#108]
1. `/load emo` would load the first build it finds in `Documents\Guild Wars\Templates\Skills` that starts with "emo" and is the correct primary profession.
2. `/load scs uw emo` would load the first build it finds in `Documents\Guild Wars\Templates\Skills\SCs\UW` that starts with "emo".
3. `/load OgNDwcPPT3M0laRkEyDxDHE1CA` would load OgNDwcPPT3M0laRkEyDxDHE1CA. Obviously nobody is going to type that in, but they may want to use it as a hotkey.
4. `/loadhero1 emo` would load onto your first hero the first build it finds in `Documents\Guild Wars\Templates\Skills` that starts with "emo" and is the correct primary profession.

Is all this possible, and can it be improved?

**Comment by HasKha** [comment]
looks good and possible. Only issue is that build (and file) names can have spaces, so how do you distinguish between /"uw emo.txt" and /"uw"/"emo.txt" ? Or rather, which one do you choose?

**Comment by Hour-of-the-Owl** [comment]
Don't accept spaces in names. I mean if you want "Golt DoA caller" you'd just type `/load goltdoacaller` or `/load scs doa goltdoacaller`. All spaces will be interpreted as folders.

**Comment by HasKha** [comment]
personally, I don't use folders and have plenty of spaces in my builds. I think different users would prefer different behavior.

**Comment by Hour-of-the-Owl** [comment]
Are your spaces meaningful, though? I mean do you have 2 different builds called "Golt DoAcaller" and "GoltDoA caller", or is "goltdoacaller" unique?

**Comment by HasKha** [comment]
no, but a user that has spaces in their builds and doesn't even know that you can have folders, expects `/load fire ele` to work and not give an error, and `load fireele` would not be intuitive. Even for me, it's more intuitive to `/load fbgm caller` than writing that without spaces.

**Comment by Hour-of-the-Owl** [comment]
Yeah I can see your point. Can we put `\`s or something in there for folders instead of spaces? If not, is there a really good reason to bother with the folder functionality?

**Comment by HasKha** [comment]
I'm thinking to allow `/` (`/load fbgm/caller`) and have an option to interpret spaces as `/`

**Comment by reduf** [comment]
I think the best is just to parse it with the space.
e.g. `/load some build` will load `Documents\Guild Wars\Templates\Skills\some build.txt`
and `/load folder/some build` or `/load folder\somebuild` will load `Documents\Guild Wars\Templates\Skills\folder/some build.txt`

**Comment by reduf** [comment]
Added.
We will probably make `/load` (w/o arguments) open the windows with all skills templates.
