### ISSUE TITLE
Automatically re-apply LB title on certain events

### ISSUE THREAD

**Issue by AnonymousII** [HasKha/GWToolboxpp#116]
a feature to automatically re-apply the LB title on certain events (like using dark escape, getting bonded with life bond or prot bond, etc. - basically wherever it makes sense for dmg reduction) would be cool - although it's already available as a hot key it would be much easier if toolbox does this automatically instead of the player who always has to pay attention to these events. So the player can focus on his actual doa job instead of manually re-applying LB title. If you can enable/disable it in tb settings it shouldnt disturb other players who still want to do this manually.

**Comment by reduf** [comment]
Most likely won't happend.

**Comment by HasKha** [comment]
Agree with reduf. With few obvious exceptions, the goal of toolbox is to make playing easier, not have it play for you. This is why I think hotkey is good while a fully automated solution is not.
