### ISSUE TITLE
antivirus trigerred as f*ck

### ISSUE THREAD

**Issue by afmart** [HasKha/GWToolboxpp#118]
https://www.microsoft.com/security/portal/threat/encyclopedia/entry.aspx?name=Trojan%3aWin32%2fFuery.A!cl&threatid=2147718513&enterprise=0

https://www.virustotal.com/en/file/2ede13469382c3ce2bdade971b92411c447be1a24529ed76d4454162aeaea3cc/analysis/

**Comment by HasKha** [comment]
Wow... that's the highest detection ration I've ever seen. And the file itself hasn't changed.

You can use the autoit launcher if you are scared about it
https://www.virustotal.com/en/file/237c93c9c9f35d7e260b97454f07a8085ecaa4595054c317330ae85d36575457/analysis/1495472390/
https://github.com/HasKha/GWToolboxpp/releases/download/2.0-launcher/GWToolbox.exe

**Comment by HasKha** [comment]
Looks like virustotal detection rate is back to normal, getting 1/63 now.
