### ISSUE TITLE
Query Guildwiki

### ISSUE THREAD

**Issue by solos-github** [HasKha/GWToolboxpp#119]
I would like a current zaishen-tasks widget.
A mediawiki api query for zaishen-vanq, mission and so on.
And maybe a pcon option for the fire imp for characters below level 20.

**Comment by reduf** [comment]
I don't think we will do zaishen widget. (If you talk about zaishen quests)
Although, all you want related to zaishen missions/zones/bounties can be found on GuildWiki on the main page. (see: https://wiki.guildwars.com/wiki/Main_Page)

**Comment by HasKha** [comment]
While possible, this is the kind of widget that is only useful to few and would be more suited as a plugin if we manage to finally implement a plugin system.

**Comment by HasKha** [comment]
related to this, maybe something simple and effective would be to make a `/zquests` command that prints the daily quests. I don't know if there are better ways to do it, but we can always parse the wiki html pages.

**Comment by 3vcloud** [comment]
Daily quests included from 3.0
