### ISSUE TITLE
Travel window - Urgoz's text is still visible under right column when window is narrow

### ISSUE THREAD

**Issue by kazerniel** [HasKha/GWToolboxpp#1196]
![image](https://github.com/user-attachments/assets/68d2db6f-c13b-4d06-bf8a-7f4fc835bf20)

(Tbh I'd be happy if all the defaults were removed, so each user could just set their personally relevant outposts. I literally never use the bottom 4.)

**Comment by BearsMan** [comment]
Just use unlock move all in the settings to widen the widget out, unless it is a bug on your end. I'm not sure.

**Comment by kazerniel** [comment]
> Just use unlock move all in the settings to widen the widget out, unless it is a bug on your end. I'm not sure.

No, I want the window to be narrow, the only issue is that the text label shows up underneath the Deep one. The labels above it don't do that. Just need the overflow to be hidden :) Maybe the scroll icon messes something up? That seems to be the only difference.
