### ISSUE TITLE
Check in which instances Toolbox is already running on startup

### ISSUE THREAD

**Issue by AnonymousII** [HasKha/GWToolboxpp#120]
Whenever tb is started while more than one instance of gw is running it always displays a combobox where you have to choose in which gw instance tb should be injected. Even in situations where this makes absolutely no sense, e.g. when you got two gw instances and tb is already running in one of them - starting tb twice in the same gw instance doesnt make any sense, so what else should the user choose in this popup?

So it would be nice to check on tb startup in which gw instances tb is already injected and filter them out of the list - if theres only one gw instance without tb left just start it there and dont ask where to start. Should be really easy to implement - e.g. just list the loaded dlls for each gw instance and check for tb dlls.

It would also be nice to have a button "Inject into all gw instances" so you dont have to do it for every instance manually.

**Comment by HasKha** [comment]
I tend to prefer to keep the launcher as simple as possible, to avoid both antivirus false positive detection and various injection bugs, but this is a very good point and we should do it if possible.

**Comment by AnonymousII** [comment]
the easiest solution is probably just making a list of gw window handles and/or names and put it in some temporary file - I would be surprised if this behaviour triggers an antivirus detection :)

**Comment by reduf** [comment]
Fixed in 7d24e64
Not that it will still show the char selector even if you can only inject one process, because it is not necessary obvious in which client you want to inject the toolbox.
