### ISSUE TITLE
[Bug] /useskill disconnects party at end of cutscenes

### ISSUE THREAD

**Issue by AbyssalMonkey** [HasKha/GWToolboxpp#121]
Use of the chat command of /useskill will cause entire party to disconnect at the end of any cutscene

Steps to reproduce: 

- /useskill x

- Wait till end of cutscene

- Entire party disconnects, ending the instance

**Comment by HasKha** [comment]
thanks for the report, I'll check

**Comment by HasKha** [comment]
fixed in https://github.com/HasKha/GWToolboxpp/commit/3205a68e6f60ca4374c68d171ffacd808840ce22
