### ISSUE TITLE
Builds tab suggestions

### ISSUE THREAD

**Issue by GWisLove** [HasKha/GWToolboxpp#127]
First thing, I want to **thank you** for this great tool, really helpful.

The "builds" tab is good, but it would be even better if there was an option for **Loading** the build (and not just send it to the chat).

Another option that can be nice is to organize the builds with categories (Such as "Fowsc", Doasc", "dungeons"... etc).

What do you think?

**Comment by HasKha** [comment]
Thanks. 
I'll see if I can add a build to load a build.
I'd say no to groups, as it would need a change in how the existing builds are saved. I suggest to use empty builds and just put some name like ==== FoW ==== as separators

**Comment by HasKha** [comment]
implemented loading in https://github.com/HasKha/GWToolboxpp/commit/9393dfa5c635165bba272741898789ce11e940d0
