### ISSUE TITLE
GWToolbox.dll not loaded

### ISSUE THREAD

**Issue by PhilohGW** [HasKha/GWToolboxpp#128]
I got "Errer: GWToolbox.dll was not loadad, unknown error" DEP is Off and i Whitlisted GW.exe and Toolbox.exe on Firewall and on antivirus program. Started both as Admin.
Toolbox not even create an Folder in %Appdata%

**Comment by HasKha** [comment]
I don't really have a solution for this unfortunately. Please check #6 and follow up there, closing this.
