### ISSUE TITLE
Item Stack Movement

### ISSUE THREAD

**Issue by UltraPower31** [HasKha/GWToolboxpp#130]
Could you please add a feature that moves an item stack from the inventory to the next free slot in the currently opened xunlai chest register or from the chest to the next free slot in your inventory by holding down shift and double clicking on the item?

**Comment by HasKha** [comment]
I like the idea, but there are a few technical challenges that prevent us from implementing this: 
* Know when an item is clicked (install a callback)
* Know if the chest window is open
* Know which xunlai tab is selected

We are talking internally about this and how to do it.

**Comment by reduf** [comment]
Done in 91c1574
