### ISSUE TITLE
party re-order

### ISSUE THREAD

**Issue by Hour-of-the-Owl** [HasKha/GWToolboxpp#132]
would be pretty handy if a chat command could kick and add people in a pre-defined/customizable order e.g. for DoA kick and add all primary mesmers; when they've all accepted kick and add the monk, and then the emo

**Comment by ritlew** [comment]
what would be the difference between a proper and simple implementation?

**Comment by HasKha** [comment]
a naive implementation would kick everyone and then invite people in pre-determined order. Would probably have to break or halt if some player left the instance. 

A proper implementation would be smart about only kicking the people required for reorder (also allowing different combination of mesmer/tank order), and somehow handling people leaving, rerolling, etc.

**Comment by ritlew** [comment]
would the user have to specify the order?

**Comment by Hour-of-the-Owl** [comment]
well yes, obviously? there could be some default ones, but the option to set your own order is kinda the point

**Comment by Azzurvif** [comment]
A dedicated new party window would allow this improvement. No more need to kick, you reorder the way you want.
It could be linked with the damage % window.

**Comment by Hour-of-the-Owl** [comment]
^ That would actually be amazing, although it would conflict with people saying stuff like "drop prot on 4" or "blind on 1".
