### ISSUE TITLE
Toggle Tick after Rezone

### ISSUE THREAD

**Issue by PhilohGW** [HasKha/GWToolboxpp#135]
Is it able to Make a auto Tick func if you Rezone?
If i toggle Pcons in GH it will obvious Tick (as long as i got it in settings obviously..)
If team TPs into Doa my tick is out, so i have to Tick manual, or Disable - Enable Cons again to get my Pick.. Probably make a auto Tick after rezone into another outpost

**Comment by Hour-of-the-Owl** [comment]
how about every time you zone, TB checks if you have pcons on, and ticks if you do?

**Comment by HasKha** [comment]
honestly, I disagree. Ticking is the player saying "I'm here and I'm ready". If toolbox did that, the player could be AFK and the tick would lose its meaning. 

Personally, I quickly toggle pcons on and off to re-tick and I think it's ok.
