### ISSUE TITLE
Optional Click on timer to /age in chat

### ISSUE THREAD

**Issue by PhilohGW** [HasKha/GWToolboxpp#137]
Some Random suggestions i recently recogniced:

is it possible to Click (evtl. cnrt Click) on timer to use /age? so if u click it u poste your age in chat, or probably send to teamchat.
Same for DMG Widget.

Bondmonitor recognice death allys such as stones as an target for Bond - advantage of it, if u use 3Stone and eg the first one dies, you still cna bond the second whos still in the right order (sorry dont know whop to say in proper english) so prob forget about that one.

**Comment by HasKha** [comment]
Most widgets are intentionally click-through, for better integration with the game (imho). 

Making timer and damage widgets absorb click events would be undesirable for a part of the userbase (me included) so it would have to be optional.
