### ISSUE TITLE
custom agent appearance on minimap

### ISSUE THREAD

**Issue by Hour-of-the-Owl** [HasKha/GWToolboxpp#139]
Having certain pre-defined bosses appear larger is pretty helpful, but it'd be even better if you could specify your own choice of agent types and customize their colour as well as size. Personally I'd use this for torment claws (so I can quickly see what's left over at 6-0) and maybe some other stuff; at least one person wants stygian fiends in a different colour, and I'm sure there are other examples.

**Comment by HasKha** [comment]
already in #62
