### ISSUE TITLE
Toolbox++ Char Selector

### ISSUE THREAD

**Issue by PhilohGW** [HasKha/GWToolboxpp#142]
Since a few releases the Toolbox++ Char Selector (if you got more then 1 gw running) got a upturned order for the gw instances.. so the current (or better say last opened) Window is not the default chosen. So if i run a Guildwars and start Toolbox, then run another one, toolbox will chose my first guildwars as default option. Would be awesom if you can reverse it.

**Comment by HasKha** [comment]
@GregLando113

**Comment by reduf** [comment]
Fixed in 7d24e64
Not that it will still show the char selector even if you can only inject one process, because it is not necessary obvious in which client you want to inject the toolbox.
