### ISSUE TITLE
toolbox widgets keep going back to default spot after i move them around into where i want them

### ISSUE THREAD

**Issue by BearsMan** [HasKha/GWToolboxpp#143]
having problems with the widgets when I try moving them to where I want them it goes back to where they originally were
![gw003](https://user-images.githubusercontent.com/34116754/33432919-c2dcb6ac-d5a7-11e7-8b3f-65e74e66e385.jpg)

![gw002](https://user-images.githubusercontent.com/34116754/33432861-91c6c116-d5a7-11e7-9b4a-d7f14e86d7a2.jpg)

**Comment by DiazExMachina** [comment]
I have the same problem: every time I Alt+Tab the game the widgets move themselves back to their default position.

**Comment by HasKha** [comment]
I'll look into this when I have time. Issue is probably caused by my quick fix for the freeze when launching in fullscreens. 

I noticed the issue on my machine when restoring from fullscreen->minimize, but I didn't have it in any other case, so I might have issues replicating.

**Comment by HasKha** [comment]
should be fixed in 2.5

Please let me know if the issue still occurs in version 2.5
