### ISSUE TITLE
Auto start Toolbox with GW

### ISSUE THREAD

**Issue by DiazExMachina** [HasKha/GWToolboxpp#144]
Is it possible to make Toolbox run automatically when starting GW through GW Launcher? Like the way it can load textures on uMod automatically.

**Comment by HasKha** [comment]
Yes, GW launcher has a feature to automatically load one or more .dll on launch. You need to move the toolbox.dll file (find it from toolbox->settings->open settings folder) into the plugins folder of the GW Launcher.

**Comment by GambitBandit** [comment]
Just wanna clarify since the GW Launcher readme says "If you create a folder named "plugins" within the Gw.exe folder, the launcher will load all .dll's inside this folder on launch."
So is it the gw.exe folder or the GW launcher folder? And is that all you need to do, simply copy paste the toolbox.dll?
Thanks

**Comment by HasKha** [comment]
> So is it the gw.exe folder or the GW launcher folder?
Not sure, I'm not using it atm and it changed with the GW Launcher version. Trust the GW launcher website or try both. 

> And is that all you need to do, simply copy paste the toolbox.dll?
Yes. "GWToolbox.exe" injects the dll into an existing gw client. GW Launcher can do that automatically after launching the game. Toolbox itself (the .dll) doesn't care how it was launched.

**Comment by GregLando113** [comment]
> So is it the gw.exe folder or the GW launcher folder?

It is either depending on whether you want it to load for all copies or just that installations copy.

**Comment by GregLando113** [comment]
As a note, it is both, if it is the Gw.exe folder, it will only load for accounts ran on that install, GW Launcher folder will load for all accounts
