### ISSUE TITLE
Customize colors for each custom markers

### ISSUE THREAD

**Issue by takepen** [HasKha/GWToolboxpp#150]
hey i have some litte but nice ideas to improove the Toolbox minimap,

1. Different collors for the custom marker and lines 
for each marker/lines you can chose a different colour

2. Folder for Costum marks 
you can add some folders to keep the gui clear 
to keep the gui clear you can add some folders (like the drop down menu -Agents -Ranges ...)

3.  Different colours for enemys
you can chose a color for each enemy you like (Checks the model ID)

4. you can set the hero flags on the ground like the vanilla flag (not even on the map)

now a small idea

5. gw client will flash when you get rez and gw client was minimitzed

cheers 
takepen

**Comment by HasKha** [comment]
linking to https://github.com/HasKha/GWToolboxpp/issues/62

**Comment by Hour-of-the-Owl** [comment]
`Different colours for enemys
you can chose a color for each enemy you like (Checks the model ID)`
there is a version of TB that does this already - is it difficult to implement it into the official one?

**Comment by HasKha** [comment]
for reference: https://github.com/Eppa93/GWToolboxpp-2.8 adds a list of npcs with customizable color for each

**Comment by HasKha** [comment]
3 was done. 4 is hard and it's in #61 . Changing issue title to reflect 1 and 2.
