### ISSUE TITLE
price check window (https://kamadan.decltype.org/ front-end)

### ISSUE THREAD

**Issue by HasKha** [HasKha/GWToolboxpp#152]
essentially, have https://kamadan.decltype.org/ on a toolbox window. 

A few notes:
* make sure to credit the website author (decltype). 
* make sure the author is OK with this.
* the website once used a rest json api (might be still up?). 
* It uses json through websockets now. 
* for details, look into the javascript file loaded with the page. 
* `/pc` should open this window, `pc item` should open the window and search for `item`. 

There are a few options for an implementation
* use the rest json api if it's still active, and render it
* use the websocket api and render it
* get the html page, parse it, and render it
* render html directly from within imgui (https://twitter.com/ocornut/status/890210588600565762)

**Comment by ritlew** [comment]
I'll take a whack at it

**Comment by ritlew** [comment]
looks like ws would be the way to go. What should I use for websockets in c++?

**Comment by GregLando113** [comment]
will most likely have to write it yourself using winsock, just an initial http get or w/e the http request is to start connection then be able to handle the request to change to websockets, also you need to ssl authenticate, maybe some winhttp lib can make this easier

**Comment by ritlew** [comment]
ive actually got something in the works with websocketpp. it uses openssl and boost as dependencies though, which would add MBs to the project size. I basically have it all working except for the UI. I would just need to finish that. I don't know how you guys feel about the extra libraries though.

**Comment by HasKha** [comment]
I don't like that. But also (from https://github.com/zaphoyd/websocketpp/wiki)

> In order to remain compact and improve portability, the WebSocket++ project strives to reduce or eliminate external dependencies where possible and appropriate. WebSocket++ core has no dependencies other than the C++11 STL.

> WebSocket++ implements a pluggable data transport component. The default component allows reduced functionality by using STL iostream. This component has no non-STL dependencies and can be used in a C++11 environment without Boost. Also included is a Boost ASIO based transport component that provides full featured network client/server functionality.

Can you see if the core reduced functionality based on stl is enough for this project?

**Comment by ritlew** [comment]
So I see that page is referring to 0.3.X, and the version I'm using is 0.8.0. I'd imagine these are miles apart as very few documents I found were up to date. And it looks like the wiki isn't up to date either. FWIW I'm looking at 138MB for boost and 15MB for openssl.

**Comment by HasKha** [comment]
Oh I just looked at the first google result, didn't see the version. 

The readme of 0.7 states:

> It uses interchangeable network transport modules including one based on raw char buffers, one based on C++ iostreams, and one based on Asio (either via Boost or standalone).

So maybe that boost dependency is still optional. 

Overall I don't like unnecessary dependencies not just because of size, but also ease of compilation and usage.

**Comment by ritlew** [comment]
Yeah I see that as well. I'll see what I can do. I don't want to use the boost library either but I didn't think it was optional.

**Comment by ritlew** [comment]
OK. That was more painless than I thought. It can use the standalone ASIO library which is only 2MB. It is still an extra dependency in the folder though.

**Comment by ritlew** [comment]
Update for interested parties:

![tradechat](https://user-images.githubusercontent.com/16658359/37082176-c493961a-21b9-11e8-945d-f44823b7c91e.PNG)

Still working on the UI as well as searching. I'm also thinking about implementing Alerts where you can define keywords and it will display a chat message letting the user know.

**Comment by ritlew** [comment]
> make sure the author is OK with this.

How do we contact the author?

**Comment by HasKha** [comment]
> How do we contact the author?

There used to be an email embedded in the html source and I previously messaged him there and on reddit and never got a reply. 

https://decltype.org/ has a link to https://constexpr.org/, so I guess that's the author? Not sure.

**Comment by ritlew** [comment]
Near finished product:

![tradechat near final](https://user-images.githubusercontent.com/16658359/37135424-4be9baf2-226b-11e8-9ba5-ff30048bb9f8.PNG)

**Comment by HasKha** [comment]
Nice. A bit of feedback on the UI:
* Overall i would try to match the original website. Remove the time column and couple together more tightly sender and message. Time can be to the left or below the sender.
* We need to credit the website somewhere in the window (header or footer)
* Try to emphasize rows, not columns (also no need for column headers)
* 'Alerts' button doesn't need the whole width and can be probably in the same row as the search bar. 

Sorry if those are obvious and you were already going to improve it, just being sure. Also I can work on the UI after the PR if you want, I don't mind doing UI stuff.

**Comment by NTBugtraq** [comment]
Pablo Busse is the author/owner of kamadan.decltype.org. He can be reached via Pablo@decltype.org

Please note, Pablo does not display every entry that could be retrieved in a search. From a conversation he and I recently had;

> This is one of those things which is not really a bug, but more of a necessary trade-off for performance reasons. We already discussed this in-game, but let me explain it more in detail:
> 
> The reason for the behavior you're observing is that each search only looks as far back as needed to retrieve a sufficient number of results (25 per page). If the entire index were to be searched, there could be quite a lot of results since the messages date back to January 2014. So, to keep queries fast even for many years into the future, there has to be a cut-off.
> 
> Of course, if only part of the index is looked at, the total number of results can only be estimated. The way this estimate works is as follows (straight from the source code):

    if (searched_exhausted_index)
    {
        result_count = matching_records.size();
        result_count_accuracy = exact;
    }
    else
    {
        double hit_rate = limit / (index_size - remaining_documents);
        result_count = round(hit_rate * index_size);
        result_count_accuracy = estimate;
    }

> In this particular case, when searching based on a single criterion, it's actually possible to do a little better. The number of documents matching an author or single query word is known in advance since it's simply the length of the associated posting list.
> 
> There is however an additional difficulty: Documents can be deleted at any time at the request of a player, but it's not possible to immediately remove all occurrences of the document from the index without shifting a lot of data around. For this reason, the document is flagged as deleted and simply skipped at match time. It stays this way until the next time that part of the index gets reorganized, at which point the empty space left over by the deleted document is reclaimed.
> 
> So if deleted documents should not be counted, each word would need to maintain an additional deletion counter. But then, deletion requests would involve one disk I/O operation per word in the message, rather than a single operation the way they are implemented right now.
> 
> That is the main reason I have not added a special case for single-criterion queries yet.
>

**Comment by NTBugtraq** [comment]
Also, remember that you can search kamadan.decltype.org by author too.
