### ISSUE TITLE
Message when someone on friendslist comes online

### ISSUE THREAD

**Issue by AnonymousII** [HasKha/GWToolboxpp#153]
When you're waiting for someone on your ingame friendslist to come online it would be nice to have any kind of notification (chat message, popup, etc) when somebody comes online, so you don't have to check the list manually over and over again.

Possible customizations would be:

- All fl members / only a list of given names
- Disable option for explorable areas (could be annoying in runs) 
- (as usual full disable / enable option)
- if realized as chat message custom color would also be nice

Since the friendslist automatically updates ingame there must be any notification (network paket to the client) when this happens, so it's probably just another network package to catch

**Comment by reduf** [comment]
For customizations, I think the best would be "enable" & "disable".
Adding more functionality would add friction because the settings keep getting bigger.

**Comment by Hour-of-the-Owl** [comment]
A simple implementation of this (PM from TB every time a friend logs on) would be fantastic, but it mighttt potentially be annoying when someone is rapidly changing characters. Then again, chat filter does a pretty good job of keeping the chat clean, so even that should be tolerable.

**Comment by HasKha** [comment]
Good idea, but agree with @reduf and @Hour-of-the-Owl.

**Comment by reduf** [comment]
Added bb38248e06ca4d23c784cc4e99d1c34556c5f5fc
