### ISSUE TITLE
Allow multiple skills in /useskill

### ISSUE THREAD

**Issue by HasKha** [HasKha/GWToolboxpp#16]
Originally reported by: **Giorgio Gori (Bitbucket: [ggori](https://bitbucket.org/ggori), GitHub: Unknown)**

---

/useskill could accept multiple skills and use them in order. 
For example, /useskill 124 would use skill 1 if recharged, otherwise skill 2 if recharged, otherwise skill 4 if recharged. Simple recharge check without upkeep, but it would help afk emos or tanks.

---
- Bitbucket: https://bitbucket.org/ggori/gwtoolbox-plusplus/issue/21

**Comment by Hour-of-the-Owl** [comment]
idk, generally encouraging people to AFK isn't great... it's already a problem koz people do it at Dhuum and then what if he unglitches?

**Comment by HasKha** [comment]
before /useskill was a thing, people would use the mouse clicker, put their mouse on 1 and go away from pc. At least now they /useskill and alt-tab, and can be called back on ts if there is a problem.

**Comment by Hour-of-the-Owl** [comment]
yeah I'm not suggesting to revert to that - just don't agree with expanding it so people do it MORE

**Comment by HasKha** [comment]
implemented in 2.6
