### ISSUE TITLE
TB doesnt open

### ISSUE THREAD

**Issue by ShayaKaraya** [HasKha/GWToolboxpp#166]
Not botting or anything before.
It says:
"No Guild Wars clients found. Please log into Guild Wars first."
obviously i am logged in etc.
tried to restart the client multiple times, doesnt work.
have the problem since a few days maybe 2 weeks (?)

**Comment by ShayaKaraya** [comment]
help

**Comment by HasKha** [comment]
sorry about that. It might be a launcher or antivirus problem. Make sure that `GWToolbox.dll` is present in the settings folder (https://haskha.github.io/GWToolboxpp/settings -> storage). You can also try one of the two launchers here (https://github.com/HasKha/GWToolboxpp/releases/tag/2.6_Release)

**Comment by jivavoda** [comment]
GW Toolbox 2.10 can't be launched. Both files (2.10 and release) were added into the white list and described folder in C, but when I restart it nothing happens. Help please!

**Comment by reduf** [comment]
Does https://github.com/HasKha/GWToolboxpp/issues/170 help you ?

**Comment by reduf** [comment]
Should be fix with the new launcher that can be found here: https://github.com/HasKha/GWToolboxpp/releases/tag/2.14_Release
