### ISSUE TITLE
Error: Failed to call EnumProcessModules

### ISSUE THREAD

**Issue by xtinctp** [HasKha/GWToolboxpp#170]
Hello, i cant get TB to work, i deleted all old TB files and re downloaded 2.8, it either doesn't change anything ingame or give me this Error code 10.

went step by step of whitelist and admin rights.

**Comment by Bu11etmagnet** [comment]
---------------------------
GWToolbox++
---------------------------
Error: Failed to call 'EnumProcessModules' (2)

Error code: 10

Return value: 0
---------------------------
OK   
---------------------------

**Comment by Bu11etmagnet** [comment]
Alas, your suggestion results in #195

**Comment by reduf** [comment]
Should be fix with the new launcher that can be found here: https://github.com/HasKha/GWToolboxpp/releases/tag/2.14_Release
