### ISSUE TITLE
automatically open minions window

### ISSUE THREAD

**Issue by Hour-of-the-Owl** [HasKha/GWToolboxpp#173]
The minions window closes itself on zoning, which is pretty annoying - could TB detect the open/closed status when zoning, and re-apply it when zoning?

Alternatively, how about detecting whether or not a bar has any spirit/minion skills, and if so, opening the minions window when entering an explorable?

**Comment by Hour-of-the-Owl** [comment]
It would also be superhelpful if the window itself was invisible (and click-through)... the only part I want to see and be able to click on is the actual health bars. Obviously the title bar needs to be somewhat accessible so you can move it around, but much like TB widgets, I assume most people find a good position for it and then never (or rarely) move it again.

**Comment by thiefa** [comment]
hi, 
please expand this to open the pets bar aswell

i like to play as beastmaster, thus i have my pets bar open, witch gets closed each time i zone like the minion bar.

**Comment by Hour-of-the-Owl** [comment]
yeah having to re-open the pet window every time I start a new match in RA is incredibly annoying

**Comment by HasKha** [comment]
All good ideas, but we don't yet have much knowledge of the gw interface, and cannot easily do this, at least for now. 

Leaving open as it is still a good idea to implement when/if we can.

**Comment by Hour-of-the-Owl** [comment]
`Alternatively, how about detecting whether or not a bar has any spirit/minion skills, and if so, opening the minions window when entering an explorable?`

That part should be easy to do though, right? Here's a list of skills that will give you a minion or spirit:

Animate Bone Fiend
Animate Bone Horror
Animate Bone Minions
Animate Candy Golem (Scarred Psyche)
Animate Flesh Golem
Animate Shambling Horror
Animate Vampiric Horror
Aura of the Lich
Star Servant (you only get this after already entering the zone though)
Verata's Aura
Verata's Gaze

Agony
Anguish
Bloodsong
Call to the Spirit Realm (Togo)
Destruction
Disenchantment
Displacement
Dissonance
Earthbind
Empowerment
Gaze of Fury
Jack Frost (Wintersday)
Life
Pain
Preservation
Recovery
Recuperation
Rejuvenation
Restoration
Shadowsong
Shelter
Signet of Binding
Signet of Spirits
Soothing
Union
Vampirism
Wanderlust

Brambles
Conflagration
Edge of Extinction
Energizing Wind
Equinox
Famine
Favorable Winds
Fertile Season
Frozen Soil
Greater Conflagration
Infuriating Heat
Lacerate
Muddy Terrain
Nature's Renewal
Pestilence
Predatory Season
Primal Echoes
Quickening Zephyr
Quicksand
Roaring Winds
Symbiosis
Toxicity
Tranquility
Winds
Winnowing
Winter

**Comment by reduf** [comment]
Guild Wars now keep the minions window open. https://wiki.guildwars.com/wiki/Feedback:Game_updates/20180613
