### ISSUE TITLE
team builds not saving

### ISSUE THREAD

**Issue by Hour-of-the-Owl** [HasKha/GWToolboxpp#174]
Changes to team builds are not saved unless the Builds window is open.

**Comment by HasKha** [comment]
more specifically, changes are saved when the Builds window gets closed (https://github.com/HasKha/GWToolboxpp/blob/master/GWToolbox/GWToolbox/Windows/BuildsWindow.cpp#L211). This is an issue if you open Builds window -> open a specific teambuild -> close Builds window -> close teambuild.
