### ISSUE TITLE
add whisper channel to send chat hotkey

### ISSUE THREAD

**Issue by Hour-of-the-Owl** [HasKha/GWToolboxpp#176]
I specifically want to be able to PM myself reminders at regular intervals e.g. "put your legionnaire back in the chest", so I'd be perfectly happy if this only worked for self PMs, rather than giving the opportunity to easily spam someone else. Of course, a hotkey to put the legio straight in the chest would be even better...

**Comment by reduf** [comment]
Added in fcfd8ea
In "Message" input box, the format is `<name>,<message>`
