### ISSUE TITLE
You fucked GWTB?

### ISSUE THREAD

**Issue by NTBugtraq** [HasKha/GWToolboxpp#181]
2 Days ago I was using the committed 2.8 code and stuff worked. 2 Days late I sign on, there are no ovious commits, not obvious code changes, and nothing works. I see the code reaching out to Kamadan.decltype.org, yet not one commit suggests that's been implemented.

So, you fucked the entire codebase by doing what?

**Comment by HasKha** [comment]
there was a game update that changed quite a bit internally. Pretty much all 3rd party programs are broken atm. We are working on a fix.

**Comment by KevinDenis** [comment]
Headers got updated during last update (23/03/18) updated the header which broke the comuication between the toolbox and the gw client. Please refer to https://wiki.guildwars.com/wiki/Game_updates and https://www.reddit.com/r/GuildWars/comments/86obrp/new_gw_update/?st=jf5sbae8&sh=e7ee3e74
