### ISSUE TITLE
Cloning, properly, the current master leads to errors

### ISSUE THREAD

**Issue by NTBugtraq** [HasKha/GWToolboxpp#182]
C:\Users\Russ>git clone --recursive https://github.com/HasKha/GWToolboxpp.git
Cloning into 'GWToolboxpp'...
remote: Counting objects: 10156, done.
remote: Compressing objects: 100% (119/119), done.
remote: Total 10156 (delta 121), reused 127 (delta 79), pack-reused 9957
Receiving objects: 100% (10156/10156), 31.90 MiB | 662.00 KiB/s, done.
Resolving deltas: 100% (7195/7195), done.
Submodule 'Dependencies/GWCA' (https://github.com/GregLando113/GWCA.git) registered for path 'Dependencies/GWCA'
Submodule 'Dependencies/imgui' (https://github.com/ocornut/imgui.git) registered for path 'Dependencies/imgui'
Cloning into 'C:/Users/Russ/GWToolboxpp/Dependencies/GWCA'...
remote: Repository not found.
fatal: repository 'https://github.com/GregLando113/GWCA.git/' not found
fatal: clone of 'https://github.com/GregLando113/GWCA.git' into submodule path 'C:/Users/Russ/GWToolboxpp/Dependencies/GWCA' failed
Failed to clone 'Dependencies/GWCA'. Retry scheduled
Cloning into 'C:/Users/Russ/GWToolboxpp/Dependencies/imgui'...
remote: Counting objects: 19065, done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 19065 (delta 4), reused 6 (delta 1), pack-reused 19051
Receiving objects: 100% (19065/19065), 19.65 MiB | 663.00 KiB/s, done.
Resolving deltas: 100% (13774/13774), done.
Cloning into 'C:/Users/Russ/GWToolboxpp/Dependencies/GWCA'...
remote: Repository not found.
fatal: repository 'https://github.com/GregLando113/GWCA.git/' not found
fatal: clone of 'https://github.com/GregLando113/GWCA.git' into submodule path 'C:/Users/Russ/GWToolboxpp/Dependencies/GWCA' failed
Failed to clone 'Dependencies/GWCA' a second time, aborting

Notice how it fails to properly clone the GitHub?

**Comment by NTBugtraq** [comment]
I thought that kind of shit wasn't supposed to be committed??

**Comment by HasKha** [comment]
That's correct and expected. 

Ziox and KAOS fixed GWCA but we don't want to help botters fix their bots, and we don't want anyone and especially anet to think of us as bot facilitators, so we decided to make the GWCA a private repository for now. 

I understand that this essentially means that for the time being, you cannot compile GWToolbox by yourself. Our current idea is to close-source the GWCA source files, open-source the headers and release a compiled .lib, however that will take some time to set up and we are currently focused on fixing GWToolbox and releasing it.

**Comment by NTBugtraq** [comment]
I'm sure you will be happy that I, and likely others, will abandon your shit

**Comment by ritlew** [comment]
> Our current idea is to close-source the GWCA source files, open-source the headers and release a compiled .lib

If the bots come back are you going to open source it again? I hear some are already back

**Comment by HasKha** [comment]
>>Our current idea is to close-source the GWCA source files, open-source the headers and release a compiled .lib

> If the bots come back are you going to open source it again? I hear some are already back

In general I am in favor of open-source, so my vote goes for that, but I don't have a strong opinion, and ultimately this is KAOS's decision, not mine. 

Overall none of us are happy with the current situation, and there is no correct solution, as anything we do has some downside. We are just trying to do our best for now, and we might re-evaluate if things change.

**Comment by reduf** [comment]
See: https://github.com/GregLando113/GWCA-Public

**Comment by NTBugtraq** [comment]
I received an email from Arenanet founder Mike O’Brien yesterday, in response to my query as to why my account had been terminated.

In it, he asks me if I was “suspended due to running one of the five banned programs?” Do any of you know the five banned programs, and/or whether or not GWToolbox is on that list?

Cheers,
Russ/Gorth

________________________________

**Comment by HasKha** [comment]
I believe he's referring to this; https://en-forum.guildwars2.com/discussion/comment/476255/#Comment_476255

and no, GWToolbox is not on that list
