### ISSUE TITLE
Add more icons

### ISSUE THREAD

**Issue by HasKha** [HasKha/GWToolboxpp#183]
Now that any toolbox window and widget can be part of the Main window, they could all use some love and a new nice icon. This thread is for suggestions and to keep track of icons we have/need. 

If you have a suggestion, please post:
* The target widget or window.
* Credits, license and/or usage rights.
* The icon, preferably as a 64 x 64 PNG file with transparency. (note: it will probably show up as empty space, as it's white-on-white here on GitHub).
* An image showing the icon used in the main window. It doesn't have to be in the button of the target window/widget, you can just replace one of your existing icons in `C:\Users\%USERNAME%\AppData\Local\GWToolboxpp\img\icons\` to show it on screen without modifying toolbox.

Here is a list of icons we have and need:
Windows:
* [x] [ ] Builds
* [x] Dialogs
* [ ] HeroBuilds
* [x] Hotkeys
* [x] Info
* [x] Materials
* [ ] Notepad (suggestion below)
* [x] Pcons
* [x] Settings
* [x] Trade
* [x] Travel
* [ ] Instance timer (upcoming feature)

Widgets:
* [ ] Alcohol (suggestion below)
* [ ] Bonds (suggestion below)
* [ ] Clock (suggestion below)
* [ ] Damage
* [ ] Distance
* [ ] Health
* [ ] Minimap (suggestion below - needs work)
* [ ] Timer (suggestion below)
* [ ] Vanquish (suggestion below)

**Comment by HasKha** [comment]
Trade window suggestion by Maddow#8892 on Discord:

![](https://cdn.discordapp.com/attachments/223619617048756224/427962920349990912/trade_icon.png)

![](https://cdn.discordapp.com/attachments/223619617048756224/427962836828815370/unknown.png)

**Comment by HasKha** [comment]
Note: most of the current toolbox icons are taken from https://www.flaticon.com/, some with minor edits

**Comment by Hour-of-the-Owl** [comment]
do you think it's superimportant to have very distinct icons for timer, instance timer, and clock? I'm thinking maybe a stopwatch, an hourglass, and an alarm clock... https://imgur.com/a/0lsQi

**Comment by tjubutsi** [comment]
For the bonds monitor?: https://image.flaticon.com/icons/svg/287/287144.svg

**Comment by MaddoW** [comment]
Jo, here my suggsetions for the timer ;)

__In Main Window:__
![clock_insidemainwindow](https://user-images.githubusercontent.com/37832419/37960684-8157bea0-31b6-11e8-95c1-b04f8888495d.png)

__The File:__
![clock](https://user-images.githubusercontent.com/37832419/37960683-813e4c04-31b6-11e8-94ac-5b8d6d58f1e3.png)
Yea, its hard to see since its white, but you can rightclick --> open image in new tab to have it shown with background!

**Comment by reduf** [comment]
https://www.flaticon.com/free-icon/form_87949#term=notepad&page=2&position=32
![notepad](https://user-images.githubusercontent.com/1349199/37972620-b8b6c39c-31a6-11e8-8672-96469d67b0c9.png)

Also, if you take the icon on a website, can you please send the link to the icon ?

**Comment by MaddoW** [comment]
**Minimap**
![image](https://user-images.githubusercontent.com/37832419/38041327-b824e074-32b1-11e8-940c-4e50f72857b7.png)
https://www.flaticon.com/free-icon/radar_149230#term=radar&page=1&position=1

**Comment by MaddoW** [comment]
**Clock**
![image](https://user-images.githubusercontent.com/37832419/38041727-c919227c-32b2-11e8-9898-c2215062da5f.png)
https://www.flaticon.com/free-icon/wall-clock_68132#term=clock&page=1&position=39

__The rotated File:__
![wall-clock](https://user-images.githubusercontent.com/37832419/38041793-f33c3300-32b2-11e8-996f-b3c69d36f528.png)

**Comment by MaddoW** [comment]
**Bond-Monitor:**
![image](https://user-images.githubusercontent.com/37832419/38042148-d7b1ea66-32b3-11e8-854a-7c995a6d38e6.png)
https://www.flaticon.com/free-icon/ankh_287144

**Comment by MaddoW** [comment]
**Alcohol:**
![image](https://user-images.githubusercontent.com/37832419/38042285-41344678-32b4-11e8-9ac1-d1664435c826.png)
https://www.flaticon.com/free-icon/beer_761856#term=beer&page=1&position=48

**Comment by MaddoW** [comment]
**For the Vanquish:**
--> maybe just a Frac like this:
![image](https://user-images.githubusercontent.com/37832419/38043168-a7a8f604-32b6-11e8-9621-49a269f9b57e.png)

**Comment by MaddoW** [comment]
**Timer:**
![image](https://user-images.githubusercontent.com/37832419/38043355-2be9e220-32b7-11e8-95e3-7eead3babe51.png)
https://www.flaticon.com/free-icon/quarter-of-an-hour_66171

**Comment by HasKha** [comment]
Love the suggestions. A few comments:

* Misty is right. Timer/Instance timer/Clock are tricky. They shouldn't be too different, but not the same. In particular, the "Instance Timer" does not have a clear identity, and the name itself might not be ideal.
* I like the ankh/alcohol icons, but they could have thicker lines, they don't match the style of the rest.
* I like the theme of minimap as radar-icon, but the icon itself might be improved, again lines are really thin.
* I don't like the fraction for the VQ monitor. I'm not sure what I would like, but I don't think I like those random numbers there.

**Comment by MaddoW** [comment]
> but they could have thicker lines
Jup, I thought the same, but since I am on my fathers laptop (from 2002 lol) I can't photoshop them better. I will make them better, when I am back home. (If no one else is going to improove them, haha)

>  "Instance Timer" [...], and the name itself might not be ideal.
How could we call it then? I like my suggsetion for the (normal) Timer, and i think it fits to the rest. And aswell the clock, on 16:00, haha.

**Comment by Hour-of-the-Owl** [comment]
Objective Timer or Quest Timer? Did you not like my hourglass icon? )=

**Comment by Hour-of-the-Owl** [comment]
https://i.imgur.com/5sYTl6A.png

**Comment by Hour-of-the-Owl** [comment]
how about this heart for health? https://www.flaticon.com/free-icon/heart_684262#term=health&page=1&position=5

lightning bolt for damage? might make more sense for energy monitor if such a thing existed =P https://www.flaticon.com/free-icon/flash_341248#term=lightning&page=1&position=39

ruler for distance? https://www.flaticon.com/free-icon/ruler_131147#term=ruler&page=1&position=9

also I think you missed the Hero Builds suggestion from @reduf ?

**Comment by 3vcloud** [comment]
can this be closed?
