### ISSUE TITLE
Enemy counter / window size / hero builds

### ISSUE THREAD

**Issue by HiImFlo** [HasKha/GWToolboxpp#185]
Hey,

1. Can we have the current soulcounter as a wildcard so we can enter a target id? Could be nice to track various enemies, like rupters.

2. Manually set size of the guildwars window (width/hight).
I like to have every panel in exactly the same location relative to my interface. Since i play in window mode, I ll sometimes accidentally change the size of the guildwars window and thereby trigger my ocd because stuff isnt lining up properly anymore.

3. Can we get a send chat funtion for hero builds? Maybe also for direct messages and not only party chat?
Also, /open hero builds doesnt work, only /open "hero builds" does. The whole thing doesnt really work for me, it just kicks all the heroes and sends "Bad hero index '7digits' for build 'build'.

Thanks!

**Comment by HasKha** [comment]
1. Can definitely be done
2. I guess we could add a `/resize x y` command or something like that, but a one-line autoit program can do just that: `WinMove("Guild Wars", "", x, y)`. Not sure about this, as I'm not sure how many users would use this. 
3. Send chat: maybe, but I'm afraid non-party chat could be abused to spam people. Functionality: I'll look into it, I might have messed it up in the weekend rush.

**Comment by HasKha** [comment]
Can you please explain the use case of (1), maybe with an example?

is an external solution like the above enough for (2)? I'm really hesitant at implementing functionality for an extremely specific scenario when a solution is already possible.

**Comment by HiImFlo** [comment]
(1) You might want to know how many rupters there are at cave, so if you could make a custom tracker with a custom range you could see how many there are with 1 glance. Same is true for souls, if you could customize the range (other solution is to use color-coded enemies).

(2) works if the client is named "Guild Wars", but not if i its started by multilaunch, thats good enough though!

**Comment by HasKha** [comment]
(2) Instead of "Guild Wars" you can use whatever your window is called, or "[CLASS:ArenaNet_Dx_Window_Class]" to match any gw window

**Comment by HiImFlo** [comment]
Thats what I tried and it didnt work, the suggested code doesnt either. If i put it in "" it just doesnt do anything at all, if i leave the "" away it says unknown function name. But really, its not that big of an issue that you ld have to worry about it, i can just close and restart if i really want to fix it.

**Comment by MaddoW** [comment]
Jo can you put a checkbox to the Enemy Counter in InfoWindow (next to the customized counter with various ModelIDs to count) to enable something like this:
![unbenannt](https://user-images.githubusercontent.com/37832419/38014550-7219dba4-3269-11e8-906b-e2e66291ffb1.jpg)
(''Show on Screen'' or similar)

I also added coloring for certain thresholds:
Red from 0-20
Yellow from 20-40
Green >40

Here is the code for that:
`
						
		snprintf(Soul_Counter, 32, "%02d", souls_count);
		ImVec2 cur;

		// 'Soul Counter'
		ImGui::PushFont(GuiUtils::GetFont(GuiUtils::f24));
		cur = ImGui::GetCursorPos();
		ImGui::SetCursorPos(ImVec2(cur.x + 1, cur.y + 1));
		ImGui::TextColored(ImColor(0, 0, 0), "Soul Counter");
		ImGui::SetCursorPos(cur);
		ImGui::Text("Soul Counter");
		ImGui::PopFont();

		// Counts
		ImGui::PushFont(GuiUtils::GetFont(GuiUtils::f48));
		cur = ImGui::GetCursorPos();
		ImGui::SetCursorPos(ImVec2(cur.x + 2, cur.y + 2));
		ImGui::TextColored(ImColor(0, 0, 0), Soul_Counter);
		ImGui::SetCursorPos(cur);
		if (use_coloring) {
			if (souls_count <= 20) ImGui::TextColored(ImColor(255, 0, 0), Soul_Counter);
			if (souls_count > 20 && souls_count <= 40) ImGui::TextColored(ImColor(255, 200, 0), Soul_Counter);
			if (souls_count > 40) ImGui::TextColored(ImColor(55, 255, 0), Soul_Counter);
		} else {
			ImGui::TextColored(ImColor(255, 255, 255), Soul_Counter);
		}

		ImGui::Text(Soul_Counter);
		ImGui::PopFont();
`

**Comment by HasKha** [comment]
@HiImFlo I it wrong, it's WinMove("title", "", x, y, width, height). That should work.

**Comment by HiImFlo** [comment]
I looked up the function myself and also tried the optional arguments. Still only works when the window is named "Guild Wars" and not "Character Name" (ofc I replaced the first argument in the function with the window's title).

WinMove("Character Name", "", 1500, 1000, 1000, 1000) does nothign when I start gw through gw launcher, WinMove("Guild Wars", "", 1500, 1000, 1000, 1000) works perfectly fine if started by itself.

**Comment by HasKha** [comment]
note that if gw launcher is running as admin, then your script also need to be running as admin to affect gw  (https://www.autoitscript.com/autoit3/docs/keywords/RequireAdmin.htm)

**Comment by HasKha** [comment]
I'm going to split this for clarity. (2) is done with the new /resize command.

**Comment by HasKha** [comment]
bugs with hero builds should have been fixed
