### ISSUE TITLE
give /follow a use

### ISSUE THREAD

**Issue by HiImFlo** [HasKha/GWToolboxpp#187]
So I just learned that /follow is an offical guildwars command but it has no known functionality.

Can we get a /follow command that does exactly what you ld expect it to do, following the selected target (for example either the current target or by party slot)?
Would be great when playing with an alt!

Could this work in conjunction with /useskill?

**Comment by HasKha** [comment]
The problem with this is not difficulty in the implementation, but rather if we want to do it.

First of all, it goes against the basic concept of toolbox, of empowering the user while not playing the game for you. `/follow` does play the game for you.

Secondly, the main use case is developing alt accounts, which is typically done by botters. At the same time, it *could* be used by non-botters to develop your alts for SCs or other specific activities.

Lastly, a `/follow` command/functionality naturally creates desire for more: make it use skills, make it accept quests/rewards, etc. This is a much bigger scope project that could stand on its own.

Overall, I say no to this, as the connection to bots and botting are too strong, while going inherently against the idea behind toolbox. A follow-bot should be a standalone project.
