### ISSUE TITLE
Make borderless move to the current monitor instead of just the primary

### ISSUE THREAD

**Issue by tjubutsi** [HasKha/GWToolboxpp#189]
Some times I just want to sit in kamadan while watching a movie you know.

**Comment by ritlew** [comment]
you can move the window with Windows key + shift + arrow key

**Comment by tjubutsi** [comment]
No, it doesn't

**Comment by ritlew** [comment]
does for me, what OS are you on?

**Comment by tjubutsi** [comment]
w10

**Comment by tjubutsi** [comment]
https://www.youtube.com/watch?v=dHClnU4eJTw

**Comment by ritlew** [comment]
i use the left windows key + shift + arrow key

**Comment by tjubutsi** [comment]
Welp, that works

**Comment by tjubutsi** [comment]
Still think making move to the current monitor instead of primary would be a better default handling

**Comment by HasKha** [comment]
I'm not sure about that actually. I often have gw open on my secondary monitor while afking, and for that staying in windowed mode and so showing the taskbar is a better experience. Then when I'm joining a run I press borderless and it goes to my primary monitor.

**Comment by tjubutsi** [comment]
maybe a setting for which monitor then?

**Comment by HasKha** [comment]
borderless has been implemented in the base game and we don't support it any more, closed.
