### ISSUE TITLE
Starting GWToolbox makes all in-game players look the same

### ISSUE THREAD

**Issue by jmctune** [HasKha/GWToolboxpp#192]
When standing in town, all players look normal. As soon as I launch GWToolbox, all players change to looking exactly the same.

https://imgur.com/a/t0JB1

When I leave town, my character looks normal again -- but when I zone back in, I'm back to seeing everyone (including myself) look the same.

When I turn GWToolbox off while in-game, people continue to look the same, but when I zone out of town and back in, this fixes the issue.

As I am new to using this tool, is this intended functionality? Or is there a setting somewhere to turn this off? Thanks for the help.

**Comment by HasKha** [comment]
[Happy April Fools' Day!](https://en.wikipedia.org/wiki/April_Fools%27_Day)

Note: this was done in the spirit of GW's [April Fools](https://wiki.guildwars.com/wiki/April_Fools%27_Day) events in 2008/2009. Everything will return to normal tomorrow.

**Comment by jmctune** [comment]
Oh geez, I feel so silly posting this then. 

Thanks for the really quick response. :)
