### ISSUE TITLE
Trade Alerts dont appear to happen

### ISSUE THREAD

**Issue by NTBugtraq** [HasKha/GWToolboxpp#194]
I open Trade, then click "Alerts", then check "Only show messages containing:", then enter, for example, consets, into the trade alert text input window...and nothing appears to happen when a trade message with "consets" in it goes across trade chat.

**Comment by reduf** [comment]
Did you check "Send Kamadan ad1..." ?
Also make sure that you wrote a "substring" in the buffer. For instance, if you write "consets" and the message contains "conset" it won't be shown.

**Comment by NTBugtraq** [comment]
Ok, I think I did all you suggested and when the ad with the word "focus" comes across nothing different happens than any other ad. Further, I thought if I told it "Only show messages containing:" I would only see ads that have my keyword "focus" in them...yet I still see every ad.
![gw417](https://user-images.githubusercontent.com/28304154/38468389-8e3fdeae-3b34-11e8-8954-7c1becf68e30.jpg)

**Comment by NTBugtraq** [comment]
I also don't get why some trade messages are red and others are pink.

**Comment by reduf** [comment]
1. The "Darker pink" are the message from ad1 & the "lighter pink" (regular color) are the message from the current district.

2. Check if on a line you have a "space" and thong else. It should be easy to see if you select all the textfield with your mouse.

**Comment by NTBugtraq** [comment]
and just another thought...where are the trade messages supposed to be restricted to? "Only show messages containing" should preclude every trade message, shouldn't it? So either the panel in the top right, or the trade chat in the bottom left, should have fewer messages than all messages, but they both have the same messages, so nothing is being stopped from displaying.

**Comment by reduf** [comment]
The "Only show messagse containing" is only for messages in the "darker pink" channel (i.e. the alerts).
It won't change the default trade channle behaviors.

The idea behind alerts, is to be able to track certain items while doing something else. Vanquishing a zone for instance.
This is also the reason why there is no messages when you are in ad1.

The only problem I saw in your first screen is that all messages where print even though you had "only show messages containing". Can you confirm that *when* it is activated, it doesn't print anymore messages not containings the keywords ?

**Comment by NTBugtraq** [comment]
So the alerts only work when outside of AED1. If that's the case, I haven't tried using this outside of Kammy. I will give that a try.
