### ISSUE TITLE
GWToolbox.dll was not loaded, unknown error

### ISSUE THREAD

**Issue by Bu11etmagnet** [HasKha/GWToolboxpp#195]
Trying to launch GWtoolbox (2.10) with either GWToolbox.exe (2016) or GWToolbox.exe (2018) results in a message box:
```
---------------------------
GWToolbox++
---------------------------
Error: GWToolbox.dll was not loaded, unknown error
---------------------------
OK   
---------------------------
```

**Comment by reduf** [comment]
Check:
https://haskha.github.io/GWToolboxpp/faq under `Issues launching GWToolbox`

**Comment by Bu11etmagnet** [comment]
The exact same computer with the exact same OS was working with toolbox 2.6 until the recent patches. I didn't change DEP, I didn't change my antivirus. How can I figure out what to do?

**Comment by HasKha** [comment]
make sure the dll is about ~3.2mb in size. If it's not, download that again and update your launcher (the gwtoolbox.exe)

**Comment by Bu11etmagnet** [comment]
GWToolbox.dll is 3.19 MB (3,348,480 bytes)
