### ISSUE TITLE
tb 2.11 early beta

### ISSUE THREAD

**Issue by HasKha** [HasKha/GWToolboxpp#196]
Uploading 2.11 beta 1 due to requests. 

Contains a few extra stuff, most notably hero id fix (#186) and custom minimap agents (#184).

**As with all betas, keep in mind this is untested and may crash your game at any time**

Please use this thread for feedback and bug reports. 

Once 2.11 is out, this beta *should* update to it, but it also might not, so make sure to periodically check for updates. 

[ToolboxBeta.zip](https://github.com/HasKha/GWToolboxpp/files/1888362/ToolboxBeta.zip)

**Comment by Hour-of-the-Owl** [comment]
when I click "Move Up" or "Move Down", it does move it up/down, but it then minimizes that tab and opens the one below/above it
when you mouse over "Move Up", "Move Down", and "Delete", it refers to the agent as a color... same with "Add Agent Custom Color" - should just be called "agent" or "custom agent"

**Comment by HasKha** [comment]
typo on Tea**r** shape

**Comment by HasKha** [comment]
bug: dead colored mobs stay colored, should take normal dead color instead

**Comment by Hour-of-the-Owl** [comment]
it is not possible to customize an agent without specifying a colour, which is a problem for agents that change affiliation e.g. charmable animals

**Comment by HasKha** [comment]
fixed everything in the thread in https://github.com/HasKha/GWToolboxpp/commit/71def1bbe31fb1e9e3bc6eca8cf45ed2e344381d
