### ISSUE TITLE
Filter for The Nine Rings not working

### ISSUE THREAD

**Issue by sebsu** [HasKha/GWToolboxpp#203]
![gw192](https://user-images.githubusercontent.com/1716091/39137762-a9b9a1f6-471e-11e8-963a-c261128bdc89.jpg)

**Comment by reduf** [comment]
Indeed, there was a bug with ChatFilter in the 2.10.
If you want there is a 2.11 beta [here](https://github.com/HasKha/GWToolboxpp/issues/196) that fix this issue.
