### ISSUE TITLE
Have Chat Filter effect Trade Alerts

### ISSUE THREAD

**Issue by KasparLinnaius** [HasKha/GWToolboxpp#207]
Possible? Would be nice to block the gold seller posts.

**Comment by reduf** [comment]
We directly piggyback on https://kamadan.decltype.org/ and they generally ignore the new spelling really fast. Would still be possible, but I don't think it's really usefull otherwise.

**Comment by reduf** [comment]
Not relevant anymore and https://kamadan.decltype.org/ already does a good job filtering messages.
