### ISSUE TITLE
AutoIt launcher does not respect user client selection - injects default client instead

### ISSUE THREAD

**Issue by Bu11etmagnet** [HasKha/GWToolboxpp#212]
1. Start two instances of Guild Wars
2. Start GW Toolbox++. The account selection dialog comes up with the active character of the GuildWars window in the foreground already selected. Click "Launch".
3. GW Toolbox++ hooks itself into the foreground GuildWars instance.
4. Start GW Toolbox++ again. The account selection dialog comes up with the active character of the GuildWars window in the foreground already selected. Select the character from the background GuildWars window. Click "Launch".
5. An error message box comes up: 
```
---------------------------
GWToolbox++
---------------------------
Error: GWToolbox++ already in specified process
---------------------------
OK   
---------------------------
```
It appears that GWToolbox++ ignores the selection and always tries to hook itself into the foreground GuildWars window. This can be used as a workaround: always put the GuildWars window you want to use Toolbox with into the foreground.

This is with the 2.14 release.

**Comment by HasKha** [comment]
Thanks for the detailed report. Probably a bug in the launcher introduced in the recent rework.

**Comment by reduf** [comment]
Are your 2 instances of Guild Wars started from the same executable / same .dat ?

**Comment by HasKha** [comment]
Note: the launcher is fixed, but you will have to manually re-download it from the website.
