### ISSUE TITLE
Minimap not hidden when taking a screenshot via Shift + PrintScreen

### ISSUE THREAD

**Issue by davidlukerice** [HasKha/GWToolboxpp#214]
Was just wondering if this could be fixed? Whenever you Shift+PrintScreen all of the game UI is hidden, but the GWToolbox++ Minimap is still visible on the screenshot.

**Comment by reduf** [comment]
Will definitly do, maybe ctrl+shift+h (or whatever shortcuts is used by the player) should hide toolbox as well.

**Comment by reduf** [comment]
Fixed in fa17b7f.

**Comment by kazerniel** [comment]
This seems to have been broken at some point between 28 April and 2 May 2021 (based on my screenshots).

Over the last 2 months the TB UI have been showing up for me while Ctrl+Shift+H is toggled.
