### ISSUE TITLE
Toolbox crashing when trying to update

### ISSUE THREAD

**Issue by raynorrr** [HasKha/GWToolboxpp#216]
Recently installed toolbox on a new pc, everytime I try to load it it seems to crash with no real error warning. Only bit I can take is it seems to be stuck trying to update but cant. 

![image](https://user-images.githubusercontent.com/19205215/40798312-9f29c1a6-6502-11e8-8c5e-293c7b0c8a01.png)

Took a screenshot of the recurring error

**Comment by reduf** [comment]
Hey, try the proposition in the [faq](https://haskha.github.io/GWToolboxpp/faq) under "I run the launcher and I get the message “GWToolbox.dll was not loaded, unknown error” or “exit code 0"

**Comment by raynorrr** [comment]
Already tried the mentioned error fixes, after installing the direct X it went from that error to this one.

**Comment by reduf** [comment]
Ok, I think it's the same error as an other guy. Does it crash Guild Wars ? If yes, you can try disabling AV the first time you start toolbox, then hopefully it will be fine.

**Comment by raynorrr** [comment]
no guild wars stays open, simply crashes the toolbox. If i try to reload toolbox on the same guildwars client get an error stating that its already in the specified process.

**Comment by reduf** [comment]
if you go in the GWToolbox directory `%localappdata%/GWToolboxpp/`, do you have any folders ?
You will definitly have a GWToolboxpp.dll, but do you have any other ?

**Comment by raynorrr** [comment]
![image](https://user-images.githubusercontent.com/19205215/40891040-1f361f4a-6777-11e8-9074-213bf5260066.png)

**Comment by reduf** [comment]
Do you mind uploading the content of "log.txt" and "launcher_log.txt" ?
You can send it in private through discord if you want.

**Comment by reduf** [comment]
Do you still have to problem after the last update ?

**Comment by reduf** [comment]
Since we got no more answer I'll close the issue.
You are free to come to discord to get more help, but it's likely an AV that's doing odd stuff. Make sure to use the most recent launcher as well.
