### ISSUE TITLE
Minimap Enhancements

### ISSUE THREAD

**Issue by HasKha** [HasKha/GWToolboxpp#23]
Originally reported by: **Giorgio Gori (Bitbucket: [ggori](https://bitbucket.org/ggori), GitHub: Unknown)**

---

Improve minimap:
- map portals, hero flags, res shrines
- (maybe) soh/sw/recall line

---
- Bitbucket: https://bitbucket.org/ggori/gwtoolbox-plusplus/issue/28

**Comment by HasKha** [comment]
implemented soh/sw/recall line in the new branch, will be part of next release

**Comment by HasKha** [comment]
implemented hero flags

**Comment by DarkManic** [comment]
Add the ability to be able to place the toolbox minimap hero flags in the 3d world.

**Comment by HasKha** [comment]
closing and opening a new one to clean up. Also moved hero flag stuff into #61
