### ISSUE TITLE
Submodule GWCA @ ... not found.

### ISSUE THREAD

**Issue by iaankrynauw** [HasKha/GWToolboxpp#232]
`fatal: repository 'https://github.com/GregLando113/GWCA.git/' not found                                                 fatal: clone of 'https://github.com/GregLando113/GWCA.git' into submodule path '../GWToolboxpp/Dependencies/GWCA' failed `

This submodule returns 404.

**Comment by HasKha** [comment]
That's expected. Please read the repository readme. I just updated it to make it more clear.
