### ISSUE TITLE
Comunication between toolbox users/instances

### ISSUE THREAD

**Issue by PhilohGW** [HasKha/GWToolboxpp#233]
Would it be a idea to use a comunication between toolbox users/instances to sent special Textes into chat and suppress them from toolbox by default? 
like i gues it was a thing to print times of single quests in DoA, but not doable because u dont get a update of the quest, if u do not accept it by yourselfe. But the player who accept the quest could sent a Chat message (e.g. TB-DoA-Foundry-Quest1) and every toolbox can time quest with it, and suppress the chat message so u dont get spammed. Non Toolbox users will get spammed but they are not wurth living at all tho..

**Comment by HasKha** [comment]
I don't like it for two reasons:
1. Toolbox users would get spammed and they *are* worth thinking about. Note also that they would get spammed by each user in the party. It will get annoying, and we don't want to affect non-tb users.
2. It could easily be abused by both tb users and non-tb users, who could manually send the messages.
