### ISSUE TITLE
Hero flag formations.

### ISSUE THREAD

**Issue by iaankrynauw** [HasKha/GWToolboxpp#239]
Spec:
- Add another button row container.
- Keep all flagging buttons consistent. (styling, double-click cancel, hover etc)
- Be able to easily add new formations. (Within code and not persisted in a file)
- Validate that heroes are placed in a valid pathing map.

First attempt will implement. 
HA style Circle
`x^2 + y^2 = r^2`
Upside down V:
`y =  -|-x| + k`
 GvG style line formations.
`y = k+a` where ` x = -2,+2`
`y = k` where ` x = -1, +1`
`y = k-a` where ` x = -3, 0, +3`

(The math is just me thinking out loud)

**Comment by HasKha** [comment]
sounds good, linking to #61 for reference

**Comment by quetzalsly** [comment]
This would be an amazing feature for running DoA HM with 7 heroes. It's really tedious to keep manually splitting. The best solution would be a simple keybind, where gwtoolbox monitors for a keypress like numpad0 or something and the heroes split when you press it.

**Comment by iaankrynauw** [comment]
Got quite close had a prototype up, but I never deployed the code. Wasn't sure if it was clean enough and tested.

I'll find it and see if I can extract some for someone else to pickup.

**Comment by HiImFlo** [comment]
Since I assume the hero team should have some sort of reference point it should be oriented towards, I think this should be
a) the current target
b) the closest hostile unit if there is no current target

**Comment by 3vcloud** [comment]
Flagging interrupts actions so some thought needs to be put behind how to identify when you're in combat, and what to do in that situation

**Comment by iaankrynauw** [comment]
My original idea was simply to have a button such as hero flag 1. In which you click on the map and a random formation is formed around where you clicked. That could be `circle` or 2 - 3 - 2 `line` etc.

**Comment by quetzalsly** [comment]
Just a random thought, but the ST hero should be behind everyone I think? he is the one that the whole team depends on to live.

**Comment by FrankGriffioen** [comment]
Basicly just had the same idea, it would be great to add a button that places all hero's in a formation (by placing multiple flags at once), Optionally the formation should be able to be edited through a menu option, to suit your preferred team setup. (xy coorditnates in relation to the formation flag your placing?)

**Comment by bquenin** [comment]
It looks like there's a couple commits regarding this issue, does it mean it's available already?

**Comment by 3vcloud** [comment]
Added in 4.1
