### ISSUE TITLE
Fix bugs with cam unlock

### ISSUE THREAD

**Issue by HasKha** [HasKha/GWToolboxpp#24]
Originally reported by: **Giorgio Gori (Bitbucket: [ggori](https://bitbucket.org/ggori), GitHub: Unknown)**

---

two known bugs: impossible to type /cam lock while unlocked, cam being fixed while characters moves (https://www.youtube.com/watch?v=6LEiSkEk3Eo)

---
- Bitbucket: https://bitbucket.org/ggori/gwtoolbox-plusplus/issue/29

**Comment by HasKha** [comment]
note about the typing bug: the IsTyping function is broken and always returns false. Update may have broken the address.
`bool IsTyping() { return (*(DWORD*)0xA377C8) != 0; } // broken`

**Comment by reduf** [comment]
Is there still the bug with the camera not reseting on the character ?
If yes, it's one memory patch that is not reversed.

About the IsTyping, there is two DWORD that are mirror to each other, 0xA377C8, 0xA37890.
So it is strange that IsTyping doesn't work.

**Comment by HasKha** [comment]
should be fixed
