### ISSUE TITLE
re-direct whispers to the correct character

### ISSUE THREAD

**Issue by Hour-of-the-Owl** [HasKha/GWToolboxpp#240]
When I PM someone and they appear offline, I pretty much always do this:
1. add them to friend list
2. if they're on a different name, get that name
3. PM the original message to that name
4. if they were not already in FL, delete from FL
TB could and should automate this! Since the FL was doubled in size, everybody probably has at least one space free.

It would also be cool if the trade chat window did this - when you click on the buyer/seller's name to PM them:
1. add them to friend list
2. if they're offline, display "Player ___ is not currently online." so we don't waste time typing out a message to them
3. if they're online, get the name they're online as
4. use that name to PM them
5. if they were not already in FL, delete from FL

**Comment by reduf** [comment]
It was already discussed on the discord, but for documentation here are the problems about this feature.

1. Let's say you have a friend added with the name `name1` to your friends list and you talk to him when he is on character `name2`. If he changes character to `name3` you will need to add `name2` to understand where to send the message. For this reason, you need to add the player before every messages which add a delay of approximately 2 * your ping.

2. When someone is not in your friends list, it is obvious that you need to add him everytime before sending a message which add a delay of approximately 2 * your ping.

3. We could add a internal state, but it would be a bit broken for non-friend players and woudn't work that well if you message `name2` before you saw him going on the character `name2`.

Overall, it would be very clunky and it would have a delay to every messages sent. That's a feature that should be implemented server-side. (i.e. by ANet devs)

**Comment by Hour-of-the-Owl** [comment]
That delay would only apply when the person is offline, right? Otherwise there's nothing to just stop the message from going through normally. This may be less than ideal, but it's still a lot better than having to add people manually.

Unless it's way too much work for you to implement, or there are some actual disadvantages to having this in TB, I don't think it's a great idea to wait for the devs to do it... even if they said "we will definitely do this", there's no guarantee it'll happen any time this year.

**Comment by Hour-of-the-Owl** [comment]
Assuming this is not going to happen, can we please have a button on the trade window to add the buyer/seller to FL? A little `+` to the left of their name would do the job.
