### ISSUE TITLE
movement macros don't work while auto-running

### ISSUE THREAD

**Issue by Hour-of-the-Owl** [HasKha/GWToolboxpp#245]
If you're auto-running and you activate a movement macro (via hotkey or minimap or whatever), it simply turns you to face towards the destination and continue auto-running in that direction. Clicking on the ground to move does NOT have this issue - it cancels your auto-run and just paths you to the destination.

**Comment by reduf** [comment]
I tried and it seems to be fix, if you have the bug you can re-open the issue and contact me so we can debug it.

**Comment by Hour-of-the-Owl** [comment]
I only just noticed you closed this. The bug has not gone away.

**Comment by reduf** [comment]
Hum ok, then I don't understand what is the bug.

**Comment by 3vcloud** [comment]
Fixed in dev https://github.com/HasKha/GWToolboxpp/commits/e63bf290c4ea3933baf22aba6b88bb873ccb1c89

**Comment by Hour-of-the-Owl** [comment]
This is still broken. Please stop closing the issue without fixing it!

**Comment by PostCrafter** [comment]
Works for me

**Comment by Hour-of-the-Owl** [comment]
okay just kidding it is actually working now - I didn't realise it had been fixed some time between 4.0 and 4.2
