### ISSUE TITLE
click-to-move on minimap false positive

### ISSUE THREAD

**Issue by Hour-of-the-Owl** [HasKha/GWToolboxpp#246]
some of the time when I press `Alt`, TB seems to think I'm still holding it down until I press it again, so when I try to ping or flag heroes, it doesn't work and makes me move (and does not ping or flag the heroes)... note that the game does not think I'm still holding `Alt` (it doesn't display all ally names)

**Comment by Hour-of-the-Owl** [comment]
k I think I worked out what causes this, or at least managed to reliably reproduce it: `Alt`+`Tab`

**Comment by HasKha** [comment]
probably gw doesn't receive the alt-up key event when alt-tabbing. Agree we should fix this.

**Comment by HasKha** [comment]
Fixed in https://github.com/HasKha/GWToolboxpp/commit/4f3ebc7ab45e6601469f144739b3d56f5a4c2f83
