### ISSUE TITLE
custom dialogs

### ISSUE THREAD

**Issue by Hour-of-the-Owl** [HasKha/GWToolboxpp#248]
Make it possible to add them as favourites? Or add stuff like "enter Factions mission outpost" and "enter Nightfall mission outpost" to the dropdown menu?

also why is it in Dec by default? Doesn't everyone use Hex???

**Comment by reduf** [comment]
Do you know if all "enter Factions mission outpost" and "enter Nightfall mission outpost" are the same?

If yes, I believe it's 0x8000B for Faction. What is it for Nightfall?

**Comment by BearsMan** [comment]
Nightfall is 0x85
