### ISSUE TITLE
suppress useless red messages in the middle of the screen

### ISSUE THREAD

**Issue by Hour-of-the-Owl** [HasKha/GWToolboxpp#249]
Lots of annoying crap appears in the middle of my screen and I have no way to turn it off, e.g.

- "Target is immune to [condition] (no flesh)"
- "This item cannot be used in towns or outposts."
- "You cannot use this item when no party members are dead."

...among others. Even if the message is something I care about, I don't want it in red in the middle of the screen. All of the red messages should be suppressed, and the handful of useful ones should be printed in chat.

**Comment by 3vcloud** [comment]
Included in merge 2020-05-02
