### ISSUE TITLE
Could not find Guild Wars process

### ISSUE THREAD

**Issue by Itsindigo** [HasKha/GWToolboxpp#251]
I'm running GW via Wine on MacOS, and trying to run GWToolbox too.

I'm currently stuck with this error:

```
remoteversion: 2.18
Displaying changelog.
format: . error: 0. extended: 0
do_update: False
One copy of GW detected. PID: 8
Error: Cannot find Guild Wars process
Flushing log, bye!
006a:fixme:win:LockWindowUpdate (0x0), partial stub!
```

Completely inexperienced with this software stack, so any help debugging would be greatly appreciated!

**Comment by reduf** [comment]
We don't support mac os, but you can find more informations [here](https://www.reddit.com/r/GuildWars/comments/87vyin/guide_to_get_gw_gwtoolbox_and_texmod_on_a_mac/)
