### ISSUE TITLE
LB title hotkey for other titles

### ISSUE THREAD

**Issue by Hour-of-the-Owl** [HasKha/GWToolboxpp#252]
Make the `reapply Lightbringer title` hotkey do the EotN titles instead, when you're in the appropriate areas.

I'll grab all the relevant map IDs when I get time:

Asura:
Rata Sum 640
Tarnished Haven 641
Vlox's Falls 624
Gadd's Encampment 638
Umbral Grotto 639
Magus Stones 569
Riven Earth 501
Arbor Bay 485
Alcazia Tangle 572
Sparkfly Swamp 558
Verdant Cascades 566

Deldrimor:
Glint's Challenge: 37
Central Transfer Chamber 652
GOLEM 664
A Gate Too Far level 1 655
A Gate Too Far level 2 656
A Gate Too Far level 3 657
Destruction's Depths level 1 670
Destruction's Depths level 2 671
Destruction's Depths level 3 672
A Time for Heroes 673
Raven's Point level 1 617
Raven's Point level 2 618
Raven's Point level 3 619

Norn:
Boreal Station 675
Eye of the North 642
Gunnar's Hold 644
Sifhalla 643
Olafstead 645
Ice Cliff Chasms 499
Norrhart Domains 548
Drakkar Lake 513
Jaga Moraine 546
Bjora Marches 482
Varajar Fells 553
Curse of the Nornbear 653
Blood Washes Blood 654
Mano a Norn-o
Service: In Defense of the Eye
Cold as Ice
Bear Club for Women/Men

Vanguard:
Doomlore Shrine 648
Longeye's Ledge 650
Grothmar Wardowns 649
Dalada Uplands 647
Sacnoth Valley 651
Against the Charr 665
Warband of Brothers level 1 666
Warband of Brothers level 2 667
Warband of Brothers level 3 668
Assault on the Stronghold 669
Cathedral of Flames level 1 560
Cathedral of Flames level 2 567
Rragar's Menagerie level 1 573
Rragar's Menagerie level 2 574
Rragar's Menagerie level 3 575
What Must Be Done (training montage) 674
Ascalon City 81
Great Northern Wall 28
Fort Ranik 29
Ruins of Surmia 30
Nolani Academy 32
Frontier Gate 135
Grendich Courthouse 36
Sardelac Sanitarium 39
Piken Square 40
Old Ascalon 33
Regent Valley 101
The Breach 102
Diessa Lowlands 13
Flame Temple Corridor 106
Dragon's Gullet 105

Lightbringer:
everywhere else..? if you REALLY want, I can find the IDs for every single map where there might be demonic servants of Abaddon, but IMO every map has the potential for you to suddenly decide you want to DoA

**Comment by Hour-of-the-Owl** [comment]
Okay I've found all the ones that really matter. I will get the instanced quests eventually, but I don't think they are at all necessary to put this in.

By the way, this should be labelled as an enhancement, not a feature request =P

**Comment by reduf** [comment]
It should be marked at "wontdo" :)

**Comment by HasKha** [comment]
nah, just do a switch on the mapid. Regions aren't good enough, and we have the ids already above (thanks owls!)

**Comment by Hour-of-the-Owl** [comment]
looks like the Wintersday version of Eye of the North is a different map ID: 821
meanwhile Ascalon City is 881

**Comment by Hour-of-the-Owl** [comment]
Wintersday EotN still doesn't apply the Norn title, but the ID has not changed from 821

**Comment by Hour-of-the-Owl** [comment]
Special Ops: Dragon's Gullet 728
