### ISSUE TITLE
Travel button to Urgoz/Deep, was hoping to not buy/waste scrolls

### ISSUE THREAD

**Issue by BearsMan** [HasKha/GWToolboxpp#253]
maybe there is a fix to this issue, since TB v2.18 update the travel to Urgoz/Deep worked fine until the new gw update so maybe there is a way to fix it no I mean its worth a shot, since it was a bug before hand (which I didn't know) maybe it can still be fixed. Its just those 2 areas

**Comment by BearsMan** [comment]
![gw035](https://user-images.githubusercontent.com/34116754/44263372-b7096480-a1ec-11e8-8666-f05ef4fa62d1.jpg)
tried the buttons for deep/urgoz no go

**Comment by reduf** [comment]
We will remove the button, but we can't "fix" that anymore.
