### ISSUE TITLE
ice/fire/poison jet timer

### ISSUE THREAD

**Issue by Hour-of-the-Owl** [HasKha/GWToolboxpp#254]
All the jets in dungeons are on a 20s timer: 10s off and then 10s on, starting at the creation of the instance. It should be supereasy to make a timer just like the Urgoz one... do you want the map IDs?

**Comment by Hour-of-the-Owl** [comment]
The ones in Nightfall are on a very similar timer, but it's not exactly the same so I'm not sure if it would just be misleading to include them.

**Comment by Hour-of-the-Owl** [comment]
fire jets:
Catacombs of Kathandrax level 1
Catacombs of Kathandrax level 3
Cathedral of Flames level 3
Bloodstone Caves level 1
Shards of Orr level 3
Oola's Lab level 2
Arachni's Haunt level 2

ice jets:
Sepulchre of Dragrimmar level 1
Raven's Point level 1
Raven's Point level 2
Heart of the Shiverpeaks level 1

poison jets:
Cathedral of Flames level 2
Bogroot Growths level 1
Bloodstone Caves level 3
Shards of Orr level 1
Shards of Orr level 2

fire spouts:
Shards of Orr level 3
Cathedral of Flames level 3
Heart of the Shiverpeaks level 3

ice spouts:
Darkrime Delves level 1
Secret Lair of the Snowmen

poison spouts:
Cathedral of Flames level 2
Bloodstone Caves level 2
Bloodstone Caves level 3

**Comment by HasKha** [comment]
note: this is indeed quite easy, add another function like the urgoz timer here https://github.com/HasKha/GWToolboxpp/blob/master/GWToolbox/GWToolbox/Widgets/TimerWidget.cpp#L75
