### ISSUE TITLE
corpses of masterless minions appear as enemies on the minimap

### ISSUE THREAD

**Issue by Hour-of-the-Owl** [HasKha/GWToolboxpp#256]
This is extremely distracting when they're supposed to be dead!

**Comment by Hour-of-the-Owl** [comment]
pretty sure this is a bug, not an enhancement =P

**Comment by reduf** [comment]
masterless minions aren't dead though, right ?

**Comment by GregLando113** [comment]
theyre dead to me

**Comment by Hour-of-the-Owl** [comment]
they still show up as red AFTER THEY DIE - that's the problem

**Comment by HasKha** [comment]
truly undead.

**Comment by HasKha** [comment]
both me and @Hour-of-the-Owl were unable to reproduce. Closing.
