### ISSUE TITLE
Improve the hide-server-chat function

### ISSUE THREAD

**Issue by HasKha** [HasKha/GWToolboxpp#26]
- Also hide pvp faction gains "you have gained x balth, visit a priest for reward!"
- Do not hide when players drop or pickup certain items (everlasting tonics for example)

**Comment by DarkManic** [comment]
add a filter for `you have played x hours` and `titles gained`

**Comment by DarkManic** [comment]
add filters for:
You picked up x
You droped x
Quest added
Quest updated
Quest finished
You gained x exp
You recived x platinum
You shared x gold
Goal completed. Press "L" ...
District is full
Contdown reset (PvP)

**Comment by Hour-of-the-Owl** [comment]
Is it possible to CHANGE a message? e.g. if I ping the monk lord have it say "I'm targeting Stygian Lord (monk)!"? Perhaps delete the original message and send the improved one to party chat?
Off the top of my head I can't think of any other immensely useful examples, but saying which lord you're pinging would be an improvement.

**Comment by HasKha** [comment]
It's possible to change a message, but what you're asking is much more difficult, because toolbox can see a message but it doesn't know what generated it, so it would have to remove your message entirely, figure out the targeted lord and print that instead.

**Comment by Hour-of-the-Owl** [comment]
#179
