### ISSUE TITLE
Bond Monitor messed up

### ISSUE THREAD

**Issue by BearsMan** [HasKha/GWToolboxpp#267]
at least all players can get bonds except for 1 person unless stone is dead (example: DoA as IAU
![gw001](https://user-images.githubusercontent.com/34116754/46508003-751e9700-c809-11e8-8cc1-57227ec21efe.jpg)

this image shows some bonds are registered but when I bonded IAU on this run it did not register unless stone died: example 6-0 tendrils

**Comment by reduf** [comment]
Thanks, fixed for next release.
