### ISSUE TITLE
GWToolbox offers to download new version on every single launch even though it's already that version

### ISSUE THREAD

**Issue by kazerniel** [HasKha/GWToolboxpp#268]
Iirc the issue started in 2.18, and is still present in 2.19.

**Comment by reduf** [comment]
Do you close GWToolbox before closing Guild Wars or just close Guild Wars.
If it's the case, close GWToolbox once before closing Guild Wars.

For some reason, GWToolbox may not have a "clean close" when Guild Wars is closed and it won't save his version in the configuration file.

**Comment by kazerniel** [comment]
Thank you, this fixed it :) (Also seems to have fixed an earlier issue where it didn't save window collapse and position upon exit.)
