### ISSUE TITLE
pinging weapons/armour

### ISSUE THREAD

**Issue by Hour-of-the-Owl** [HasKha/GWToolboxpp#270]
when you 'Alt'+click (or whatever) on a weapon or armour in your inventory/storage/on you, TB should get the following information and EITHER put it in the active chat channel without sending the message (if you are currently writing a message) OR send it directly to party chat (if you are not):
req (including abbreviated attribute if it's a staff, wand, focus, or shield)
damage iff it's less than max
skin
abbreviated prefix
abbreviated suffix
abbreviated inscription

armour pieces would state the skin, attribute if it's a headpiece, insignia, rune, and AL if it's less than max

Maybe people also want to know what colour it's dyed???

**Comment by 3vcloud** [comment]
I think this is good except for putting it into the chat text box before sending. Might be able to hijack the `I'm wielding a burning sweaty sausage wand of procrastination slaying` StoC package to allow you to ping the weapon/armor in the receiver's language, but that wouldn't work as well if you're putting it into the input section on your own client before sending.

**Comment by 3vcloud** [comment]
Included in merge 2020-05-02
