### ISSUE TITLE
Default Titles

### ISSUE THREAD

**Issue by NG-GW** [HasKha/GWToolboxpp#271]
I saw the new titles feature and its very good.
I have an idead that will make it better (in my point of view).

Make an option to choose to each character a default title (by character name).
On load to outpost it will set the title to my character default,
and the "area title" will change when we load the explorable area.

Thanks for the great work!!

**Comment by HiImFlo** [comment]
+1, UW players need to show off their titles in embark

**Comment by HasKha** [comment]
Two notes:
1. it is quite a bit of UI work for a feature that arguably adds very little to gameplay. Still, it's possible.
2. I would not automatically set on rezone, and still require the player to hit the hotkey. We previously decided against the automatic re-application of lb title when bonded, casting sf, etc, and while this is not as bad, I'd still prefer to avoid automatic actions.

**Comment by 3vcloud** [comment]
This can be achieved by assigning a hotkey by profession to trigger on map load

**Comment by NG-Guildwars** [comment]
But there is no option to choose a specific title? (e.g. Zaishen, Kurz etc.)

**Comment by 3vcloud** [comment]
Right you are, thought this was in already - will add a second argument to this
