### ISSUE TITLE
chat filter - regular expression validation

### ISSUE THREAD

**Issue by Azzurvif** [HasKha/GWToolboxpp#273]
Currently you get tons of error messages when typing a regex, which flood the chat. You must erase/rewrite your expression to be sure that it's good.
A save button and a validation message would be just fine instead of an automatic check

**Comment by reduf** [comment]
Will look into that.

Note that if you are using regex for ignoring accent you don't need to do that anymore.
We now normalize the string so messages like `PàlAdîn` and `paladin` will match.
Works like "ctrl-f" works on web browsers.

**Comment by Azzurvif** [comment]
Nice thanks, that's a good thing to know 
Gold sellers still use the 0 instead of O, so I will keep my regex for some cases ☠️

**Comment by reduf** [comment]
I wasn't sure about normalizing numbers, it might be usefull (i.e. `0` to `o`, `3` to `e`), but my thought is that generally there wasn't enough combination to be annoying.

I just had both.

**Comment by reduf** [comment]
That's not what we do right now and if we were to do `3` -> `e` we would also do the other (`4`, `1`, `5`, ...)

I didn't think that it was very good when I implemented it and wanted to do something that would be familiar to the users. So it works like ctrl-f in Chrome/Firefox.

**Comment by reduf** [comment]
I've added a noise reduction constant that delay the parsing of both buffer since we can't catch the event when the focus is lost.
