### ISSUE TITLE
Pcons window: Visibility of Enabled/Disabled button is not remembered

### ISSUE THREAD

**Issue by necropola** [HasKha/GWToolboxpp#275]
I disabled the button, typed "/tb exit" to save the settings, relaunched GWToolbox and the button reappeared. Also it's a bit unclear whether visibility should only affect the button in the pcons window or also the button in the TB main menu (it does not, which is good).

**Comment by Azzurvif** [comment]
Did it just happened once ?

I had this issue for the button and other settings in TB. I think it's a general bug of saving.
Did you update TB during the same game session ? 
My settings have not been saved twice in the last few week, it seems hard to reproduce but I am 90% sure that I had a TB update just before.

**Comment by necropola** [comment]
I tried disabling the button. then /tb exit and then relaunch a few times and it was never saved. The consumables I have disabled (set to invisible) in the window were successfully saved, though.

**Comment by reduf** [comment]
Thanks, will be fix for the next update.

**Comment by HasKha** [comment]
Thanks for the catch and analysis. I am amazed noone noticed this before. Maybe I'll do a general pass checking all the ini Set/Get to make sure there aren't any others.
