### ISSUE TITLE
Recent Damage Timeout is not remembered

### ISSUE THREAD

**Issue by necropola** [HasKha/GWToolboxpp#276]
A change of this setting is not written to the `.ini` but is loaded correctly , if I edit the `.ini` (`recent_max_time=...` in section `[Damage]`) manually and then relaunch GWToolbox.

I found `ini->GetLongValue(Name(), VAR_NAME(recent_max_time), recent_max_time)` in `PartyDamage::SaveSettings(CSimpleIni* ini)` where it probably should be `ini->SetLongValue(Name(), VAR_NAME(recent_max_time), recent_max_time)`

https://github.com/HasKha/GWToolboxpp/blob/3fa077d3554b6a2b6895c33e112ea1dbad945f10/GWToolbox/GWToolbox/Widgets/PartyDamage.cpp#L380

**Comment by reduf** [comment]
Thanks, will be fix for the next update.

**Comment by HasKha** [comment]
Good catch, my bad.
