### ISSUE TITLE
Reroll functionality

### ISSUE THREAD

**Issue by PostCrafter** [HasKha/GWToolboxpp#282]
Similar to #132 a reroll functionality would be nice to have.
This would include:
- Changing to a different character - either by profession or name (for those with multiple characters of the same profession)
- Traveling to the outpost and district of the previous character
- Inviting yourself into your previous party (send invite to the previous party leader?)
- _optional:_ load a specific skill template

I'd suggest implementing this either as a separate window and/or adding it to the existing builds window.

I haven't checked yet whether GWCA implements any functionality for character select, so this might not be possible with the current prerequisites.

**Comment by reduf** [comment]
This is very unlikely to happens, because there would be too many failure cases to handle and there is a lot to implement. Moreover, I think that it bring so little to game.

**Comment by reduf** [comment]
No need to keep this issue as it won't be done.
