### ISSUE TITLE
Flagging hero crash the toolbox

### ISSUE THREAD

**Issue by reduf** [HasKha/GWToolboxpp#284]
From discord,

> Sometimes when i either flag a hero through tb minimap or having shift or ctrl, tb closes my client down.

**Comment by 3vcloud** [comment]
I fixed a few bugs with this - if the map type changed to outpost or loading and the player flagged on the map (e.g. clicked the flag button before map change when the buttons were available) it would crash the client. The merge with flag heros shortcut has put my fix for this in.

**Comment by reduf** [comment]
I wasn't able to reproduce. Does that happend every time for you ?

**Comment by reduf** [comment]
Was patched in #299.
