### ISSUE TITLE
Send Item to Chat

### ISSUE THREAD

**Issue by kyleshrader** [HasKha/GWToolboxpp#287]
Is it possible to add a shortcut to <modifier(s)>+mouse0 to send an item name and quantity to the input field for chat?

**Comment by kyleshrader** [comment]
If someone could provide a link to the xunlai chest ctrl+mouse0 code, i could try to put a PR together for this and #230

**Comment by kyleshrader** [comment]
another similar idea would be to perform /wiki <Item::singularName> on some modifier click

**Comment by kyleshrader** [comment]
I imagine the following meta key usages:
Ctrl => Move item to/from storage or trade.
Alt => Send displayed name (quantity and plural name) to chat input.
Alt+Shift => Send an items full description to chat? This could be useful for sharing gear rolls?
Ctrl+Shift => Open Wiki

Any other comments or suggestions? Maybe we could set up a settings section for all these settings, maybe allowing for the user to change the default meta key combos and enable/disable some of these options?

**Comment by reduf** [comment]
Duplicate of #270
