### ISSUE TITLE
Kamadan ae1

### ISSUE THREAD

**Issue by Hour-of-the-Owl** [HasKha/GWToolboxpp#300]
change "Kamadan" in the Travel window to "Kamadan ae1" - pretty sure that's where people are going when they click the button

**Comment by HasKha** [comment]
The current functionality is to travel to Kamadan, using the district in the combo above, just like all other buttons. Are you suggesting to change this functionality, and force ae1 for Kamadan only?

**Comment by 3vcloud** [comment]
I only ever use /tp kama or /tp kamadan - we could just change that to default to ae1 and leave the window as is. I like how tidy the travel window is atm and it would cause a few headaches code-wise to do it that way

**Comment by reduf** [comment]
There is also a certain cost to consider when breaking the coherence within the same command.

**Comment by HasKha** [comment]
Another issue with forcing ae1 is that if the district is full then actually getting there is annoying. I would rather travel to ae2 than not travel at all.

**Comment by 3vcloud** [comment]
Well what about just ae? Doesn't the overflow only trigger if ae1 is full?

**Comment by reduf** [comment]
`/tp kama ae` or `/tp kama ae` :)

**Comment by 3vcloud** [comment]
Thats like saying that we don't need `/tp kama` because you could just type `/tp kamadan` - they're supposed to be shortcuts :(

**Comment by reduf** [comment]
I mostly agree except that in your example it doesn't add ambiguity to have `/tp kama` vs `/tp kamadan`.

**Comment by Hour-of-the-Owl** [comment]
Okay, forcing ae1 is indeed bad - change that to just ae.

I am requesting that the button name changes to `Kamadan ae` and it automatically sends you to American district. The only reason Kamadan is a default button is because people use it as a trading hub.

**Comment by reduf** [comment]
Not an issue anymore, since the update that increased the maximum amount of players in Kamadan. 
Might revisit if a lot of players starts playing Guild Wars again.
