### ISSUE TITLE
can't travel to Urgoz's

### ISSUE THREAD

**Issue by Akira2511** [HasKha/GWToolboxpp#304]
I can't travel to Urgoz's Warren. it doesnt matter where i want to start (Kamadan, Embark, Kaineng) 
and yes i may enter this outpost

**Comment by reduf** [comment]
https://github.com/HasKha/GWToolboxpp/releases/tag/2.19_Release

3rd before last point.

**Comment by Akira2511** [comment]
Hey.

sorry for wasting your time but i meant this function

best regards
lars

Am Mi., 20. Feb. 2019 um 16:01 Uhr schrieb Ziox <notifications@github.com>:
