### ISSUE TITLE
crash on health ping

### ISSUE THREAD

**Issue by Hour-of-the-Owl** [HasKha/GWToolboxpp#306]
Last night in Arachni's I pinged her health and the game immediately crashed. I've been using this feature a lot (including a minute earlier on the exact same target, but before I'd damage her) and this is the only time it's caused any problem.

**Comment by HasKha** [comment]
not sure about this, I took a look and the code seems ok. The possible failure point might be `GW::Agents:AsyncGetAgentName(..)` which we also use in a bunch of other places.

**Comment by reduf** [comment]
Was fix in a previous version, so closing the issue.
