### ISSUE TITLE
 PvP-Addons

### ISSUE THREAD

**Issue by HasKha** [HasKha/GWToolboxpp#31]
Originally reported by: **Anonymous** on BitBucket

---

First off sorry for my bad englisch.. Non native speaker writing on my phone which is correcting evrything to make it even worse.

Would it be possible to add Holy Vial or an Option for all bonds to the hotkeys Skills like UA and Recall?

Also reviving the "aggrometer" from the passed gen toolbox would be nice.

And lastly a enemie Party window with hp and clickable Name for targeting would be awsome, tho i think this could end up being a huge Performance Hit in pve.

**Comment by HasKha** [comment]
1. Adding Holy Veil to the bonds hotkey is definitely possible and good idea, will do.
2. Aggro monitor is definitely possible. It used to be a big performance issue in autoit, but with C++ this is no longer a problem. It's not an easy task though, and will require time.
3. About the Party Window, I'm tending to be against it, although I'm open to a discussion. Those are my arguments against it.
   * It provides an unfair advantage in a PvP environment.
   * It's a lot of work for a PvP-only feature. Toolbox would benefit more from other features.
   * Party windows have already been done, why can't those be used instead?

**Comment by Hour-of-the-Owl** [comment]
Surely aggro monitor is a MUCH bigger unfair advantage in PvP than the party window?

**Comment by HasKha** [comment]
True, and thanks for bringing this issue up.
1. Holy Veil has been added to the bonds hotkey and is now visible in bonds monitor
2. Aggro monitor has been replaced by mob count for pve (doa babyway was pretty much the only use-case of aggro monitor anyway), and as misty said, it's OP in pvp to pre-prot spikes
3. Not doing a party window for the reasons above.
