### ISSUE TITLE
automatically restore saved widget positions from ini file after full-screen/window-mode toggle

### ISSUE THREAD

**Issue by smiley232** [HasKha/GWToolboxpp#310]
1) be in full screen mode
2) toolbox widget is placed on the far right side of the GW window (does not matter if size or position is locked)
3) switch to windowed mode (i.e. half the X-resolution of full screen)
4) switch back to full screen mode

current behaviour:
5) the widget from (2) moved its position to the left

expected behaviour:
5) the widget from (2) is at the exact position it was before switching to windowed mode

my current workaround is to manually uncheck/hide the affected widgets before entering windowed mode but that is a pain in the ass.

it may be worthy of mention that this issue was introduced with toolbox version 2.3.

**Comment by BearsMan** [comment]
it was fixed from a dll patch that me and Livia fixed but if it happens again ill put a dll patch up for it if needed

**Comment by 3vcloud** [comment]
Fixed in 4.3; "Load Now" to load UI layout when toolbox last saved settings
