### ISSUE TITLE
Mission Completion and Title status info?

### ISSUE THREAD

**Issue by dfarley1** [HasKha/GWToolboxpp#311]
I recently started digging around in the GWToolbox and GWCA code to see if I could implement something like a panel that would show what missions a character has done for Protector/Guardian.  I'm not sure where I'm going with it but I wanted to see if I could implement some widget like #119 requested, automatically accept Ziashen quests that the character needed, TP to relevant outputs, stuff like that.

Anyways, I'm unable to find any context (GameContext, WorldContext, Titles) that show character mission progress that's already been found.  Do you guys have any hints or tips that I could explore?

**Comment by 3vcloud** [comment]
https://github.com/GregLando113/GWCA/blob/8a0e5a522e417dd3e7d39d97a4157d41dbc49f4a/Source/GWCA/Context/WorldContext.h#L74 might be a good idea to check whether a player has access to a map, and https://github.com/GregLando113/GWCA/blob/8a0e5a522e417dd3e7d39d97a4157d41dbc49f4a/Source/GWCA/Context/WorldContext.h#L61 might show you completed quests.

Thats where I'd start, but haven't really looked into those arrays.

**Comment by reduf** [comment]
You can look if you already found a map by using the following array.
https://github.com/GregLando113/GWCA/blob/master/Source/GWCA/Context/WorldContext.h#L74

e.g.
```cpp
bool GetIsMapUnlocked(uint32_t map_id)
{
    Array<uint32_t> unlocked_map = GameContext::instance()->world->unlocked_map;
    uint32_t index = map_id / 32;
    if (index >= unlocked_map.size())
        return false;
    uint32_t shift = map_id % 32;
    uint32_t flag = 1 << shift;
    return (unlocked_map[index] & flag) != 0;
}
```

**Comment by dfarley1** [comment]
Thanks so much for the leads guys, I noticed unlocked_map before but had no idea how to start deciphering it except trying to track it as I played the game and did some missions!  I'll check when I get home but I wonder if those values show the mission completion (masters, bonus, etc.) or Hard Mode.

**Comment by reduf** [comment]
Doing something similar as an example of how to use GWCA. If it get popular enough, might move to GWToolbox.
