### ISSUE TITLE
Global Alpha validation

### ISSUE THREAD

**Issue by 3vcloud** [HasKha/GWToolboxpp#319]
Global Alpha should be between 0.1 and 1.0 i.e. can't hide toolbox completely. People are accidentally setting this to either 0 or something silly like 5.

**Comment by reduf** [comment]
Which global alpha are you talking about ?

The drag bar under "Theme" is bounded between 0.2 and 1.0.

**Comment by 3vcloud** [comment]
I was a bit hasty to presume that this was the issue. Had someone get in touch saying they couldn't see their toolbox (or show it etc). Toolbox was running because it outputted instance time via `/age2` in-game.

Attached is a copy of their `Theme.ini` file - in my tests it seems to show an error message and give option to abort or ignore. I've asked for more info but it shouldn't be possible?

It might be worth re-retting the value anyway (e.g. 0.2 if < 0.0, 1.0 if > 1.0) by reference when doing the range check, instead of an assert with an error message. Its what I'm doing for a few settings on my side.
