### ISSUE TITLE
Minimap size

### ISSUE THREAD

**Issue by Waldenpond007** [HasKha/GWToolboxpp#32]
Have a problem with the mini map not zooming out. Is there a way to reset the mini map upon the program starting up?

**Comment by HasKha** [comment]
If you want to reset the minimap zoom go to settings -> open settings folder -> open GWToolbox.ini in a text editor (like notepad) and delete the line at the end with "scale = ..."

for controls for the minimap and more info check here: http://tools.fbgmguild.com/gwtoolbox/info/minimap/

**Comment by Waldenpond007** [comment]
Thank you. Have a great weekend.

**Comment by Waldenpond007** [comment]
I did not find the line "scale =". Any ideas?

**Comment by Waldenpond007** [comment]
This is the ini file. I have deleted and downloaded again the gwtoolbox
program. The mini map remained the size of the green pointer in the Guild
Wars mission map. I thank you for your time and help. Brian

**Comment by HasKha** [comment]
Seems like your problem is the size of the minimap, remember that you can change its size by unticking "freeze..." in settings and scrolling over the minimap.

You can also reset it from the settings: somewhere in your GWToolbox.ini file there is a line "[minimap]" (without the quotes), under that there are the minimap settings, delete the line with scale ("scale = 1.0") to reset the zoom within the minimap and delete the line with width ("width = 550") to reset its size.

**Comment by Waldenpond007** [comment]
trying the shift key and mouse scroll wheel with the cursor over the minimap does not resize the map.
It does however move the camera zoom in/out. I have tried the ctrl, alt and shift keys at times while trying to zoom out the minimap. I also tried adding the width=550 after the color pings in the mini map section. I saved the file, then restarted the GWtoolbox program. the minimap did not change the size.  I did un-tick the freeze box. 
The minimap is working but it is the size of the green direction circle/arrow on the mission map 

Here is the code from the ini file

[hotkey-1:SendChat]
msg = age
active = false


[hotkey-2:SendChat]
msg = stuck
active = false


[hotkey-3:SendChat]
msg = resign
active = false


[hotkey-4:DropUseBuff]
SkillID = 925
active = false


[launcher]
dllversion = 1.10


[minimap]
color_range_hos = 0xFF881188
color_range_aggro = 0xFF994444
color_range_cast = 0xFF117777
color_range_spirit = 0xFF337733
color_range_compass = 0xFF666611
color_map = 0xFF999999
color_mapshadow = 0xFF120808
color_agent_modifier = 0x001E1E1E
color_eoe = 0x3200FF00
color_qz = 0x320000FF
color_target = 0xFFFFFF00
color_player = 0xFFFF8000
color_player_dead = 0x64FF8000
color_signpost = 0xFF0000C8
color_item = 0xFF0000F0
color_hostile = 0xFFF00000
color_hostile_damaged = 0xFF800000
color_hostile_dead = 0xFF320000
color_neutral = 0xFF0000DC
color_ally = 0xFF00B300
color_ally_npc = 0xFF99FF99
color_ally_spirit = 0xFF608000
color_ally_minion = 0xFF008060
color_ally_dead = 0x64006400
color_drawings = 0x00FFFFFF
color_quest = 0xFF22EF22
color_north = 0xFFFF8000
show = true
x = 85
y = 365
size = 24
color_pings = 0x00FF0000


[mainwindow]
x = 963
y = 0
tabsleft = false
adjustresize = false
borderlesswindow = false
Travel0 = 51
editbuild_up = true
freeze_widgets = false
Travel1 = 122
save_location = false
nobackgroundwidgets = false
minimize_alt_position = false
Travel2 = 96
hide_target = false
minx = 972
miny = 45
suppressmessages = false
openlinks = false


[builds1]
buildname = 
name1 = 
template1 = 
name2 = 
template2 = 
name3 = 
template3 = 
name4 = 
template4 = 
name5 = 
template5 = 
name6 = 
template6 = 
name7 = 
template7 = 
name8 = 
template8 = 
name9 = 
template9 = 
name10 = 
template10 = 
name11 = 
template11 = 
name12 = 
template12 = 
showNumbers = true


[TargetHealth]
show = false
x = 1095
y = -16


[Distance]
show = true
x = 1073
y = -2


[bonds]
show = false


[damage]
show = false


[hotkey-7:Action]
active = false


[pcons]
apple = false
egg = true
corn = false
kabob = false
skalesoup = false
pahnai = false
cupcake = false
grail = false
armor = false
essence = false
pie = false
alcohol = true
warsupply = false


[timer]
x = 248
y = 12


[hotkey-8:Toggle]
active = false


[hotkey-10:DropUseBuff]
active = false


[hotkey-11:UseItem]
hotkey = 0
modifier = 0
active = false

**Comment by HasKha** [comment]
sorry its size, not width, my bad. Delete that line "size = 24" or change the value

**Comment by Waldenpond007** [comment]
Okay I'll try that. Thank you
