### ISSUE TITLE
Dialogs for Hotkeys keep resetting to 0 for ID 

### ISSUE THREAD

**Issue by BearsMan** [HasKha/GWToolboxpp#321]
any reasons why the dialog ID resets to 0 for Hotkeys meaning the custom ones, not the preset ones?

[hotkey-010:Dialog]
hotkey = 0
modifier = 0
active = true
DialogID = 0
DialogName = The City of Torc'qua: Take

(example mentioned above)

**Comment by reduf** [comment]
Try to save settings manually before closing toolbox.

**Comment by HasKha** [comment]
or close toolbox before you close GW. 

Those are the most common cases where settings don't get saved:
* having two toolbox instances up. Closing the first saves, but closing the second also saves, overwriting changes. 
* Closing guild wars while toolbox is running within. This *should* work, but I know it doesn't work for some users.

**Comment by BearsMan** [comment]
fixed thanks Has and Livia
