### ISSUE TITLE
You have been playing for... Chat filter not working

### ISSUE THREAD

**Issue by 3vcloud** [HasKha/GWToolboxpp#324]

**Comment by kazerniel** [comment]
Neither do custom chat filters for me.

The lines I wanted to filter were "earned a skill point" and the one about leveling up. Neither does anything, I still see these lines about other players.

**Comment by reduf** [comment]
The reason for "You have been playing for" is that it doesn't seem to be sent by the server. I'm not sure why we have an option for it, because it probably never worked.

For the custom chat filters, it's only the "real" players messages that will be filtered.

**Comment by reduf** [comment]
Won't add.
It changes the flow too much for too little gain, because it's a message generated on the client.

**Comment by 3vcloud** [comment]
I fixed this on mine by feeding the filters into `RegisterLocalMessageCallback`
