### ISSUE TITLE
friend list login 

### ISSUE THREAD

**Issue by BearsMan** [HasKha/GWToolboxpp#327]
https://i.imgur.com/aaezkfD.jpg

if u look closely there are multiples of the same due to last seen online/offline feature for friends to see how online and offline any reason why there are multiple copies of the same name?

**Comment by reduf** [comment]
Never saw this bug, anyone else got it ?

**Comment by 3vcloud** [comment]
try adding a new friend

**Comment by 3vcloud** [comment]
As a catchall, we should really check for empty player name string before printing - theres no point otherwise :)

**Comment by reduf** [comment]
Yeah, I thought of that, but I was wondering if there was a deeper reason that would be worth fixing instead.

**Comment by 3vcloud** [comment]
The friend list has a separate connection thing to the main game, which would be why you can sometimes disconnect from friends whilst still playing the game - maybe a reconnect would show this error but its not worth the testing
