### ISSUE TITLE
create /ff command

### ISSUE THREAD

**Issue by reduf** [HasKha/GWToolboxpp#328]
same as `/resign`

**Comment by PostCrafter** [comment]
Does this mean we will get `/forfeit`, `/surrender` and `/concede` as well?

**Comment by Vilt-Coding** [comment]
Don't forget `/capitulate`, `yield`, and `/submit` aswell!

**Comment by Hour-of-the-Owl** [comment]
`/Frankreich`

**Comment by HasKha** [comment]
added `/ff` only

**Comment by rosshadden** [comment]
Why was this requested? `/resign` is not many more letters, and the hotkey system means if you _really_ wanted to save keystrokes you could bind it to a key. In my experience having aliases also waters things down and makes it more confusing for users and developers both. "Forfeit" isn't even two words so abbreviating it to FF doesn't make sense, unless this is some sort of gaming nomenclature I'm unaware of? (very possible)

**Comment by HasKha** [comment]
Yea, it's just really common. I know League of Legends has it, idk about other games. 

https://www.urbandictionary.com/define.php?term=FF
