### ISSUE TITLE
Guild Wars Toolbox++ Crash!

### ISSUE THREAD

**Issue by BearsMan** [HasKha/GWToolboxpp#330]
https://cdn.discordapp.com/attachments/224695376102293514/572880062278402048/image0.jpg

sent from Hayden on Discord he is just a regular member in GWToolbox Discord

**Comment by HasKha** [comment]
I'm just going to copy what I already sent on Discord and close this, since we had no further reply on Discord. 

> Probably an old dll. Go into settings folder and delete gwtoolbox.dll, then relaunch

> Make sure you are running the latest dll and .exe, try manually downloading the dll from the GitHub releases page. Run it as admin. Run without any other programs that might be affecting gw. Install dx9 runtime. If it still has the same problem, either you did some of that wrong or your antivirus is really messing with you.

> But in general that error message makes me think you are running an old version. Keep in mind the downloader might fail (permission issues, antivirus), so check that the .dll matches (compare sizes, each release is slightly different)
