### ISSUE TITLE
[May 1 update fix] 2.24 beta

### ISSUE THREAD

**Issue by HasKha** [HasKha/GWToolboxpp#332]
**As with all betas, keep in mind this might be unstable and may crash your game at any time**

Please use this thread for feedback and bug reports.

Reported issues (ticked = fixed internally):
* [ ] toolbox borderless functionality is disabled
* [x] toolbox chat messages to user do not work. Commands like /stuck and messages to team chat should work. 
* [x] crash when skipping cutscene
* [x] crash when loading a build on player
* [x] clicking on player's name to whisper not working

[ToolboxBeta.zip](https://github.com/HasKha/GWToolboxpp/files/3144000/ToolboxBeta.zip)

**Comment by Hour-of-the-Owl** [comment]
reported bugs:

* cutscene autoskip causes a crash
* loading a hero team causes a crash, although the team will be successfully loaded
* Clicking on player's name in Trade Chat feature won't let you whisper

**Comment by BearsMan** [comment]
Hotkeys (dialog) wont work - needs fix


 

Author 
BearsMan commented 7 minutes ago 
Update: targeting Mini hotkey works :D I will test quest dialog hotkeys to make sure that one needs fixing

**Comment by Rupurin** [comment]
loading individual hero builds with the hero builds feature works.
Loading a build to your own skill bar crashes the game. (both with the hero builds feature as with the builds feature)

**Comment by Hour-of-the-Owl** [comment]
It seems that loading multiple hero builds rapidly still causes the crash, even if you do them individually.

**Comment by disteLLL** [comment]
I experienced a crash when registering a minipet in the HoM

**Comment by HasKha** [comment]
> I experienced a crash when registering a minipet in the HoM

probably related to skipping cutscenes

**Comment by rosshadden** [comment]
The new build works great for me after ~2 days of use. Thank for providing a pre-built DLL. I use Linux and would have had to jump through a lot of hoops to build this from source, unless you can compile it with Mono outside of Visual Studio.

**Comment by HasKha** [comment]
released 2.24

**If you have used the toolbox beta above, please make sure to update**
