### ISSUE TITLE
Hotkeys function doesnt work

### ISSUE THREAD

**Issue by BearsMan** [HasKha/GWToolboxpp#334]
Hotkeys (dialog) wont work - needs fix

**Comment by BearsMan** [comment]
Update: targeting Mini hotkey works :D I will test quest dialog hotkeys to make sure that one needs fixing

**Comment by BearsMan** [comment]
I figured it out it doesnt show in chat window

**Comment by HasKha** [comment]
related to #332, known issue. closing.
