### ISSUE TITLE
[Feature] Quick switch between TB minimap and builtin compass

### ISSUE THREAD

**Issue by MiloszKrajewski** [HasKha/GWToolboxpp#338]
Hi,

Minimap is great, but in tight tactical situations when "the excrement makes physical contact with a hydro-electric powered oscillating air current distribution device" original compass allows to control heroes better by allowing to put flags on the ground. 

I understand that adding this feature (flags on the ground) might be a little but complicated but ability to toggle minimap/compass visibility with single key should be relatively easy.

BTW, thanks for great work.

**Comment by Hour-of-the-Owl** [comment]
I think it should be possible to use texmod to make the default compass invisible except for the hero flags, so you can have those available at all times. I've not actually tried this though - anyone care to confirm whether or not it could work?

**Comment by reduf** [comment]
I think he meant the button to then be able to click on the ground to put the flag. If it's the case I think the better solution here is to replicate that. It shouldn't be too hard, but we need to do some reversing for this functionality.

**Comment by MiloszKrajewski** [comment]
What I really want is ability to move heroes by putting flags on the ground, yes.
I just assumed that it is quite hard to implement (flagging on minimap is in 2d, flagging on the ground is in 3d so access to terrain data would be needed?).

As a remedy, I was suggesting ability to switch between built in compass (F11 -> Interface -> Compass) and minimap (Toolbox -> Settings -> Minimap) with a single keystroke (Toolbox -> Hotkeys?).

Of course, fully integrated flagging in the ground would much better.

**Comment by reduf** [comment]
We won't do this feature as mentioned and close this issue, because the 3d flagging feature is already mentioned in issue #61.
