### ISSUE TITLE
Easy way to donate faction to alliance

### ISSUE THREAD

**Issue by Bu11etmagnet** [HasKha/GWToolboxpp#341]
It would be nice to have a button to donate Luxon/Kurzick faction to one's alliance, without having to walk up to the NPC, select the right option and fill out the character's name.
This could be among the Dialog options. The "Raise alliance reputation" dialog id is 0x87
It would be nice if the name of the character could be filled in automagically.

**Comment by Hour-of-the-Owl** [comment]
I think the most useful part of this feature is inputting your current character name, and that is surely something that nobody would object to, so it wouldn't even need to be an option..?

**Comment by 3vcloud** [comment]
Don't do it, its a trap - imagine all those JQ bots firing up toolbox and breaking the leaderboard!

**Comment by Azzurvif** [comment]
Bots already write down their name instantly

**Comment by reduf** [comment]
If I remember correctly, the name is only client side so they just ignore it.

**Comment by reduf** [comment]
You would still need to walk-up to the npc. I don't really get the use cases other than for botting. Openning whatever window has the button is as slow as typing the character name.

**Comment by 3vcloud** [comment]
have you checked out my fix for this? saves me a bunch of time when donating to alliance

**Comment by reduf** [comment]
Can you ping a link of where to look please?

**Comment by 3vcloud** [comment]
https://github.com/3vcloud/GWToolboxpp/blob/1b762635ad96bd628b63f1617fb27ef868285651/GWToolbox/GWToolbox/Modules/GameSettings.cpp#L966

**Comment by Bu11etmagnet** [comment]
@reduf Do you consider AFKing in Zos Shivros as "botting" ?

**Comment by reduf** [comment]
No

**Comment by 3vcloud** [comment]
Included in merge 2020-05-02
