### ISSUE TITLE
Remember chat "history" even after logout

### ISSUE THREAD

**Issue by 3vcloud** [HasKha/GWToolboxpp#345]
When changing chars or logging out it would be cool to log in again and see past chat history instead of a clean slate, and for the sent chat histtory to be remembered too

**Comment by reduf** [comment]
I don't know if this is desirable, because the chat history is private to the account. That said, it's realistically not a problem, unless you are playing on a public computer and leaving Guild Wars open.

**Comment by 3vcloud** [comment]
Would be great if I can get a nudge in the right direction some time and I can try to tackle myself

**Comment by reduf** [comment]
The memory from the chat buffer must be freed after the player disconnect, so it should be very easy to have a data breakpoint on the chat buffer and look who use it when you disconnect. At this point, it probably boils down to rewriting the first byte of the function with a "retn".

**Comment by reduf** [comment]
Imo the game choose to do it this way for a good reason. It doesn't sound like a good default.
