### ISSUE TITLE
Minimap is broken (Terrain glitch in certain areas - some areas are fine)

### ISSUE THREAD

**Issue by BearsMan** [HasKha/GWToolboxpp#346]
https://i.imgur.com/e0HVZpE.jpg

**Comment by Drewrockon** [comment]
I see this issue too. restarting gwtoolbox fixes it when it happens but at the risk of crashing the game

**Comment by Hour-of-the-Owl** [comment]
temporary workaround: click `Load Now` on your settings to load the correct map

**Comment by reduf** [comment]
Fixed in 09b59acbb8a0f9c6763857fab2302ce6613d6034
