### ISSUE TITLE
[enhancement] save as setting the "unlock move all"

### ISSUE THREAD

**Issue by gwmai** [HasKha/GWToolboxpp#353]
When I resize my windows the widgets keep moving and changing places so I was wondering if it's possible to save the "unlock move all" button setting as permanently enabled.

**Comment by reduf** [comment]
Guild Wars save the positions of the ui by saving the width percentage and height percentage instead of the absolute positions. That would be better and I will look if we can do this not too hardly, because this part is from a 3rd party library, namely imgui.

**Comment by gwmai** [comment]
Anything you could do would be great. Thanks for considering this

**Comment by reduf** [comment]
The position of the UI elements are saved by imgui and it's not supported. Doesn't really make sense to save the "unlock move all".
