### ISSUE TITLE
auto-popping tonics

### ISSUE THREAD

**Issue by Hour-of-the-Owl** [HasKha/GWToolboxpp#36]
Is it possible to add tonics to the pcons popper, much like the in town speed boosts?

**Comment by HasKha** [comment]
it can't be done easily in the current setup, as it's not as straightforward (which tonic should it use?). Plus it would ruin the alignment. I'll think about it.

**Comment by DarkManic** [comment]
And while you are at it also add auto-popping for minipets.

**Comment by Hour-of-the-Owl** [comment]
Let's not do minipets =P tonics should be fine now though, yes? pop the first one in the inventory

**Comment by reduf** [comment]
Won't do, but you can bind an hotkey that is triggered when you enter a zone to use a tonic.
