### ISSUE TITLE
Title Widget/Setting request

### ISSUE THREAD

**Issue by DaynaGW** [HasKha/GWToolboxpp#362]
a widget or setting that controls titles for you:
If you enter an area in elona it auto sets titles to lightbringer (just explorable)
or if u enter an asura/norn/ebon it sets to the right title (just explorable)
and if ur back to town it auto sets the title to whatever you like (maybe in a tier list)
Tier1 : title xy (and if you dont have it on that char it switches to tier2)
Tier2 : title xy (if false then tier3 etc)

would be cool since i think many ppl dont use the bonus they would get by the title or often forget to change it back for doa after vq or dungeon

**Comment by HasKha** [comment]
There is a hotkey that sets the most relevant (for gameplay) title. At the moment we don't have plans to add a UI to set one or more custom ones.
