### ISSUE TITLE
targeting miniatures

### ISSUE THREAD

**Issue by GWisLove** [HasKha/GWToolboxpp#364]
hii
gw crashes when i am trying to target miniature ghostly priest via hotkey using the id 349 of the miniature. 
any ideas?
thx

Edit: seems like it happens only when i click on "Run" in hotkey widget

**Comment by GWisLove** [comment]
An option to "use" the minipets will be a nice addition if its possible

**Comment by reduf** [comment]
Does it do it all the time or it only happen once ?

**Comment by GWisLove** [comment]
all the time, but its not crashing when i use hotkey, only if i click on "Run"

**Comment by reduf** [comment]
Can you give me the target id in the hotkey window and which mini it is please ?

**Comment by GWisLove** [comment]
349

**Comment by 3vcloud** [comment]
Can't do a PR atm because my hotkey module is being worked on. `ChangeTarget` needs to be in the game thread - this might affect other hotkeys but haven't looked into it

```
if (closest > 0) {
        GW::Agent* agent = agents[closest];
        GW::GameThread::Enqueue([agent]{
            GW::Agents::ChangeTarget(agent);
            });
	}

**Comment by 3vcloud** [comment]
Included in merge 2020-05-02
