### ISSUE TITLE
add an option to disable hotkeys while chatting

### ISSUE THREAD

**Issue by smiley232** [HasKha/GWToolboxpp#366]
Would it be possible to detect whether the chat input is opened or closed? If so, can we please get an option to disable hotkeys while the chat input is active (same as vanilla Guild Wars functionality)?

At the moment, whenever I write a chat message containing the hotkey character (not case sensitive, btw) the command runs immediately.

Thank you very much.

**Comment by HiImFlo** [comment]
Whenever I type a word that contains "x" I use a rezz scrolls 🤔 .

**Comment by smiley232** [comment]
You're lucky then. Whenever I type a word that contains "b" I use/drop Recall. :D
I Know that the problem is on my end but it would be really great to solve this w/o me buying a 100-buttons mouse.
