### ISSUE TITLE
Save Any/X build

### ISSUE THREAD

**Issue by reduf** [HasKha/GWToolboxpp#371]
Found here: https://www.reddit.com/r/GuildWars/comments/cqm4ct/gwtoolbox_is_it_possible_to_search_your_inventory/ewy4p2p/

**Comment by Hour-of-the-Owl** [comment]
You can already do that though. Try loading a build with the wrong primary profession and you'll get all the secondary stuff anyway.

**Comment by reduf** [comment]
Big brain
