### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by BearsMan** [HasKha/GWToolboxpp#374]
when playing the game it crashes even with Toolbox up maybe needs to be fixed

**Comment by reduf** [comment]
It's not remotly enough information.

Does it happen in Kamadan?

**Comment by BearsMan** [comment]
It’s happened in general regardless of where u are I think

**Comment by Bu11etmagnet** [comment]
https://www.chiark.greenend.org.uk/~sgtatham/bugs.html#respect

**Comment by BearsMan** [comment]
ok lets say u are standing in kamadan and u tab out of the game I say after 5-10 mins of that happening may crash for no reason
