### ISSUE TITLE
Teleport double click bug

### ISSUE THREAD

**Issue by NG-Guildwars** [HasKha/GWToolboxpp#378]
Hello friends!
Firstly, it seems that my mouse is crap, once is a time it does double click instead of just one click (yes, I know that I need to replace it...).
Anyways, I have been playing GW and wanted to teleport to Kamadan.
So I clicked on the Kamadan-shortcut in the teleport-window, and my mouse double-clicked it.
Instead of teleporting to kamadan, I found myself in Character-select scereen (https://i.imgur.com/d16KKFf.jpg) - with empty char slots, like the Client of a new account. From here I had to close GW and reopen it.
It happened to me few times, not only when I wanted to teleport to Kamadan (also the others, Vlox, Gadds etc.).

**Comment by BearsMan** [comment]
restart client because that is not a toolbox bug its related to the client itself I used to have that too

**Comment by GWisLove** [comment]
@BearsMan It happened alot of times (not only today), even after I restart GW Client.

**Comment by reduf** [comment]
Will look into that, but it's not suprising.

**Comment by 3vcloud** [comment]
I was about to suggest making a new button type that had a delay check but its possible to duplicate this bug using TP command too

**Comment by reduf** [comment]
Yeah, we didn't put any guard arround it. I still want to deal with the button event in a single frame, but maybe we could disable button event for the next few ms.
