### ISSUE TITLE
Only show one capture signet

### ISSUE THREAD

**Issue by reduf** [HasKha/GWToolboxpp#379]
Can't be deleted otherwise as far as I know, so if every skills are unlocked they can potentially pollute the window.

**Comment by Azzurvif** [comment]
Keep in mind that the total number of skill displayed in the UI takes into account the total number of capture signets.

**Comment by reduf** [comment]
The reason is that I have a irresponsible friend that bought ~5k signets on one of his main.
Now, everytime he opens the skills window, he lags or crash.

That said, I might just limit to a smaller number like 100.

**Comment by Azzurvif** [comment]
It could be submitted to the devs for a fix or a way to refund ! Do you have reddit ? Sometimes one of them is coming and checking.
A situation that causes the game to crash may be fixed

**Comment by 3vcloud** [comment]
Is this purely a client side thing or do we get a stream opened for the skills window? I haven't checked but I could sort it if it can be fixed at stoc level

**Comment by reduf** [comment]
It's definitely sent at some point from the server. I didn't look if it was every time you open the skill window.

**Comment by 3vcloud** [comment]
Packet 221 updates the count of an available skill after buying it, but can't find the big boy packet in login - you can probably trace to the array from that packet? I don't know how sorry :(

**Comment by 3vcloud** [comment]
https://github.com/HasKha/GWToolboxpp/releases/tag/5.14_Release
