### ISSUE TITLE
Widgets

### ISSUE THREAD

**Issue by ExcrementSniffer** [HasKha/GWToolboxpp#38]
I don't know if it would be possible or not but could you add a widget for the actual time zone for when you're playing borderless mode....
Also would it be possible to add a simple calculator too....
Many Thanks 👍

**Comment by HasKha** [comment]
timer is definitely possible, calculator is a bit more work. I'll do both with an interface rewrite, right now they would be clunky to implement.

**Comment by HasKha** [comment]
implemented clock in the new branch, will be part of next release
