### ISSUE TITLE
Make identification and salvage more user friendly

### ISSUE THREAD

**Issue by MangelMaxime** [HasKha/GWToolboxpp#382]
Is it possible to add a feature like one of this:

- Allow activating kit via a custom "hotkey use item"
- If the user press a specific key while a kit is active, keep it active when used. So for example, the user double click on a kit and keep "Shift" pressed then he can click on the items he wants to identify without having to double click on the kit between each item

I found about a similar feature discussed in #164. But compared to #164 we don't do everything automatically it's still the user who does the work.

**Comment by 3vcloud** [comment]
An option that stops the user having to re-click the ID kit for each item would be better IMO, i.e. keeps the identification icon active if the kit still has uses when identifying an item. Won't need a hotkey that way

**Comment by reduf** [comment]
What @3vcloud said is very likely what we would do. Maybe as long as a key is holded.

**Comment by 3vcloud** [comment]
Adding context menu to kits has made identification and salvage more user friendly, and after spending a good few hours trying to hook into the function that "primes" the identification or salvage kit (i.e. changes the icon ready for you to identify something) I didn't get very far. Using context menu though, I don't use the original method
