### ISSUE TITLE
Coindrop Hotkey should NOT be there anymore

### ISSUE THREAD

**Issue by BearsMan** [HasKha/GWToolboxpp#384]
https://wiki.guildwars.com/wiki/Game_updates:2016

its under code line 369 in Hotkeys.cpp

https://gyazo.com/8ddb11d3eeccabbdfec35a15ddb4462b

Code line shown in above link

**Comment by reduf** [comment]
Some people still use it for fun, so I'll leave it as there is no problem with it. Let's call it "deprecated". :)
