### ISSUE TITLE
Compiler used to build the client might change from VC6 to VS2017 - will that break Toolbox?

### ISSUE THREAD

**Issue by DrStephenCW** [HasKha/GWToolboxpp#386]

**Comment by reduf** [comment]
Hey, switching compiler might break some signatures, but most of the data won't change, so it shouldn't be too hard to fix with few exceptions. Nothing we can't handle. :)

Hopefully, it will go smoothly on your side as well.

**Comment by DrStephenCW** [comment]
K, great.  I don't have an ETA - it's running internally on VS 2017 but probably needs some kind of QA before we ship it Live.
