### ISSUE TITLE
Now using VS2017 for GW.exe

### ISSUE THREAD

**Issue by DrStephenCW** [HasKha/GWToolboxpp#387]
Just so you know, we pushed the compiler change from VC6 to VS2017.

**Comment by oyvindln** [comment]
It seems you introduced some bug when changing pvp equipment that disconnects people.

**Comment by HasKha** [comment]
Thanks for letting us know!

**Comment by BearsMan** [comment]
https://gyazo.com/d84ea01845b5b564e8b8d7d1fd3de19b

this was the error that was found after the update

**Comment by reduf** [comment]
Pattern to fix in GWCA:
* [ ] GWCA\Examples\PacketLogger\main.cpp
* [ ] GWCA\Source\SkillbarMgr.cpp
* [x] GWCA\Source\UIMgr.cpp
* [ ] GWCA\Source\FriendListMgr.cpp
* [ ] GWCA\Source\ChatMgr.cpp
* [ ] GWCA\Source\RenderMgr.cpp
* [ ] GWCA\Source\PartyMgr.cpp
* [ ] GWCA\Source\MerchantMgr.cpp
* [ ] GWCA\Source\MemoryMgr.cpp
* [ ] GWCA\Source\MapMgr.cpp
* [ ] GWCA\Source\ItemMgr.cpp
* [x] GWCA\Source\StoCMgr.cpp
* [ ] GWCA\Source\GWCA.cpp
* [ ] GWCA\Source\EffectMgr.cpp
* [x] GWCA\Source\CtoSMgr.cpp
* [ ] GWCA\Source\CameraMgr.cpp
* [ ] GWCA\Source\AgentMgr.cpp

Patterns to fix in GWToolbox
TODO

**Comment by reduf** [comment]
You can have some insights about how the fixes are coming along here: https://github.com/GregLando113/GWCA/projects/1

**Comment by reduf** [comment]
Update done and beta on Discord. You can follow bug fixes in issue #390.
