### ISSUE TITLE
character select screen

### ISSUE THREAD

**Issue by Hour-of-the-Owl** [HasKha/GWToolboxpp#39]
please make it so the timer disappears, since it's not actually showing any accurate information

**Comment by HasKha** [comment]
doing this will also remove timer from loading screen, which I'm not sure how I feel about.

**Comment by Hour-of-the-Owl** [comment]
Surely it doesn't tell you anything useful on the loading screen either... at least for me, all it does is freeze what time it was at when I left the previous map.

**Comment by HasKha** [comment]
yea but you see when the new instance gets created (timer resets). I can see your point though, frames drop during load so its not accurate anyway.

**Comment by HasKha** [comment]
implemented in the new branch, will be part of next release
