### ISSUE TITLE
Ctrl+click celestial sigils

### ISSUE THREAD

**Issue by Hour-of-the-Owl** [HasKha/GWToolboxpp#393]
Moving one in between chest and inventory works fine. If you already have one in there though, the second one can't move. It's trying to make them stack, which obviously doesn't work.

**Comment by Hour-of-the-Owl** [comment]
A similar issue occurs with Candy Cane Shards. They should stack with each other, but instead get moved into separate inventory positions, so you have to stack them manually.

**Comment by MangelMaxime** [comment]
Hello, 

I took a look at this issue. I don't have celestial sigils so I can only speak for the `Candy Cane Shards` items.

It seems that their type is `17` which means they are considered [SalvageItem](https://github.com/GregLando113/GWCA/blob/7285a3dfdfd01bdeac38b801866cb9edd4d172d3/Source/ItemMgr.cpp#L281).

What is considered a `SalvageItem` from GWCA point of view? And is it correct to consider them non stackable?

**Comment by 3vcloud** [comment]
They're considered Salvage Items because items of type 17 have "Salvage Item" in their description. Its obviously incorrect to consider them non stackable, because they're stackable ;)

**Comment by MangelMaxime** [comment]
Ok, so should we add a special case when detecting a "Salvage Item" and check for the item ID?

**Comment by 3vcloud** [comment]
Thats for you to find out and let us know to help resolve this bug ;)

**Comment by 3vcloud** [comment]
```
		inline bool IsStackable() {
			return interaction & 0x80000;
		}
```

**Comment by MangelMaxime** [comment]
Hello @3vcloud,

could you please explain how you end up with this code? 

I am new to reverse engineering and so I am learning via trial and error exploring the GWCA and Toolbox code.

**Comment by 3vcloud** [comment]
Well I know from experience that `item->interation` is a set of flags for an item - these bits are stored as a single unsigned int in `GW::Item`, so by doing some trial and error you can start to figure out which bits mean which by converting the `interaction` value to a binary string:
```
‭‭00101010001000100001011000000001‬ = candy cane scythe (gold, non salv)
‭00100000000000100000001001000001‬ = accursed icon (gold, can salv)
‭00100000000010000000001000000001‬ = steel ingots
‭00100001000010000001001000000001‬ = tengu support flare (non salv)
‭00100000000000100000001001000011‬ = Warden vestments (gold, upgrades removed)
‭00100000000010000000001000100001‬ = granite (non salv)
‭00100001000100000000011000000001‬ = derv minor rune (non salv)
‭00100101000000000000011000000001‬ = inscription (non salv)
‭00100001000010000011001100010001‬ = Igneous summong stone (green, non salv)
‭00100000000010000000001001000001‬ = Candy cane shard
‭00100001010000000001001000000000‬ = mini koss (purple)
‭00100001000000000001001000010001‬ = mini gwendoll (green)
‭00100001000010000000011000000001‬ = 20 drake kabobs

‭00000000000000100000000000000000‬ = GOLD
‭00000001000000000000000000000000 = NON SALVAGABLE? USABLE?
‭00000000000010000000000000000000 = STACKABLE?
00000000000000000001000000000000
00000000‭010000000000000000000000‬ = PURPLE
```

**Comment by MangelMaxime** [comment]
Ok, thank you for the explanation.

I will update my repo tomorrow and test your solution which seems cleaner :)

**Comment by reduf** [comment]
Fixed by the PR on GWCA. Thanks again.
