### ISSUE TITLE
Toolbox should not connect to Discord by default.

### ISSUE THREAD

**Issue by Bu11etmagnet** [HasKha/GWToolboxpp#395]
Every time I start Toolbox, I get a nasty red message saying "GWToolbox++: Failed to create discord connection".

Not everybody has Discord installed. There should be an option to prevent connecting to (possibly non-existing) discord.

**Comment by BearsMan** [comment]
@Bu11etmagnet if I'm correct when it says failed it actually still works but in a way yes not everyone has it installed so there should be an option to prevent it

**Comment by reduf** [comment]
It was meant to be disable by default, but the proper way to disable it now is to go in Settings -> ToolboxSettings and uncheck "Discord integration".
