### ISSUE TITLE
Danger meter?

### ISSUE THREAD

**Issue by StarWong** [HasKha/GWToolboxpp#396]
I vaguely recall some kind of danger meter when I last played with toolbox. It would report the number of enemies who have me as their target. After a brief trial with this iteration of the toolbox, I've yet to find this feature. If this is indeed missing, could someone add the feature or point me in the right direction? (I did find some counter boxes (e.g. soul tormenter counter), but those would tally enemies by location and not by whether they're targeting me.)

I'd be glad to add this feature myself, but I should mention that while I'd be excited to do so, I've only ever had limited experience with the autoit version of the toolbox, and so any rough sketches or instructions on how to do this might have to be just a tad more involved than it'd need to be otherwise

**Comment by reduf** [comment]
The problem with this feature was that it was extremely inaccurate. The way it was done back then is: whenever an agent attack an other agent we assume that it's his target. But it's kind of broken and I doubt we will add it. I'll leave the issue open for few days though, maybe someone wants to comment on that.

**Comment by BearsMan** [comment]
also the danger meter written here makes no sense because as someone else whose name will not be mentioned because of target swapping when the very first target u attack is instantly swapped to a new one so technically this feature probably shouldn't be in Toolbox
