### ISSUE TITLE
GW crash while using Cons

### ISSUE THREAD

**Issue by dollety** [HasKha/GWToolboxpp#398]
When running Toolbox application and enabling consumables (Pcons → sweets or alcohol) GW is crashing every time. I also tried different PC/Laptops, because maybe of a new windows update maybe, but GW is crashing every single time. This happens when i'm outside in an instance and using alcohol / sweets. 

**This is the message i always get when crashing:**
[GWToolbox_crash.txt](https://github.com/HasKha/GWToolboxpp/files/4208098/GWToolbox_crash.txt)

**Comment by PostCrafter** [comment]
There has been a GW update a couple of hours ago which update the packet headers.
A fix should be available soon (tm).
