### ISSUE TITLE
Large interface

### ISSUE THREAD

**Issue by Bu11etmagnet** [HasKha/GWToolboxpp#404]
It would be nice to have an option for a larger interface. Toolbox on a 3840x2160 resolution is tiny:
https://imgur.com/a/eoKw1OF

**Comment by PostCrafter** [comment]
Have you tried dragging the windows/widgets bigger and adjusting the Font Scale (Settings > Theme > Global Font Scale)?

**Comment by Bu11etmagnet** [comment]
It worked, but it's not the most intuitive interface :) I clicked it a dozen times for no effect. Nothing suggest to drag it.

**Comment by Bu11etmagnet** [comment]
Would it be possible to add a tooltip on Global Font Scale and Global Alpha?

**Comment by PostCrafter** [comment]
Pretty much all of the number fields use the same interface: dragging to change the value and double click to edit it directly.

**Comment by reduf** [comment]
I might not have understood correctly, but isn't that a common practice with windows on a desktop computer? (Only the dragging not the font) Other than that, there is the following that suggest to drag it.
![image](https://user-images.githubusercontent.com/1349199/75657593-d5b43c80-5c66-11ea-9355-aa5f6f076e9d.png)

**Comment by Bu11etmagnet** [comment]
Tell me which part of the interface suggests that these fields are draggable:

![](https://i.imgur.com/tn5lRsJ.jpg)
