### ISSUE TITLE
remove dungeon chest popup

### ISSUE THREAD

**Issue by Hour-of-the-Owl** [HasKha/GWToolboxpp#406]
When you complete a dungeon, you get an enormous popup in the middle of your screen, preventing you from seeing the actual chest to open it and pick up your drops. Please add an option to remove it.

**Comment by 3vcloud** [comment]
@PostCrafter if you can bring your `GameSettings` in line with the refactor from 3.4 I'd like to pick this commit and close this off

**Comment by PostCrafter** [comment]
Sure, I'll do that in a bit.

**Comment by PostCrafter** [comment]
I've rebased the branch in #414 so you can cherry-pick this feature now.

**Comment by 3vcloud** [comment]
Added in 723373f80df7147bddd659edfbe6a5ba964c86fc
