### ISSUE TITLE
Gw multilaunch

### ISSUE THREAD

**Issue by zcaywa** [HasKha/GWToolboxpp#407]
Prior to this last update (I have not played in 6-8 months so there may have been other updates) I was using GW multilaunch and when I launch GW toolbox, a character/screen selection box popped up allowing me to start GW toolbox on all of my sessions individually.  One screen per launch.  However; when I launch GW toolbox now, it will not startup in any of my screens, nor give me the option to character or screen select as before.  Hoping this gets fixed as it is such a useful 'toolbox' for GW.

**Comment by reduf** [comment]
You might have an outdate launcher if you didn't play in 6-8 months. Try to use the updated launcher: https://github.com/HasKha/GWToolboxpp/releases/download/3.6_Release/GWToolbox.exe
