### ISSUE TITLE
Map: Highlight auto-target

### ISSUE THREAD

**Issue by DubbleClick** [HasKha/GWToolboxpp#409]
![image](https://user-images.githubusercontent.com/7896469/77848857-00db6e80-71c8-11ea-89b0-06365e97cfdf.png)

Like this. This is the one functionality that TB is missing that prevents me from not using the default compass.

**Comment by 3vcloud** [comment]
Added for next release, https://github.com/HasKha/GWToolboxpp/commit/527c20397e0e70224602b3376271a735da3da626
