### ISSUE TITLE
cam fov command game crash

### ISSUE THREAD

**Issue by Lukas-Eisele** [HasKha/GWToolboxpp#41]
The `/cam fov` command with a negative float value crashes the game.

**Comment by HasKha** [comment]
thanks, I'll do a pass on the chat commands, let me know if there are any other issues

**Comment by Lukas-Eisele** [comment]
I think you fixed the wrong one.
/zoom was working fine with negative values .
It's /cam fov

**Comment by HasKha** [comment]
oops, thanks for the catch, fixed /cam fov too
