### ISSUE TITLE
Gwtoolbox ++ dll not found. 

### ISSUE THREAD

**Issue by waldenpond1** [HasKha/GWToolboxpp#410]
I have deleted gwtoolbox++, and downloaded the program again.  It can not find the dll.
The program was working on 4/28/2020 until about 1:45pm Az time. 
The program had updated itself to the  current version and I was working fine.

**Comment by chichke** [comment]
Same, when I did download the dll from the release tab and had it specified, but when i run gw i have a black blink and gwtoolbox doesn't appear.

**Comment by BearsMan** [comment]
yea Windows Security is whats actually blocking the dll to inject into the GW Client

**Comment by chichke** [comment]
Yup actually virus total tag is as a RAT ? Please I hope you're not trying to infect us your tool was great !

**Comment by reduf** [comment]
RAT is a "remote access" malware. What is your AV? Normally, AV companies with some decency offer a portal where you can submit false positive and they will analyze/whitelist it. If you do so, make sure to also give the PDV (which is on Github) and the Github repo link.

**Comment by waldenpond1** [comment]
Figured it out. Thx
