### ISSUE TITLE
Make Toolbox easier to use

### ISSUE THREAD

**Issue by PostCrafter** [HasKha/GWToolboxpp#417]
Currently the "GWToolbox++ Release" button at the top of the website only allows to download the `GWToolbox.dll`.
The launcher is only mentioned in a small note, which is often missed, leaving new people puzzled on how to use Toolbox.

There are a few possible options to solve this:
- make the launcher the default download
- add "Launcher" as a button to the downloads in the header
- download the .dll and .exe together (archived or whatever)
- add more documentatio: "Getting Started" section or add an entry to the FAQ

**Comment by reduf** [comment]
I'm currently working on having a final launcher that will be in C++. It will be part of the project and named `GWToolbox`. I will rename the dll to `GWToolboxdll` and the overall thing will offer un-installation.

**Comment by 3vcloud** [comment]
My launcher didn't do any downloading or update checking at all; I packaged the dll with the exe every time, and the launcher would use the dll that was with it.

**Comment by HasKha** [comment]
I agree with this, the download button on the website used to point to the launcher, I'm not sure what happened there.

**Comment by 3vcloud** [comment]
Closing this; any bugs with the new launcher can be raised as separate issues, but the download button etc has been fixed
