### ISSUE TITLE
useskill command for heros

### ISSUE THREAD

**Issue by XC3S** [HasKha/GWToolboxpp#423]
It would be greate to have a **/useskill** command for heros.

**Comment by Bu11etmagnet** [comment]
`/heroskill` maybe ?

**Comment by PostCrafter** [comment]
I'm curious about the usecase for this.

**Comment by XC3S** [comment]
@PostCrafter I think some hero build would be more viable, like a full Dwayna Support hero in mass minion builds. Or a real E/MO bounder as a hero especially since Heroic Refrain allows to keep Ether Renewal up without a conset. Or something simple like putting "They're on Fire!" on a hero to keep echos up.

**Comment by PostCrafter** [comment]
Fair enough, but keep in mind that you can't use hero skills directly, you can only queue them up.

**Comment by HasKha** [comment]
In my opinion, this will work a lot worse than you think. If you keep queuing up low-cd skills the hero won't be able to move, and even for higher cd skills it'll stop to cast all the time. 

It could work in some cases with a lot of micro (you'll have to manually enable/disable this a lot). At that point, is it worth over microing skills directly?

**Comment by 3vcloud** [comment]
Wouldn't this just be the same as binding a key to one or more of these? If so, then its not needed in toolbox
![image](https://user-images.githubusercontent.com/10796356/81845490-8765c880-9548-11ea-9f7a-8bb628e143f4.png)

**Comment by PostCrafter** [comment]
I agree that adding useskill for heroes with the same functionally as the existing useskill wouldn't really do much.
The main issue with the inbuilt "Action: Order Hero X to use Skill Y" keybindings is that you can't use any of the modifier key (Ctrl, Shift, Alt, etc), so adding them to Toolbox in order to solve this would actually be of use.

**Comment by 3vcloud** [comment]
Not worth writing the code just to cater for modifier keys
