### ISSUE TITLE
Close Herobuilds and Builds menu when leaving the outpost

### ISSUE THREAD

**Issue by KartOMania** [HasKha/GWToolboxpp#432]
When leaving an outpost there is no need for builds anymore to be accessible. Maybe close the window or minimize it. Restore original state on reentry would be nice as well as an option.

**Comment by 3vcloud** [comment]
Good idea, added option to hide it when entering explorable area for next release, https://github.com/HasKha/GWToolboxpp/commit/533c0aa95b761952889acc63a523e5b9112b3ed7
