### ISSUE TITLE
"Hero Builds" Load does not load first heroes' build?

### ISSUE THREAD

**Issue by zemzelett** [HasKha/GWToolboxpp#433]
Hi there,

i grew to love the Hero Builds Window. But i had issues playing with my heroes lately and i figured it was because of one hero not having the right build.
I investigated a little further and found the following buggy behavior to be consistent:
* __The first hero build will never be loaded.__ That means, that hero is correctly put into the party, but has not the intended build load onto it.
* Loading builds individually works as intended. So it has to do with the loading of the whole Hero Teambuild only.
* All other builds are loaded correctly.
* If a player build is present or not, does not alter the result.

I looked into the code but could not figure out anything wrong. (Though C++ is not my domain)
The only thing i can imagine is a timing issue here maybe...

Can someone confirm my observation? Is this really a bug?

I'm running GWToolbox++ v3.42

**Comment by 3vcloud** [comment]
This has already been fixed and will be in the next release

**Comment by zemzelett** [comment]
Alright. Thanks for the info. And the great work you all do! :)
