### ISSUE TITLE
Add "scroll" icon beside Urgoz & Deep travel button

### ISSUE THREAD

**Issue by reduf** [HasKha/GWToolboxpp#434]
It would be a nice way to indicate a scroll is used for this teleportation, a bit like the UAC shield on button that require admin rights.

We can use the scroll icon, because we already have the ressource.

**Comment by 3vcloud** [comment]
https://github.com/HasKha/GWToolboxpp/commit/c6b8f37687461cefe8b596f8a34277567d9cf492
