### ISSUE TITLE
Hotkey to target pinged target other than last of whole party

### ISSUE THREAD

**Issue by HiImFlo** [HasKha/GWToolboxpp#435]
You can target the last pinged target among all party members via a GW native command (default: "T").

It would also be nice to have a hotkey to target the pinged target of:
a) the own character (helpful for splitting without interfering with others)
b) a specific party member by index (for more advanced spikes/splits)

I can see some broad use for a), while b) would be quite specific.

**Comment by Hour-of-the-Owl** [comment]
It would also be useful to have a hotkey that does the same as T but ignores targets that are out of compass range. Would that be simpler to implement?
