### ISSUE TITLE
ProcessExists check does not work in wine without workarounds

### ISSUE THREAD

**Issue by jnvsor** [HasKha/GWToolboxpp#437]
When playing GW on linux through wine (Or mac I presume) there are a few hurdles to jump over. The registry checks for vcrun and dx9 look in the wrong place depending on x86/x64. This isn't a problem since you can skip those checks. The real problem is AutoIt's `ProcessExists` function

```
[...]
remoteversion: 3.42
Displaying changelog.
format: . error: 0. extended: 0
do_update: False
One copy of GW detected. PID: 8
Error: Cannot find Guild Wars process
Flushing log, bye!
```

I presume autoIt is assuming such a low number is an error code instead of a proper process ID, but it is a proper process ID in an environment that's only running 7 processes :)

So I run `wine taskmgr` before GW and after all the service executables have run it puts the GW PID at 43 and hey presto it works.

So if you add another skip on the line 420 `If Not ProcessExists` check (But only if the PID has already been found) this will solve this issue in wine. I also hear you're making a new launcher, please keep this in mind when you're checking if the process exists. Thanks!

**Comment by 3vcloud** [comment]
Both launchers (AutoIt and C#) will be deprecated after the next release, and we'll be using a c++ one moving forward. I'll keep this open as a reminder to test this bug in the new launcher when its ready

**Comment by 3vcloud** [comment]
@jnvsor please download the launcher @ https://github.com/HasKha/GWToolboxpp/releases/download/3.5_Release/GWToolbox.exe and let me know how you get on

**Comment by jnvsor** [comment]
> GWToolbox doesn't seem to be installed

```
RegGetValueW failed: status:0x2
RegGetValueW failed: status:0x2
RegOpenKeyExW failed: status:0x2
CopyFileW failed (32)
CopyInstaller failed
Failed to install
```

With the new `/noinstall` flag (Both with and without a low PID)

```
RegGetValueW failed: status:0x2
RegGetValueW failed: status:0x2
RegOpenKeyExW failed: status:0x2
RegGetValueW failed: status:0x2
Couldn't read the key 'release' from GWToolbox settings
browser_download_url: 'https://github.com/HasKha/GWToolboxpp/releases/download/3.5_Release/GWToolbox.dll'
RegOpenKeyExW failed: status:0x2
OpenUninstallKey failed
Couldn't find installation path
InjectInstalledDllInProcess failed
```

Possibly of note: Wine's taskmgr crashed when the new launcher stopped.

Anyway, it still works with the 3.42 launcher, high PID, and 3.5 dll

**Comment by 3vcloud** [comment]
Try having `GWToolboxdll.dll` and `GWToolbox.exe` in the same folder, and provide the `/localdll` argument

**Comment by jnvsor** [comment]
With `/localdll` I get only the first 3 lines:

```
RegGetValueW failed: status:0x2
RegGetValueW failed: status:0x2
RegOpenKeyExW failed: status:0x2
```

After pressing launch nothing happens.

I tried `/noinstall` again and noticed I forgot a popup which runs after the `Couldn't find installation path` line:

> Couldn't find any appropriate target to start GWToolbox

**Comment by jnvsor** [comment]
Actually does work in 3.5+ launchers, but you have to remove the old one entirely, not just replace it. It will fail copying the file over itself during "Installation" and without installing the registry keys it will freak out when you try to use it normally
