### ISSUE TITLE
Trade window doesn't like font scaling above 1.0

### ISSUE THREAD

**Issue by Bu11etmagnet** [HasKha/GWToolboxpp#438]
With font scaling at 1.5, some text in the chat window is cut off:

![image](https://user-images.githubusercontent.com/7579651/83074852-29220500-a073-11ea-8f5e-a7d9215b178f.png)

**Comment by 3vcloud** [comment]
Thanks, https://github.com/HasKha/GWToolboxpp/commit/45a3f8e0d70cb89e06a98e3726cd66cdb2c7548a
