### ISSUE TITLE
Chat Command Hook Feature

### ISSUE THREAD

**Issue by Lukas-Eisele** [HasKha/GWToolboxpp#44]
A feature to hook up custom chat commands would be nice.
As an example: hooking commands to control teamspeak.
The commands would be defined in scripts or dlls and automatically loaded on toolbox start (as the standard toolbox commands are registered).

**Comment by HasKha** [comment]
I'm currently working on a big rewrite, where each toolbox component is separate and self-contained. After that, I'll try to detach those components into their own dlls that toolbox will load. Once that is done, you will be able to choose, create and share custom functionality for toolbox by using or creating a dll that uses gwca and imgui apis and implements the following interface (might change, but this is current idea):
-Update() // called every frame
-Draw(directx_device*) // render window, called if visible
-DrawSettings() // render its settings into the setting panel
-LoadSettings(inifile*) // load from ini
-SaveSettings(inifile*) // save to ini
and probably OnLoad and OnDestruct which correspond to the current constructor/destructor. 

You can take a peek on the rewrite on the imgui_rewrite branch, but keep in mind it's still early work.

So to answer your original question, if everything goes as planned, that (and much more) will be possible once I'm done with this work, which might take some time, of course, but I'm actively working on it.

**Comment by Lukas-Eisele** [comment]
thx for the info
