### ISSUE TITLE
GW crash when I enter new dungeon lv with toolbox active

### ISSUE THREAD

**Issue by MandruStack** [HasKha/GWToolboxpp#444]
![image](https://user-images.githubusercontent.com/55577013/83699318-fee8be00-a603-11ea-9e0e-532c7280140c.png)

Whenever I enter a new lv in a dungeon for any Eye of the north dungeon, game crash and I get the message above. Game works fine without toolbox and before the last update of toolbox

**Comment by PostCrafter** [comment]
Did you mean to close this? There is a known issue regarding Slaver's Exile, that will be fixed in the next release, but I wasn't able to reproduce the issue in Bogroots.
