### ISSUE TITLE
Toolbox does not respect resizing and snaps damage window back to unreadable size

### ISSUE THREAD

**Issue by Bu11etmagnet** [HasKha/GWToolboxpp#447]
I have Global Font Size at 1.5 because of high DPI monitor. This makes the damage monitor window hard to read:

![image](https://user-images.githubusercontent.com/7579651/83950339-52d4ec00-a82a-11ea-9f6a-6c13156aa187.png)

When I set "Unlock move all" and try to resize the damage window by dragging the bottom-right corner, it snaps back to its original (unreadable) size when I release the mouse button.

Other widgets like Timer, Clock, Vanquish counter don't exhibit this resistance to resizing.
This is toolbox v3.7

**Comment by 3vcloud** [comment]
![image](https://user-images.githubusercontent.com/10796356/83951358-d5f54280-a828-11ea-8527-d098d568a796.png)

**Comment by jnvsor** [comment]
@3vcloud Would it be an idea to roll that width into the width "size" option above?

**Comment by PostCrafter** [comment]
I agree that the Size inputs don't really make any sense when the actual size is determined by width and row height anyways.

**Comment by Bu11etmagnet** [comment]
Lock Size could be the culprit.

**Comment by 3vcloud** [comment]
Fixed in https://github.com/HasKha/GWToolboxpp/commit/5234f3d8934f716bc2e8728f1956a7ce6c1d2744 
 , size inputs were being displayed in error
