### ISSUE TITLE
Emotes dialogs

### ISSUE THREAD

**Issue by BearsMan** [HasKha/GWToolboxpp#448]
some dialogs like /sit do not trigger the dialog for [Character Name] sits but the dialogs for example on [Character Name] plays rock paper scissors do trigger in the emotes channel in-game it may be a bug I don't know here is the image with my character sitting in the guildhall when I used the emote which did not trigger the dialog once sat down

I know without Toolbox it triggers well

[https://i.imgur.com/JU0F2pJ.jpg](url)

**Comment by PostCrafter** [comment]
That's a Guild Wars thing, afaik using `/sit` never triggered the emote message.
