### ISSUE TITLE
Hide bonds widget when none available

### ISSUE THREAD

**Issue by jnvsor** [HasKha/GWToolboxpp#449]
An option to automatically hide the bonds widget when you don't have any bonds would be nice. As it stands it always takes up a minimum of 32 pixels width

**Comment by BearsMan** [comment]
u can hide it while in an outpost there is an option for it

**Comment by 3vcloud** [comment]
Fixed in https://github.com/HasKha/GWToolboxpp/commit/58a1e8381681609a24815395358c80bf33c24489
