### ISSUE TITLE
Option to sync minimap rotation

### ISSUE THREAD

**Issue by jnvsor** [HasKha/GWToolboxpp#450]
I have my TB and GW minimaps lined up to get the best of both worlds:

![image](https://user-images.githubusercontent.com/5260644/83963070-50fb3f00-a8a3-11ea-971e-ba0665d74bc9.png)

Unfortunately, because the guild wars minimap has a bit of acceleration, all the npc icons look blurry when turning (Because the underlying map is slightly off)

Can you add an option to either disable GW map's acceleration, or make the TB minimap use the same acceleration as the GW one?

**Comment by PostCrafter** [comment]
Duplicate of #87

**Comment by jnvsor** [comment]
Looks like you're right @PostCrafter I'll close this
