### ISSUE TITLE
Trade: Option to filter normal trade chat as well as kama ad1 trade chat

### ISSUE THREAD

**Issue by jnvsor** [HasKha/GWToolboxpp#454]
Currently you can filter the toolbox generated kamadan trade chat, but if you go to kamadan your trade chat will be flooded.

Toggling trade chat on and off all the time is a bit of a pain, so it would be nice if you could filter normal trade chat too

**Comment by 3vcloud** [comment]
pending next release https://github.com/HasKha/GWToolboxpp/commits/adb4522c082f15ad40627f996523916818736cf3
