### ISSUE TITLE
aggro radius

### ISSUE THREAD

**Issue by Hour-of-the-Owl** [HasKha/GWToolboxpp#456]
The actual radius of the aggro bubble is 1012 gwinches. Displaying it as 1010 is EXTREMELY DANGEROUS. I've uninstalled Toolbox to avoid any aggro mishaps in the future, but for the sake of the poor souls still using this cheat program, please fix the aggro bubble radius.

**Comment by 3vcloud** [comment]
Is this the same as earshot range?

**Comment by HasKha** [comment]
oh no 2 gwinches :(

**Comment by HasKha** [comment]
Anyway, for reference: http://wiki.fbgmguild.com/Ranges

We can change minor things (1010 -> 1012) as it won't really make a difference, but please think twice before changing anything major, it'll confuse people even if it's more correct.

Numbers in toolbox were our best guess when I first wrote it.

**Comment by Hour-of-the-Owl** [comment]
As you can see from that page, there are actually 2 different earshots with very slightly different radii. Guild Wars is stupid. Aggro bubble is the same as the larger one, so if you're in aggro range, you are definitely in earshot.

**Comment by 3vcloud** [comment]
Changed to 1012 in GWCA
