### ISSUE TITLE
Download of new version fails

### ISSUE THREAD

**Issue by DubbleClick** [HasKha/GWToolboxpp#457]
You forgot to include the gwtoolbox.dll (rather than only gwtoolboxdll.dll?) in the release. Not sure if that's the reason, but it fails with 0 bytes downloaded and throws a warning.

**Comment by 3vcloud** [comment]
hi, please use the current launcher from the GWToolbox website from now on, we won't be supporting the older versions

**Comment by DubbleClick** [comment]
Unfortunately the loader I just downloaded pops up with this notice:
![image](https://user-images.githubusercontent.com/7896469/85205544-410c4200-b31c-11ea-8385-9b984396bd8f.png)
And simply closes without doing anything upon clicking "Yes".

**Comment by 3vcloud** [comment]
I'll look into it, thanks for the heads up

**Comment by DubbleClick** [comment]
Debugging the installer code myself it's the file download that once again fails with a 0kb download size and a missing filename.

**Comment by DubbleClick** [comment]
Huh, it suddenly started working. Now TB injects successfully, but "cannot load font" and is invisible in the game.

**Comment by 3vcloud** [comment]
Sounds like you're having issues downloading resources from Github atm

**Comment by DubbleClick** [comment]
I suppose I'll delete the toolbox folder and attempt reinstalling with a VPN.

**Comment by DubbleClick** [comment]
Still the same issue about the font not loading.

**Comment by DubbleClick** [comment]
Turns out it downloaded everything but failed on the font install, even with the VPN. Manually downloading it fixed the issue.,
