### ISSUE TITLE
3.8.1 crashes the game upon termination

### ISSUE THREAD

**Issue by DubbleClick** [HasKha/GWToolboxpp#458]

**Comment by BearsMan** [comment]
are u on new launcher?

**Comment by 3vcloud** [comment]
1. Do you get a crash dialog?
2. Did it create a crash dump for you?
3. Does "termination" mean closing toolbox, or closing GW?

**Comment by DubbleClick** [comment]
@BearsMan new launcher, not like that matters since it happens after the launcher is long out of the question.

1. Crash dialog? No, it just freezes the game until windows says it's not responding anymore.
2. No crashdump.
3. Upon closing the TB main window.

**Comment by 3vcloud** [comment]
You able to take a screenshot of your UI before you close (and crash) the game?

**Comment by DubbleClick** [comment]
https://youtu.be/Xa1-h4MHR-8

**Comment by DubbleClick** [comment]
Some more information: fresh installations of TB, Windows v2004, also happening in a freshly installed VM. Not happening in the last TB release.

**Comment by 3vcloud** [comment]
Sick tunes bro, what do you mean by "last TB release" ? I did make changes recently to stop this freezing/crashing from happening, but you've said this is using version 3.8.1 which is the latest?

**Comment by Bu11etmagnet** [comment]
All I get is a "ding" when closing GW with TB active. Have to double-check if it happens with 3.8.1

**Comment by DubbleClick** [comment]
My last TB version was 3.7 I believe, but it might have been 3.8, it definitely wasn't happening with it however.

**Comment by DubbleClick** [comment]
Debugging showed that Resources::Terminate hangs at `worker.join();`.
Not entirely sure why, but rebuilding the solution and replacing gwtoolboxdll.dll with the recompiled one got rid of the issue. When I use the 3.8.1 release tagged one however, it still happens.

**Comment by 3vcloud** [comment]
Make sure you're recompiling the tagged 3.8.1 and not the latest commit on master to test

**Comment by DubbleClick** [comment]
Same still holds true.

**Comment by 3vcloud** [comment]
fixed https://github.com/HasKha/GWToolboxpp/commits/adb4522c082f15ad40627f996523916818736cf3
