### ISSUE TITLE
Bonds "Hide in outpost" checkbox does nothing

### ISSUE THREAD

**Issue by jnvsor** [HasKha/GWToolboxpp#459]
58a1e83 fixed the bonds window showing when no bonds were available, but the "Hide in outpost" checkbox is meaningless now since it doesn't show in an outpost anyway.

The easy fix is to remove the checkbox, otherwise show a "Dummy" window in outposts just for positioning

**Comment by 3vcloud** [comment]
this should still be relevant, have you tested this?

**Comment by jnvsor** [comment]
Yes. With bonds in the bar the bonds widget doesn't show in outposts whether it's on or off

**Comment by 3vcloud** [comment]
![image](https://user-images.githubusercontent.com/10796356/85231249-6d43c380-b3ed-11ea-8aff-f8dd91415b5b.png)

Tested; bonds widget showing when I have bonds on my bar, hidden when "hide in outpost" is ticked - can you attach a screenshot please?

**Comment by 3vcloud** [comment]
Looks like there is a bug that doesn't show it if you don't have any effects e.g. LB title on, will fix

**Comment by 3vcloud** [comment]
Fixed https://github.com/HasKha/GWToolboxpp/commit/1c527f3bbc7e1173279f0e69f559a0ec185a36fd
