### ISSUE TITLE
Syntax error messages for chat commands

### ISSUE THREAD

**Issue by DarkManic** [HasKha/GWToolboxpp#46]
Print out an error message and the right syntax for a specific chat command wich was used in a wrong way.

Example:
Player enters the following chat command: `/tp ae1 doa`
Toolbox gives out the following error message: `Syntax Error! /tp <town> [dis]`

**Comment by HasKha** [comment]
Most of those are already implemented, but chat commands are overall quite a mess right now. I'll need to do a pass on chat commands.

**Comment by 3vcloud** [comment]
`/tp` command refactored in 3.0 and docs updated @ http://www.gwtoolbox.com/travel#chat-commands
