### ISSUE TITLE
Crash immediately after character selection

### ISSUE THREAD

**Issue by findow123** [HasKha/GWToolboxpp#460]
The Crash happens immediately after character selection. Using Gw Launcher and version 3.8.1
crashes only for 1 alt account. 

![image](https://user-images.githubusercontent.com/67233809/85228697-41bcdb00-b3e5-11ea-8922-4b959c05a7b3.png)

crash dump:
[crash dump.txt](https://github.com/HasKha/GWToolboxpp/files/4809770/crash.dump.txt)

**Comment by 3vcloud** [comment]
Can you attach the file from `C:\Users\sang\AppData\Local\GWToolboxpp\crashes\3.8.1-20200621-174111-28048-11996.dmp` please?

**Comment by findow123** [comment]
Hi, I can't seem to attach dump files in github. Any other way to send the file?

**Comment by 3vcloud** [comment]
right click and zip it

**Comment by findow123** [comment]
[3.8.1-20200621-174111-28048-11996.zip](https://github.com/HasKha/GWToolboxpp/files/4810295/3.8.1-20200621-174111-28048-11996.zip)

**Comment by 3vcloud** [comment]
Fixed for next release https://github.com/HasKha/GWToolboxpp/commit/f15682ce8b61bb0a09e872d9ca458ef7ec55f785
