### ISSUE TITLE
View Shout upkeep on party members

### ISSUE THREAD

**Issue by MorbidlySoBeast** [HasKha/GWToolboxpp#473]
As per the title, it would be super handy if Shout upkeep was visible for each party member so that Heroic Refrain can more easily be maintained.

**Comment by PostCrafter** [comment]
The info for that is only available for yourself and your Heroes, adding Refrains to anybody else would purely be a guessing game so I didn't bother implementing that.

**Comment by reduf** [comment]
We won't do that for the reason mentioned by @PostCrafter.
