### ISSUE TITLE
Preserve tick status

### ISSUE THREAD

**Issue by DubbleClick** [HasKha/GWToolboxpp#477]
Should give users the option to retain their tick status between zoning into an instance and going into the outpost again.

**Comment by HasKha** [comment]
That would defeat the whole point of ticking. People would start saying "oh but toolbox ticked me, I wasn't ready" and then people would lose trust on the ticks.

**Comment by HasKha** [comment]
Also, duplicate of #135.

**Comment by DubbleClick** [comment]
That's why it should be an option. I specifically untick or tick if I'm there. It's very bothersome to continually tick whenever we leave an instance.

**Comment by DubbleClick** [comment]
Implemented a tick toggle in pr #474  because im lazy
