### ISSUE TITLE
Automated AFK status

### ISSUE THREAD

**Issue by DarkManic** [HasKha/GWToolboxpp#48]
Change the status to `away` if it was `online` after a certain time passed without any input to the game.
For example 10 minutes, this time should be adjustable in the settings.

Change the status back to `online` if it was `away` on any input to the game.

**Comment by Hour-of-the-Owl** [comment]
If you manually set to Away in order to hide from someone, would this then override that because you're still making inputs?

**Comment by DarkManic** [comment]
I think if you are trying to hide from someone you should set yourself to offline or disable this feature.

**Comment by Hour-of-the-Owl** [comment]
well you might still want to talk to someone else (so offline wouldn't work), and remember to disable could get annoying... it's still a great feature - just trying to think of ways to make it even better (=

**Comment by HasKha** [comment]
Can do, but this is the a classic tricky problem, made even harder by the fact that toolbox doesn't really know when you're changing your status manually. Best would probably be to make it optional and explain clearly what it does.

**Comment by HasKha** [comment]
done
