### ISSUE TITLE
Option to Untick/Tick Cinematic Start/End needs fixing

### ISSUE THREAD

**Issue by BearsMan** [HasKha/GWToolboxpp#489]
in-game the cinematic can be skipped via toolbox but in its game settings the checkbox for flashing in taskbar window the checkbox will still be enabled even if u turn the setting off and on from when u restart the game completely and start toolbox at any point 

there should an option to permanently allow u to turn it off and on again without the need to restart the client and toolbox

I will leave a screenshot here: [https://i.imgur.com/MPd12on.jpg](url)

**Comment by 3vcloud** [comment]
Fixed for next release, ta
