### ISSUE TITLE
Multi language support

### ISSUE THREAD

**Issue by DarkManic** [HasKha/GWToolboxpp#49]
As the title says, realisation via language files with strings.

**Comment by HasKha** [comment]
This would be great, but it's a major project.

**Comment by Hour-of-the-Owl** [comment]
Which part is major - the support, or the translation? The translation part can be completely outsourced to players who know nothing about coding, right?

**Comment by HasKha** [comment]
Correct, but support for translation is a lot of work, and then while it can be outsourced, I still have to manage it
