### ISSUE TITLE
"Load Team Hero Build"

### ISSUE THREAD

**Issue by Hour-of-the-Owl** [HasKha/GWToolboxpp#490]
Load Hero Team Build hotkeys are named "Load Team Hero Build `namehere`". "Team" and "Hero" should be switched.

**Comment by 3vcloud** [comment]
I want to deprecate a lot of these hotkeys now that we have chat commands for many of them; need to remove this hotkey option at load time, and re-create legacy hotkeys to be Sendchat hotkey `/heroteam <teambuild>`
