### ISSUE TITLE
Info Window for Managing Gold - Help Screen wordings are incorrect

### ISSUE THREAD

**Issue by BearsMan** [HasKha/GWToolboxpp#492]
the info window for managing gold - the help section found an incorrect spelling path shown here: [https://i.imgur.com/lAt4G4A.jpeg](url) - the word in help section is spelled automatcly <- when the correct spelling should be -> automatically

look very closely at the spelling and u will notice a mistake

**Comment by Hour-of-the-Owl** [comment]
As I told you, I've already fixed this. I'll make a PR for it soon.

**Comment by BearsMan** [comment]
ill close this since it is Merged from PR #494
