### ISSUE TITLE
Quoted Item tab in the Info window

### ISSUE THREAD

**Issue by Hour-of-the-Owl** [HasKha/GWToolboxpp#493]
Does this have any use for normal players? Anyway, there should be an option in Settings to not display this.

**Comment by jongarbott** [comment]
I'll disable this for release mode but keep it in debug, you're right theres not purpose to players

**Comment by 3vcloud** [comment]
Will remove in release mode

**Comment by 3vcloud** [comment]
https://github.com/HasKha/GWToolboxpp/commits/35725b8329bb5c81d7ae9f82a13252df5ce28cae
