### ISSUE TITLE
Enter Challenge hotkey disconnect

### ISSUE THREAD

**Issue by Hour-of-the-Owl** [HasKha/GWToolboxpp#495]
The `Enter Challenge` hotkey appears to cause a disconnect when used anywhere other than a Prophecies or Factions mission outpost.

Also, why does it say "Challenge" rather than "Mission"? Challenge missions are still missions - right now the wording is confusing.

**Comment by 3vcloud** [comment]
This hotkey should be merged with `/enter` command and logic applied there
