### ISSUE TITLE
player is not online

### ISSUE THREAD

**Issue by NG-Guildwars** [HasKha/GWToolboxpp#499]
Lets say that I want to PM some player called xxx. If he is not online I get the msg "Player xxx is not online."
But it is still possible that they are playing on other character, lets call the other character yyy. 
Is it possible to check if the player is online on other character and get the msg "Player xxx is now playing yyy"?
or even redirect the msg to the other character yyy?

**Comment by jongarbott** [comment]
This is already in toolbox, have you tested it?

**Comment by 3vcloud** [comment]
This is already in toolbox, have you tested it?

**Comment by NG-Guildwars** [comment]
Really? where do I find it?

**Comment by 3vcloud** [comment]
Its done automatically, have you tested it?

**Comment by NG-Guildwars** [comment]
Well, not working for me (v3.8.1)

**Comment by 3vcloud** [comment]
![image](https://user-images.githubusercontent.com/10796356/90227780-0818b700-de0d-11ea-923e-eb193fae3ce5.png)

If you're running 3.8.1 you should only see the "player is not online" message if that player isn't logged in at all

**Comment by 3vcloud** [comment]
Make sure you enable the "Friend List" feature in settings 
![image](https://user-images.githubusercontent.com/10796356/90228032-73fb1f80-de0d-11ea-8ae8-096e6f098d76.png)

**Comment by PostCrafter** [comment]
Keep in mind it only works for players that you have added to your friends list.

**Comment by NG-Guildwars** [comment]
> Make sure you enable the "Friend List" feature in settings
> ![image](https://user-images.githubusercontent.com/10796356/90228032-73fb1f80-de0d-11ea-8ae8-096e6f098d76.png)

it is already enabled for me

> Keep in mind it only works for players that you have added to your friends list.

trying to do it with my alt so added to fl

**Comment by NG-Guildwars** [comment]
Ok I figured it out.
TB should see the friend's character before and save it for future reference.

**Comment by jongarbott** [comment]
You need to see their character on the friend list, but you don't have to see them in-game on that character. If this isn't whats happening for you then its a bug

**Comment by NG-Guildwars** [comment]
try to add a new friend and right after that pm his other character, this the thing that is not working

**Comment by 3vcloud** [comment]
I think if you logged out then back in after adding it should trigger the code that registers it, so this is a bit of an edge case

**Comment by NG-Guildwars** [comment]
already tried to restart gw after adding and did not work

**Comment by Hour-of-the-Owl** [comment]
[I originally asked](https://github.com/HasKha/GWToolboxpp/issues/240) for a feature that redirects to the correct character even if you don't have them in your FL. I also outlined how I thought that could be done... is that not possible?

**Comment by DubbleClick** [comment]
I guess toolbox could only retrieve that information by temporarily adding them to friendlist.

**Comment by Hour-of-the-Owl** [comment]
That is indeed what I suggested.

**Comment by 3vcloud** [comment]
Whispering redirects for non friend list players is sorted, will need at least 1 slot in your FL for the check
