### ISSUE TITLE
option to not draw anything when player has M map open

### ISSUE THREAD

**Issue by DubbleClick** [HasKha/GWToolboxpp#503]

**Comment by DubbleClick** [comment]
https://github.com/DubbleClick/GWToolboxpp/commit/6268d6e3d888db7e3accd565986ded0e0edeb05c

**Comment by 3vcloud** [comment]
https://github.com/HasKha/GWToolboxpp/commits/2d1a8d4ca2a4f09629def4d524e819442264b5fb
