### ISSUE TITLE
Autoformat URLs in chat

### ISSUE THREAD

**Issue by DarkManic** [HasKha/GWToolboxpp#51]
Autoformat every URL in chat from `<url>` to `[<url>;xx]`.

**Comment by Hour-of-the-Owl** [comment]
this would be a rare occurrence, but what if adding those 5 characters brought it over the max message length?

**Comment by DarkManic** [comment]
Maybe Toolbox should just detect if there was an URL posted in the chat and do a sperate message with a clickable link.

**Comment by Hour-of-the-Owl** [comment]
that would not solve the problem of the URL not fitting in one message though? you want TB to go fetch a tinyurl? =P

**Comment by DarkManic** [comment]
No its only for urls already posted in chat wich are not formated in a build code to be clickable.

**Comment by Hour-of-the-Owl** [comment]
and instead send a message flaming the idiot who can't make shorter links? (=

**Comment by HasKha** [comment]
Before I can even think about implementing this feature, we need a much deeper understanding of and control over the chat system. Moreover, the risks involved in this feature out weight the benefits. Typing [ ctrl+c ;xx] is really not that bad.

**Comment by HasKha** [comment]
Added by @reduf, thanks!
