### ISSUE TITLE
custom agent "big circle" is filling with "target color"

### ISSUE THREAD

**Issue by GambitBandit** [HasKha/GWToolboxpp#510]
when you want to create a custom agent with shape=big circle in order to better see its range (like the built-in big circles for eoe, qz, winnow), then when you target it, its whole big circle becomes shaded with your target edge color (default yellow), and it becomes hard to see anything else in that big circle.

for the built-in big circles for eoe/qz/winnow, this doesn't happen. the only thing that changes to your target color is the edge of the actual small eoe/qz/winnow in the middle. is there a way to use this behavior for all custom big circles?

**Comment by 3vcloud** [comment]
Fixed for next release, ta
