### ISSUE TITLE
add which district info to friends list

### ISSUE THREAD

**Issue by GambitBandit** [HasKha/GWToolboxpp#514]

**Comment by 3vcloud** [comment]
The client doesn't have access to this information, so toolbox can't grab it :(

**Comment by GambitBandit** [comment]
Oh ok just wondering since discord has info

**Comment by 3vcloud** [comment]
Discord has info about your own character yeh, and maybe there might be a way of linking users in discord to their character names and then on to your friend list, but its a lot of code debt for something that would be a bit too flaky to be reliable
