### ISSUE TITLE
Salvaging rare crafting material into common material 

### ISSUE THREAD

**Issue by loorenzo** [HasKha/GWToolboxpp#519]
At the moment it is not possible to craft rare crafting material with the toolbox salvaging feature. For example, i want to salvage bolts of silk into dust or steel ingots into iron.

**Comment by 3vcloud** [comment]
![image](https://user-images.githubusercontent.com/10796356/92211462-6c68ec80-ee88-11ea-968f-536bd2adb0ec.png)
