### ISSUE TITLE
bond monitor registering others' bonds on yourself

### ISSUE THREAD

**Issue by GambitBandit** [HasKha/GWToolboxpp#524]
If you have bond x equipped and someone else casts x on you, the bond monitor shows like *you* are maintaining x on yourself.
x should only be on your own effects list, not bond monitor.

**Comment by 3vcloud** [comment]
which bonds would this apply to and in which situation would this be an issue?

**Comment by HasKha** [comment]
I noticed this too. When emoing in DoA, it shows the Life Bond on yourself that was casted by the monk. It's shaded a bit differently, but it's still weird and somewhat distracting.

**Comment by BearsMan** [comment]
I agree with @HasKha because it is quite annoying and the shading really got to me

**Comment by PostCrafter** [comment]
It's a side effect that was introduced by adding the refrains to the bond monitor. I didn't think it was a big issue when I found out a few weeks after the change so I didn't bother reporting it.
The different shading comes from the "Low Attributes Overlay", that was introduced in the same update, showing that it was casted with a lower attribute level than what you currently have in that attribute.

**Comment by GambitBandit** [comment]
It would be funny if you could click that bond to remove it on yourself. Then flame the emo for dropping bonds :>

**Comment by 3vcloud** [comment]
https://github.com/HasKha/GWToolboxpp/commits/bec544e78dfb6f67695c7b199aa9cfb0cdffdbdf
