### ISSUE TITLE
Crash when trying to travel to Embark Beach on lvl 4 Canthan character

### ISSUE THREAD

**Issue by kazerniel** [HasKha/GWToolboxpp#531]
For any other ineligible destinations it just gives the usual error message in chat without crashing.

(Reproduced it multiple times on the same character, but when I tried on another character, my lvl 10 Tyrian one managed to travel to Embark even though he's still in Ascalon and doesn't have access to the boat icon. I don't have any other characters that shouldn't be able to travel there, nor free slots to make another Canthan, so can't really test it further.)

GitHub doesn't let me upload dmp files, so I zipped them.

[3.8.1-20200922-022347-11124-6980.zip](https://github.com/HasKha/GWToolboxpp/files/5258830/3.8.1-20200922-022347-11124-6980.zip)

[3.8.1-20200922-022429-4400-11236.zip](https://github.com/HasKha/GWToolboxpp/files/5258832/3.8.1-20200922-022429-4400-11236.zip)

**Comment by jongarbott** [comment]
#426

**Comment by 3vcloud** [comment]
#426

**Comment by 3vcloud** [comment]
Fixed in dev https://github.com/HasKha/GWToolboxpp/commits/ea6da7876ff1261d0c8b62bcf5e194c5f68b0d70
