### ISSUE TITLE
Any way to add a hotkey to change hero combat mode?

### ISSUE THREAD

**Issue by kazerniel** [HasKha/GWToolboxpp#533]
It would be convenient if I didn't have to manually click on each hero panel to change their combat mode between Fight/Guard/Avoid Combat.

(I don't really need to set specific heroes, usually I want to change the whole party's combat mode.)

**Comment by 3vcloud** [comment]
Already pending next release https://github.com/HasKha/GWToolboxpp/commits/0f8595b1ab4e3aadf4eaf02fcb5c043748751cb5

**Comment by DubbleClick** [comment]
This was already added a while back. Chat command of /heroes attack or so

**Comment by kazerniel** [comment]
Thanks!
