### ISSUE TITLE
Trade window doesn't work, says "connection timed out"

### ISSUE THREAD

**Issue by Bu11etmagnet** [HasKha/GWToolboxpp#538]
![image](https://user-images.githubusercontent.com/7579651/94993453-65212580-0591-11eb-9ee1-cb81eeda4b30.png)

https://kamadan.gwtoolbox.com/ shows up correctly in  a browser

**Comment by BearsMan** [comment]
that has been fixed for next release if i am not mistaken

**Comment by Bu11etmagnet** [comment]
[citation needed]

**Comment by 3vcloud** [comment]
Should connect on 4.1
