### ISSUE TITLE
Show / hide Costume Headpiece

### ISSUE THREAD

**Issue by NG-GW** [HasKha/GWToolboxpp#539]
It will be great if we could hide / show the Costume Headpiece with tb. 
It will be useful when we want to switch the armor with hotkey but we want the Wicked Hat (or any other) to show too, because it works better with that outfit.

Edit: Same applies to show / hide the head armor.

**Comment by Hour-of-the-Owl** [comment]
This should also be possible for body costumes and capes.

**Comment by 3vcloud** [comment]
Pending 5.6 release

**Comment by 3vcloud** [comment]
Sorted 5.6
