### ISSUE TITLE
Enhance the /scwiki chat command

### ISSUE THREAD

**Issue by DarkManic** [HasKha/GWToolboxpp#54]
Add the ability to directly add a search querry to the chat command.

Example:
Player types in the chat: `/scwiki doa`
Browser opens: `http://wiki.fbgmguild.com/index.php?search=doa`

**Comment by reduf** [comment]
Added.
You can also write /scwiki city foundry veil to get `http://wiki.fbgmguild.com/index.php?search=city+foundry+veil`.
Like `/wiki` does in Gw.
