### ISSUE TITLE
Toolbox Main Window - Features Display Order

### ISSUE THREAD

**Issue by T0rv4ld** [HasKha/GWToolboxpp#542]
I noticed that in the main window of toolbox, the various features we decide to display show up in a pre-defined order, not taking into account the alphabetical order nor the order in which they are ticked. This makes it pretty hard to find a logic as, without one of those two rules, the new features will pop up randomly in between others. Here is an example:

I have in the example the following:
- Info (which I think should always be on top)
- Trade
- Daily Quests (no alphabetical order)

If I turn on a few other features, the following order appears:
- **Hero Builds**
- Info
- **Materials**
- Trade
- **Faction Leaderboard**
- Daily Quests

Which does not appear to show any category logic behind it (except maybe Materials and Trade).

Would it be possibly to classify those by alphabetical order (for ease of organization) or, even better/as a second option, in the order they are ticked on?

**Comment by 3vcloud** [comment]
Fixed in dev for next release, https://github.com/HasKha/GWToolboxpp/commits/cd60aa81c8a29bef092d75749d5932c9393b9227
