### ISSUE TITLE
Age2 bug?

### ISSUE THREAD

**Issue by kazerniel** [HasKha/GWToolboxpp#543]
Just got this:
![age2](https://user-images.githubusercontent.com/5689996/95791065-7d531c00-0cd8-11eb-9837-eb4435e0a030.jpg)
Out of the two the ingame value is correct.

**Comment by 3vcloud** [comment]
age2 is only accurate in explorable areas

**Comment by kazerniel** [comment]
I see, thanks!

**Comment by reduf** [comment]
Not even if we want to be very pendantic. `/age` returns the time you have been on the map, not the instance time. It's very obvious in the case where someone loads slowly, let's say 1 minute slower than someone else. Both will have different `/age`.
