### ISSUE TITLE
Added ignore list features

### ISSUE THREAD

**Issue by destroyhumns** [HasKha/GWToolboxpp#549]
Adding the ability to either take your existing ignore list or creating a new one on toolbox, then creating new features such as:

- Automatic declining of trade requests
- Automatic declining of party invites

Just two ideas off the top of my head, but maybe there could be some more features with this. 

Thanks for looking at my suggestion and taking the time to work on toolbox after all these years!

**Comment by Duckiesss** [comment]
Yes Please! This one guy in DOA spam invites everyone he can find... :(

**Comment by 3vcloud** [comment]
5.13

**Comment by Hour-of-the-Owl** [comment]
ideally these should also not flash the GW icon on the taskbar
