### ISSUE TITLE
Add an automated trade chat poster

### ISSUE THREAD

**Issue by DarkManic** [HasKha/GWToolboxpp#55]
Add the ability to setup a custom trade chat message wich will be automatically reposted in the trade chat.
Sidenote, set the repost timer high enough to prevent it from beeing used as a spam tool and also stop reposting the message after traveling.

**Comment by HasKha** [comment]
I am quite strongly against this. I don't like the gw trading system, and I dislike spam bots even more, so I wouldn't want toolbox to become one. 

If toolbox will ever help trading, it will be with an auction house, which is a related project we've been thinking about for a long time.
