### ISSUE TITLE
Dialog labels cut off when Global Font Scale > 1

### ISSUE THREAD

**Issue by Bu11etmagnet** [HasKha/GWToolboxpp#551]
This is the right edge of the "Hotkeys" window with Global Font Scale at 1.5:

![image](https://user-images.githubusercontent.com/7579651/97304186-ad172d80-185b-11eb-82c3-0601534aaa69.png)

This is the right edge of the "Hotkeys" window with Global Font Scale at 1.0:

![image](https://user-images.githubusercontent.com/7579651/97304485-1303b500-185c-11eb-8e02-93e6d04da402.png)

**Comment by 3vcloud** [comment]
https://github.com/HasKha/GWToolboxpp/commits/01b176da93233294cdfd244de2624aab15c397ea
