### ISSUE TITLE
chat command to reinvite target

### ISSUE THREAD

**Issue by Hour-of-the-Owl** [HasKha/GWToolboxpp#557]
`/reinvite` should kick the targeted player (or hero) and immediately add them back. If they're not currently in the party, just invite them.

**Comment by Hour-of-the-Owl** [comment]
If you're not party leader, this should first leave instead of kick.

**Comment by Hour-of-the-Owl** [comment]
If you target yourself, should this kick you from the party and re-invite the leader OR do nothing? I'm not sure how often people are going to target themselves (do people ever do that in an outpost?) and then accidentally hit their hotkey.

**Comment by 3vcloud** [comment]
Added in 4.4

**Comment by Hour-of-the-Owl** [comment]
> If they're not currently in the party, just invite them.

plz

**Comment by 3vcloud** [comment]
1. Will look into it
2. Target yourself and use the command

**Comment by Hour-of-the-Owl** [comment]
thank you <3
