### ISSUE TITLE
Update /transmo command list

### ISSUE THREAD

**Issue by Mr-HaXx** [HasKha/GWToolboxpp#562]
For fun, add this list to the ChatCommands.cpp

  npc_transmos = { 
        {"charr", {163, def_scale, 0x0004c409, 0, 98820}}, 
        {"reindeer", {5, def_scale, 277573, 277576, 32780}}, 
        {"gwenpre", {244, def_scale, 116377, 116759, 98820}}, 
        {"gwenchan", {245, def_scale, 116377, 283392, 98820}}, 
        {"eye", {0x1f4, def_scale, 0x9d07, 0, 0}},
        {"zhu", {298, def_scale, 170283, 170481, 98820}}, 
        {"kuunavang", {309, def_scale, 157438, 157527, 98820}}, 
        {"beetle", {329, def_scale, 207331, 279211, 98820}},     
        {"polar", {313, def_scale, 277551, 277556, 98820}},    
        {"celepig", {331, def_scale, 279205, 0, 0}},  
        {"mallyx", {315, def_scale, 243812, 0, 98820}},     
        {"bonedragon", {231, def_scale, 16768, 0, 0}},     
        {"destroyer", {312, def_scale, 285891, 285900, 98820}},   
        {"destroyer2", {146, def_scale, 285886, 285890, 32780}},    
        {"koss", {250, def_scale, 243282, 245053, 98820}},     
        {"smite", {346, def_scale, 129664, 0, 98820}}, 
        {"dorian", {8299, def_scale, 86510, 0, 98820}},         
        {"kanaxai", {317, def_scale, 184176, 185319, 98820}},         
        {"skeletonic", {359, def_scale, 52356, 0, 98820}},          
        {"moa", {504, def_scale, 16689, 0, 98820}},
        {"Dhuum", {344, def_scale, 353571, 353574, 98820}},
        {"Ghostly", {25, def_scale, 116228, 130109, 98820}},
        {"Amara", {3337, def_scale, 116225, 184958, 524}}, 
        {"Danika", {3477, def_scale, 116225, 184614, 540}},
        {"Attia", {3398, def_scale, 116225, 170391, 524}},
        {"Gita", {3482, def_scale, 16267, 185043, 540}},
        {"Hala", {3480, def_scale, 16257, 185038, 540}},
        {"Catrine", {3614, def_scale, 116225, 185129, 524}}, 
        {"Shadow", {8056, def_scale, 141311, 116800, 524}}, 
        {"Kormir", {4862, def_scale, 243500, 245317, 524}},
        {"Margonite", {5535, def_scale, 207524, 207872, 98820}},
        {"GreatDestroyer", {6081, def_scale, 312914, 0, 0}},
    };

**Comment by 3vcloud** [comment]
Won't add more stuff to the list of existing transmos, but would love it if a PR was made to have a toolbox user add or remove these themselves, perhaps by targetting an NPC to get the info
