### ISSUE TITLE
Option to disable materials salvage confirmation for rare drops

### ISSUE THREAD

**Issue by AnonymousII** [HasKha/GWToolboxpp#565]
Since one of the latest GW updates (not sure which particular one), when you use a cheap salvage kit (100 gold at merchant) on a rare drop (e.g. purple or gold salvage item like an armor) to get the materials only but not the mods, the GW client displays a confirmation request where you have to click "Yes" to get the materials. An option to disable this request would be great as you have to confirm it on each individual salvage action.
(Similar to the option to disable selling confirmation for goldies at the merchant)

**Comment by 3vcloud** [comment]
Hello poppet, won't be doing this - press "Y"
