### ISSUE TITLE
not showing/ font error

### ISSUE THREAD

**Issue by rupted** [HasKha/GWToolboxpp#567]
Since the pcon crash, ive updated to 4.6, tb runs and says its injected, but doesn't show menu or minimap. Hotkeys still work. Ive tried /tb reset and /show settings and different screen resolution settings, but still just says error: Cannot load font.

**Comment by 3vcloud** [comment]
Linked to #529 - delete Font.ttf from your gwtoolbox folder and re-run toolbox
