### ISSUE TITLE
[Feature-Request] Automaticaly load saved Build by entering PvE / PvP-Area

### ISSUE THREAD

**Issue by DasFragezeichen** [HasKha/GWToolboxpp#569]
If I play PvP I load an other build as in PvE. The problem is, that most time I forget to load the PvE build if I go back to PvE.

So it would be nice If toolbox recognizes If I enter an PvP Area or PvE area and automaticaly load an saved build. Is this possible?

**Comment by 3vcloud** [comment]
Fortunately there aren't many PvP outposts, so you can set a hotkey called `/load <build_code>` to trigger when you enter the outpost(s) you want via the options in the hotkeys window
