### ISSUE TITLE
Moving to material storage with ctrl+click does not work over 1 stack

### ISSUE THREAD

**Issue by ninjazzy** [HasKha/GWToolboxpp#572]
Even if you have purchased material storage expanders and have the room for the extra materials in mat storage, ctrl+click still deposits the material into the bank tabs ifyou have 250 or more of that material in material storage. If less than 250 of a material is in the mat storage and you ctrl+click a stack such that it will be over 250, it will deposit appropriately.

**Comment by 3vcloud** [comment]
The GW client doesn't know your max material storage, but if you have 251 of a material, toolbox will presume you can fit up to 500 of that item, then 501, 751 etc
