### ISSUE TITLE
move to trade bug

### ISSUE THREAD

**Issue by NG-Guildwars** [HasKha/GWToolboxpp#575]
I just noticed that you can double click to send items to trade window, awesome!

Anyways, there is a bug that you can also send items from xunlai chest by double click - but trade will be canceled.
Suggestions:
1) Disable this option to send items to trade windom from xunlai.
2) Maybe can automaticly send the item from the xunlai to the bags and after that add to trade window.

**Comment by 3vcloud** [comment]
Pending release, https://github.com/HasKha/GWToolboxpp/commits/3fe429364349c2239205398fd8fa1d6dd22c2ed3
