### ISSUE TITLE
add widget to show alcohol level 

### ISSUE THREAD

**Issue by HasKha** [HasKha/GWToolboxpp#58]
and maybe including a timer counting down

**Comment by ritlew** [comment]
im interesting in getting involved with this;

how would you do the timer? I've been able to dispaly the alcohol level but theres no place to access a timer (that i could find), would i have to track alcohol time myself?

**Comment by HasKha** [comment]
Yes, alcohol duration is not stored in the client so you'll need to have your own timer, which refreshes according to the post-processing effect packet.

**Comment by ritlew** [comment]
OK I have a working timer in place. I inserted it into the Pcons panel, where should it actually go?

![alc](https://cloud.githubusercontent.com/assets/16658359/26022603/86b995a6-3777-11e7-938a-e2d770948bf7.PNG)

**Comment by reduf** [comment]
Just as a question, do you support when someone use alcohol manually ?
For instance, 1m30 lasting then use 1 charge ~> 2m30, but how do you handle that ?
There is few other case that make alcohol timer annoying.

**Comment by ritlew** [comment]
According to the 2 tests I did, the game upgrades the timer to the next level, meaning:
1m30 (alcohol level 2) lasting then use 1 charge (to level 3) ~> 3m.
The alcohol level ticked down with the alcohol timer on time, which surprised me. If it didn't do this, I can't think of a way I would handle it without being overly complicated.

**Comment by reduf** [comment]
I just tried and if you use 1 charge at 0:00, then an other at 0:30, you will loose one level at 1:00.
That was what stop me when I wanted to do it, there is a lot of edge cases and only a little of accuracy.

Although, it can be a option that is interesting if the player doesn't use the alcohol manually which is probably the majority of the users.

**Comment by ritlew** [comment]
Testing it more, it does do what you describe, but the timer will auto correct itself when it jumps to the next level at least. I'll work on something to track this correctly.

However I would still like an answer to my original question of: where should the timer go?

**Comment by HasKha** [comment]
About display, I would make a widget similar to the health or distance, that says "alcohol" and the duration in mm:ss. You can start by copy-pasting one of those classes. Keep in mind you also need to add your class to ToolboxSettings to appear with the others.
