### ISSUE TITLE
Crash - Toolbox Crash as well as Guild Wars on occasion.

### ISSUE THREAD

**Issue by Toggsy** [HasKha/GWToolboxpp#580]
Hi all. 

I've been trying to get this to work - most of the time toolbox crashes though on occasion Guild Wars itself closes.
As requested by the app here is the crash file.

I wasn't doing anything in game and have actually never been able to open Toolbox (I crash immediately upon selecting a character from the toolbox menu). All files relevant to the app have been added to my antivirus exception list (including the toolbox dll) and I am running both in admin mode.

Thanks in advance! :) 

[4.8-20210323-175201-1452-7124.zip](https://github.com/HasKha/GWToolboxpp/files/6191808/4.8-20210323-175201-1452-7124.zip)

**Comment by 3vcloud** [comment]
@Toggsy please try with 4.9 and upload another dump and I'll check it out
