### ISSUE TITLE
Game freezes at loading screen after Zos Shivros failure

### ISSUE THREAD

**Issue by kazerniel** [HasKha/GWToolboxpp#584]
The game freezes on the loading screen back to the outpost.

Could reproduce it twice with TB, and didn't happen when I tried twice without.

**Comment by 3vcloud** [comment]
Before I check this one out, can you double check that you don't have any other plugins loaded e.g. umod?

**Comment by kazerniel** [comment]
uMod doesn't seem to affect it, it was running during both the TB freezing, and the non-TB non-freezing tests.

I can do a try without uMod but with TB.

**Comment by kazerniel** [comment]
Yes, it still freezes without uMod with TB.

**Comment by kazerniel** [comment]
Hmm today it froze without TB 🤔 Maybe it's unrelated then? If you fail while alt+tabbed out of GW?

**Comment by 3vcloud** [comment]
GW stops rendering when minimised, and Toolbox was built around the rendering loop. Leave the game minimised for long enough, and the rendering queue will grow too large to handle when restoring the window.

**Comment by kazerniel** [comment]
Does it count as minimising if you're alt-tabbing out in windowed full screen mode?

**Comment by 3vcloud** [comment]
You can always tell by checking the GPU load in task manager

**Comment by kazerniel** [comment]
It uses the GPU while alt tabbed, and only stops when I actually minimise GW via the top right corner.

**Comment by kazerniel** [comment]
Ok, mystery solved I think. I did a lot of quick tests with the window being active the whole time, and the game froze each time on wipe with or without either or both mods. (I even tried if there's a difference between min and max graphics settings.)

And it turns out that if I'm zoomed in to the maximum, the game freezes upon loading to the outpost even with the window being active, with or without mods, regardless of graphical settings. If I'm not zoomed in to the max, it doesn't freeze even with two mods running, and the game minimised to the taskbar (no GPU use).
