### ISSUE TITLE
Observer Mode: JSON export - Add guild name and/or guild tag

### ISSUE THREAD

**Issue by arka6594** [HasKha/GWToolboxpp#589]
I'm reading the code to have the guild name / and or guild tag in the JSON export. Would be nice to have it :)

_Originally posted by @arka6594 in https://github.com/HasKha/GWToolboxpp/pull/587#discussion_r615771532_

**Comment by arka6594** [comment]
The JSON export could be then structured like this: 

`{
   "parties":[
      {
         "guild_name": "Here the guild name",
         "guild_tag": "Here the guild tag",
         "members":[
            {
               "name":"A/E Player Name (1)",
               "party_id":1,
               "party_index":1,
               "primary":7,
               "profession":"A/E",
               "secondary":6,
               "skills":[
                  {
                     "name":"Conjure Flame"
                  },
                  {
                     "name":"Jagged Strike"
                  },
                  {
                     "name":"Critical Eye"
                  },
                  {
                     "name":"Critical Strike"
                  },
                  {
                     "name":"Way of the Assassin"
                  },
                  {
                     "name":"Golden Fang Strike"
                  },
                  {
                     "name":"Death Blossom (PvP)"
                  },
                  {
                     "name":"Wild Strike (PvP)"
                  }
               ],
               "stats":{
                  "cancelled_count":14,
                  "cancelled_skills_count":3,
                  "deaths":1,
                  "interrupted_count":0,
                  "interrupted_skills_count":0,
                  "kdr_str":"5.00",
                  "kills":5,
                  "knocked_down_count":2,
                  "knocked_down_duration":4.0,
                  "total_crits_dealt":116,
                  "total_crits_received":10,
                  "total_party_crits_dealt":77,
                  "total_party_crits_received":4
               }
            }
         ],
         "party_id":1,
         "stats":{
            "cancelled_count":109,
            "cancelled_skills_count":14,
            "deaths":4,
            "interrupted_count":9,
            "interrupted_skills_count":9,
            "kdr_str":"6.25",
            "kills":25,
            "knocked_down_count":10,
            "knocked_down_duration":10.0,
            "total_crits_dealt":209,
            "total_crits_received":26,
            "total_party_crits_dealt":147,
            "total_party_crits_received":15
         }
      }
   ],
   "version":"0.0"
}`

**Comment by NickGw99** [comment]
I'll have a look at this. Will also add the missing stats and info that's not currently taken into the JSON.
