### ISSUE TITLE
Marking which features and settings do/don't communicate with the server?

### ISSUE THREAD

**Issue by kazerniel** [HasKha/GWToolboxpp#591]
Related to the recent bans, I wonder if it would make sense to show on various windows which features/settings can ANet possibly detect server-side, meaning which could increase players' chances of getting banned? So that users can make a more informed decision on what features they use.

Sorry if a noob question :)

**Comment by 3vcloud** [comment]
Closing this because theres too much stuff to go through, and even if they were provided would not provide any more safety from getting banned as any of the other features of the program.
