### ISSUE TITLE
Crash after legacy update 4.10 

### ISSUE THREAD

**Issue by XenoDae** [HasKha/GWToolboxpp#592]
Ran toolbox and retrieved update. Still crashing. Cant upload crash file as the file is not supported.

![Crash](https://user-images.githubusercontent.com/83318248/116326204-1a5f3900-a781-11eb-8133-da95924742aa.PNG)

The first crash was right after update. The second were after the release of the hotfix.
[4.10-20210427-172647-33012-33656.zip](https://github.com/HasKha/GWToolboxpp/files/6388746/4.10-20210427-172647-33012-33656.zip)

**Comment by MortsNoteak** [comment]
Same here!

**Comment by BearsMan** [comment]
[Uploading 4.10-20210427-215556-21820-1744.dmp.zip…]()

**Comment by BearsMan** [comment]
@XenoDae u have to upload it as a zip file

**Comment by XenoDae** [comment]
> @XenoDae u have to upload it as a zip file

Thanks for that!

**Comment by 3vcloud** [comment]
Fixed 4.11
