### ISSUE TITLE
[Request] Option to Use German Wiki on Right Click in Inventory

### ISSUE THREAD

**Issue by SikroK** [HasKha/GWToolboxpp#595]
Hey, don't know if it's feasible and an easy change, but it would be cool if we could choose whether we want to go to the German or the English wiki using the wiki button in the inventory.
As of right now, playing the game in German, it looks for the German word on the English wiki, which obviously doesn't yield any results.

Thanks for the great tool.

**Comment by 3vcloud** [comment]
Good find - I'd normally say that because GW takes the user to the english wiki we should do the same, but searching for the german name is a bit weird - sorted for next release
