### ISSUE TITLE
Crash starting toolbox

### ISSUE THREAD

**Issue by JasperTheun** [HasKha/GWToolboxpp#597]
Hi,

I got a crash when I start toolbox in GW.

[Crash file.zip](https://github.com/HasKha/GWToolboxpp/files/6465761/Crash.file.zip)

**Comment by 3vcloud** [comment]
This looks like a corrupt font file; delete C:\Users\Bas\AooData\Local\GWToolboxpp\Font.ttf and relaunch toolbox and let me know if its fixed please

**Comment by JasperTheun** [comment]
Hi,

This solves the problem. Thank you for your help!
