### ISSUE TITLE
Failed to load d3dx9_xx.dll

### ISSUE THREAD

**Issue by justin-dx** [HasKha/GWToolboxpp#599]
I've installed the DirectX package, but it still isn't being picked up.
The dll exists in System32 and SysWOW64.
Any ideas?

**Comment by 3vcloud** [comment]
What is the exact name of the dll that is in your system32 folder?

**Comment by justin-dx** [comment]
d3dx9_43.dll

**Comment by 3vcloud** [comment]
If you haven't restarted since installing, restart your PC. Also try reinstalling it if that still doesnt solve the problem, it might be a corrupt dll

**Comment by justin-dx** [comment]
Still no good after a reboot, reinstall fixed it. Weird.
Thanks
