### ISSUE TITLE
Error: GWToolbox.dll was not loaded, unkown error

### ISSUE THREAD

**Issue by HasKha** [HasKha/GWToolboxpp#6]
Originally reported by: **Anonymous**

---

Hey, I get this error message when I launch the toolbox while GW is running. I am on Windows 10. I downloaded and installed  vcredist_x86.exe and DirectX Redistributable. I don't have any .dmp file in the %LOCALAPPDATA%/GWToolbox folder. I don't know what to do now..

---
- Bitbucket: https://bitbucket.org/ggori/gwtoolbox-plusplus/issue/6

**Comment by sfindow** [comment]
Hi,
I had the same Problem on my new Win 10 Notebook, but it fixed itself when i downloaded and ran the DirectX End-User Runtime Web Installer from the ms page. Hope this helps if it hasn't been fixed yet!

**Comment by reduf** [comment]
See FAQ and use new launcher.
