### ISSUE TITLE
collapse all

### ISSUE THREAD

**Issue by GambitBandit** [HasKha/GWToolboxpp#60]
The old tb would close all panels when the main tb window was minimized. Can there still be an option for this?

also disenchant spirit radar :P

thx!

**Comment by HasKha** [comment]
you can use `/hide all` 

disenchant spirit radar? Disenchant is a spirit and it's shown, but it doesn't make sense to show spirit range from it.

**Comment by GambitBandit** [comment]
Oh well it was just pretty nifty and intuitive to collapse all and re-expand with a single click instead of separate /hide and /show commands (and/or hotkeys)

Yup dissies are just regular red dots on the minimap, i was thinking about maybe a special colour circle for aggro range but then remembered elevation effects etc..however a special color dot for them would be neat!

**Comment by HasKha** [comment]
mhm, I understand. However, the new interface has a different workflow overall, and the windows are completely separated from the main 'toolbox' window, which is nothing more than a (optional) menu to open them.

That said, I understand that changing the user experience can be inconvenient. I personally believe the new way is better, but I will consider a compromise if I receive more similar feedback.

About disenchant, check #62 . I'll try to do it at some point in the future, but I cannot promise anything.
