### ISSUE TITLE
Hero flags improvements

### ISSUE THREAD

**Issue by HasKha** [HasKha/GWToolboxpp#61]
Bug fixes:
- Fix flags when managing more than 7 heroes (can happen in urgoz/deep)

There are several possible improvements in the hero flagging system:
- Improve symbols in the minimap: show the number of the hero and have a different symbol for All
- Change the mouse cursor while placing a hero flag
- Implement formations. Example: press a button (or drop-down?) which then sets all hero flags according to pre-determined rules (and show the new formation while placing them, maybe in a different color).
- Be able to place flags in the 3d world. This requires some reversing work to find either the "click on flag" or "click on world" functions.

**Comment by Hour-of-the-Owl** [comment]
is it out of the question to make henchies flaggable? They are very commonly used in HA

**Comment by HasKha** [comment]
you can flag them with the 'all' flag but not individually. That's not something we can add.

**Comment by daanvandenhoek** [comment]
I dont know if this helps with point 5 but found this in an old au3 clickpoint file. It uses the clicked position for cords:
```
Local $iCoordAddress = ScanForPtr($hGWProcess, "D8658485FFD9C0", -4)

Local $dCoordStruct = DllStructCreate("float ClickX;float ClickY")
Local $iStructSize = DllStructGetSize($dCoordStruct)
Local $iStructPtr = DllStructGetPtr($dCoordStruct)

DllCall($hKernel32, "int", "ReadProcessMemory", "int", $hGWProcess, "int", $iCoordAddress, "ptr", $iStructPtr, "int", $iStructSize, "int*", 0)
		$fClickX1 = DllStructGetData($dCoordStruct, "ClickX")
		$fClickY1 = DllStructGetData($dCoordStruct, "ClickY")
```

**Comment by 3vcloud** [comment]
All of the above sorted in 4.3 with exception of hero number on minimap
