### ISSUE TITLE
UseSkill doesn't work anymore :(

### ISSUE THREAD

**Issue by guesswhosback1** [HasKha/GWToolboxpp#610]
Hi there !
After version 4.7.1 the /useskill function doesn't work anymore, can you please bring it back , would be highly appreciated!

It was a nice acheivement to do a complete solo-duo FoW in HM with it, but now can't do it anymore :(

thank you HasKha !

**Comment by HasKha** [comment]
It was intentionally limited, see 4.8 patch notes https://github.com/HasKha/GWToolboxpp/releases/tag/4.8_Release
