### ISSUE TITLE
windows 10 not work

### ISSUE THREAD

**Issue by morteistantanea** [HasKha/GWToolboxpp#614]
i can download toolbox but when i start use not work  , were is when start in gw????

**Comment by BearsMan** [comment]
Did u see the shortcut on your Desktop after running GWToolbox.msi ?

**Comment by 3vcloud** [comment]
https://discord.com/channels/223619617048756224/572878219586306090/572878524092907529

**Comment by morteistantanea** [comment]
it work now , i download  direct x , my new pc no have before , tnk so much

Il giorno sab 26 giu 2021 alle ore 01:47 Darius Ronkowitz (Bears) <
***@***.***> ha scritto:
