### ISSUE TITLE
Label Tengu summons with their elite skill

### ISSUE THREAD

**Issue by HiImFlo** [HasKha/GWToolboxpp#618]
It would be great to know which Tengu you got from a summoning stone bwithout observing it using skills. I suggest adding the elite skill to the name of the angchus, so for example: Angchu Warrior [Hundred Blades] or Angchu Elementalist [Sandstorm]

List Ryn posted in the discord at some point (did not validate):
Global Const $ModelID_Angchu_W_Hundred_Blades      = 8994
Global Const $ModelID_Angchu_R_Broad_Head_Arrow    = 8995
Global Const $ModelID_Angchu_A_Palm_Strike         = 8996
Global Const $ModelID_Angchu_Mo_Life_Sheath        = 8997
Global Const $ModelID_Angchu_E_Lightning           = 8998
Global Const $ModelID_Angchu_Me_Fevered_Dreams     = 8999
Global Const $ModelID_Angchu_N_Spiteful_Spirit     = 9000
Global Const $ModelID_Angchu_Rt_Preservation       = 9001
Global Const $ModelID_Angchu_W_Primal_Rage         = 9002
Global Const $ModelID_Angchu_R_Glass_Arrows        = 9003
Global Const $ModelID_Angchu_A_Way_of_the_Assassin = 9004
Global Const $ModelID_Angchu_Mo_Peace_and_Harmony  = 9005
Global Const $ModelID_Angchu_E_Sandstorm           = 9006
Global Const $ModelID_Angchu_Me_Panic              = 9007
Global Const $ModelID_Angchu_N_Aura_of_the_Lich    = 9008
Global Const $ModelID_Angchu_Rt_Defiant_Was_Xinrae = 9009

**Comment by Hour-of-the-Owl** [comment]
The same would also be useful for Canthan Guards.  Do you have those IDs too?
