### ISSUE TITLE
TB crash on map load

### ISSUE THREAD

**Issue by HasKha** [HasKha/GWToolboxpp#623]
Never seen this one before. Link to pdb + dmp: https://1drv.ms/u/s!AicDyQVrn8hX2FTS19AdQHCTXiCx?e=R8FvXC

**Comment by 3vcloud** [comment]
From what I can see, this could well be an issue with your texmod d3d9.dll module causing headaches on device reset (and create)

**Comment by HasKha** [comment]
I don't use texmod :)

This is just kaos' launcher + toolbox + OBS recording

**Comment by 3vcloud** [comment]
The crash itself is within whatever d3d9.DLL you're running from the plugins folder on your machine, but I don't think its related to toolbox - the call stack just runs through the render loop before the crash every frame anyway. if its a common crash (which I think you've implied that its not ATM) I'd try removing the DLL from your plugins folder and try again to see if its an issue

**Comment by 3vcloud** [comment]
Sorted 5.6
