### ISSUE TITLE
Loading skillbars with factions pve skills

### ISSUE THREAD

**Issue by 3vcloud** [HasKha/GWToolboxpp#624]
If trying to load a skillbar with a kurzick or luxon skill and the player doesn't have the respective version unlocked, instead try to load the rival version of the skill.

If trying to load a skillbar with a kurzick or luxon skill and the player has both versions but a higher rank in the rival title, instead try to load the rival version of the skill.

**Comment by HiImFlo** [comment]
Could do the same for proph/factions duplicate skills if the bar contains only one of them. Most relevant ones are probably visage and desecrate/defile enchantments.

**Comment by RiftLurker** [comment]
[List of duplicate skills](https://wiki.guildwars.com/wiki/List_of_duplicate_skills)

**Comment by 3vcloud** [comment]
Sorted 5.6
