### ISSUE TITLE
Default agent name tag color

### ISSUE THREAD

**Issue by RiftLurker** [HasKha/GWToolboxpp#625]
This request came up on discord to help colorblind people to spot enemies more easily.

Toolbox should allow to change the default agent name tag color similar to how we allow to change the defaults for the minimap.
Additionally it might be worth looking into making the name tag background configurable to allow for more contrast.

**Comment by 3vcloud** [comment]
https://github.com/HasKha/GWToolboxpp/commit/13c1fa427f84360bc53ebbe930a35a620ffc726e
