### ISSUE TITLE
Pcons are getting refilled even though they're disabled in pcon window

### ISSUE THREAD

**Issue by RiftLurker** [HasKha/GWToolboxpp#628]
This means that I ended up with Pcons on storage characters and other characters that are not supposed to have them.

**Comment by UltraPower31** [comment]
Would be great if you could disable this Low on *pcon* message. I've set my thresholds to 250 to always have a stack of each pcon and my chat is spammed with this message every time I refill.

**Comment by RiftLurker** [comment]
@UltraPower31 Are you saying you get the message despite having enough items in storage to refill up to the desired threshold?
I too have all thresholds set to 250 and the message only displays when I don't have enough stock in my Xunlai Chest.

If the issue persists in 5.7 please open a separate issue, as this one was fixed in 5.7 (92be443).
