### ISSUE TITLE
Low on Pcon Message and /pcons refill doesn't work

### ISSUE THREAD

**Issue by UltraPower31** [HasKha/GWToolboxpp#632]
Every time Toolbox refills a pcon I get the "Low on pcon" message for every pcon refilled. Those new /pcons refill commands also don't work for me.

**Comment by 3vcloud** [comment]
You get a low on pcon message because you're low on pcons. The `/pcons refill` command will be sorted for next release

**Comment by UltraPower31** [comment]
OK, so I have my thresholds set to 250 to always have a stack of each pcon and it's a bit annoying if my chat is spammed with 6 messages every time I zone back to an outpost. Imho this message would make more sense if I see it when I'm running low on a certain pcon in my chest, not in my inventory.

**Comment by 3vcloud** [comment]
Can you show a screenshot of the messages in chat and your pcons window in the same image please?

**Comment by UltraPower31** [comment]
![image](https://user-images.githubusercontent.com/1564031/134597672-9ce1b3ac-bc54-425b-aa18-f2c933a8e6a2.png)

**Comment by 3vcloud** [comment]
Thanks, sorted for next release

**Comment by UltraPower31** [comment]
I tried out your patch and now I don't get the warning message anymore. But what happens now is that if you have pcons enabled and you enable previously disabled pcon, it doesn't get refilled and instead just the warning message is posted in chat.

**Comment by 3vcloud** [comment]
Thanks for the testing, sorted that bug too thanks
