### ISSUE TITLE
Crashes 5.10 Update 

### ISSUE THREAD

**Issue by BearsMan** [HasKha/GWToolboxpp#638]
[crashes.zip](https://github.com/HasKha/GWToolboxpp/files/7573092/crashes.zip)
All 3 Game Crashes happened when I was in a doa run 

if it doesn't need to be fixed then don't bother and just close it

**Comment by 3vcloud** [comment]
Not a toolbox crash

**Comment by BearsMan** [comment]
I found it on my side it was caused by having save data location on

**Comment by BearsMan** [comment]
Never mind but ok I still random crash without warnings or crash dialog pop ups
