### ISSUE TITLE
Crash 5.10 TB - DoA run - veil area - 6-0 done/Chest spawn

### ISSUE THREAD

**Issue by HaxZykox** [HasKha/GWToolboxpp#639]
Hello,

I got a crash in my DoA run after done 6-0 at veil with the new update from TB. We were 3 to crash in same time.

[5.10-20211119-232957-22508-21772.dmp.zip](https://github.com/HasKha/GWToolboxpp/files/7574204/5.10-20211119-232957-22508-21772.dmp.zip)

Hax

**Comment by BearsMan** [comment]
I happen to find my problem mine was related to having save data location on

**Comment by HaxZykox** [comment]
Why not, but i mean if any ppl has the same crash in same moment, it's no longer a problem after modifying with Toolbox isn't it?

**Comment by BearsMan** [comment]
Never mind but ok I still random crash without warnings or crash dialog pop ups

**Comment by 3vcloud** [comment]
Fixed 5.11
