### ISSUE TITLE
crash game

### ISSUE THREAD

**Issue by Lilian-Mahut** [HasKha/GWToolboxpp#640]
after update to 5.11 to fix 5.10 crash,
i have some crashes (closing brut game).
I remain available for any information

**Comment by BearsMan** [comment]
Was it unexpected close ?

**Comment by Lilian-Mahut** [comment]
yes and without message like in 5.10

**Comment by 3vcloud** [comment]
Hi, thanks for making an issue - can you give any more info on how you caused the crash?

**Comment by Lilian-Mahut** [comment]
after patch 5.10 with 5.11, the game suddenly closes without warning.
The last time was in soosc during a fight. After in fowsc during a run, sometimes map changing.
The players in the group always see me logged in and when I restart the game, gw sometimes (not always) reports an error code 007 and if I validate I go back to the outpost. Now I cut my connection to simulate a network failure, restart the game that can't connect, close the game again, restart my connection, and restart the game. With this (long) manipulation I manage (sometimes) to return to the game with a loss of connection reported to the players of the game.
PS: sorry for my rough English

**Comment by 3vcloud** [comment]
What language do you run the game in?

**Comment by Lilian-Mahut** [comment]
in french
is it better to start it in English?

**Comment by BearsMan** [comment]
I run mine in English but I don't think that matters no ?

**Comment by Lilian-Mahut** [comment]
i'm trying and i go back to you

**Comment by Lilian-Mahut** [comment]
same
1st crash today.
error message when reload game : disconnect

**Comment by Lilian-Mahut** [comment]
2nd crash today (without admin mode)
i copied details of the report
[crash_gw.txt](https://github.com/HasKha/GWToolboxpp/files/7589214/crash_gw.txt)

**Comment by AuraofMana** [comment]
I have the exact same issue. Crash as soon as I load in Toolbox. Exact same error as above.

**Comment by Lilian-Mahut** [comment]
i abandon, same crash.
i donwgrade to 5.09, last stable for me

**Comment by AuraofMana** [comment]
How do you downgrade?

**Comment by 3vcloud** [comment]
I've had a look at the above `gw_crash.txt` file, but without more info this bug I can't fix this - I need to know from each of you:

1. Language that you were playing with at the time (not sure if this is a factor yet)
2. Copy of ArenaNet.log in `Documents/Guild Wars` folder
3. Copy of your `%localappdata%/gwtoolboxpp/GWToolbox.ini` files
4. Copy of any `.dmp` files in `Documents/Guild Wars` folder
4. Copy of any `.dmp` files in `%localappdata%/gwtoolboxpp/crashes`

Its a good idea to send these files directly to me on Discord rather than on Github, but when I get them through I'll take another look

**Comment by AuraofMana** [comment]
I am happy to send them to you. I can't even upload the .ini file on here because GitHub flags it as "not supported". Which person are you on Discord? I'll DM you through there.

**Comment by 3vcloud** [comment]
Jon [SNOW]#1816

**Comment by 3vcloud** [comment]
Fixed 5.12
