### ISSUE TITLE
while loop

### ISSUE THREAD

**Issue by MiniTheBest** [HasKha/GWToolboxpp#642]
Hello,
Is it possible to implement a while loop in order to enter kama ae1 :)
Thanks

**Comment by BearsMan** [comment]
I was actually thinking the same thing I know loop may work but the function used to allow it might be a bit complexed

**Comment by 3vcloud** [comment]
Hi, this is a bit niche only to kamadan and only on events, with the added risk of your account possibly getting flagged. Functionally this would also be very annoying. Just use the chat history to resend /tp kama ae1 by using opening chat, key up, send when you get the error message.
