### ISSUE TITLE
Add material storage upgrade logic

### ISSUE THREAD

**Issue by Dinichou** [HasKha/GWToolboxpp#645]
So i recently bought a material storage upgrade to go from 250 to 500 max materials, and the right click "store all materials" only stacks up to 250 materials before sending them into main bank slots. I'd love to have an update on this since that's one of my favourite features !

**Comment by 3vcloud** [comment]
TB checks your materials pane to figure out your max storage - to do this, make sure you already have at least 251 of a material in storage, and it'll figure it out - https://github.com/HasKha/GWToolboxpp/blob/dde1f73fa956d1bd291c8ba0c6371926629a2c42/GWToolboxdll/Modules/InventoryManager.cpp#L55

**Comment by Dinichou** [comment]
Mmmh, then it might not be working properly, i tried with different materials, with both right click "store all materials" and ctrl-clicking, and materials won't be put into my material pane if it goes higher than 250 (even if i already have more than 250 in storage).
The materials end up on the bank slot that is currently opened, or worse if i'm on the material panel, it goes into my first bank slot.
The settings i'm using :  
move_item_on_ctrl_click = true
move_item_to_current_storage_pane = true
move_materials_to_current_storage_pane = false

**Comment by 3vcloud** [comment]
Cant duplicate this in my tests with the same settings; hit me up on discord and take a recording for me

**Comment by Dinichou** [comment]
I can't find you on discord, i'll leave a comment on the toolbox section so you can find me ! I'll put the video i made here too : https://youtu.be/vR0-5no0Fao
Thanks for the help :)

**Comment by Galygious** [comment]
can confirm i have also dealt with the same issue. it doesn't seem to attempt to try to put it in materials before just defaulting to putting it in regular storage.

**Comment by 3vcloud** [comment]
Yep, wasn't showing a bug for me because I've already fixed in pending release

**Comment by 3vcloud** [comment]
https://github.com/HasKha/GWToolboxpp/releases/tag/5.14_Release
