### ISSUE TITLE
Minimap : CLICKTHROUGH Evolution

### ISSUE THREAD

**Issue by HaxZykox** [HasKha/GWToolboxpp#649]
Hello everybody, I 've a question :D I'm using ToolBox 5.13 and i want to use my minimap in middle of my screen.

If i want to walk or run, i just want to click "BEHIND" my minimap without interaction with minimap but i want to target monsters in minimap with "CTRL" for example.
The option "CLICKTHROUGH" don't work as i want but i want click BEHIND my minimap to run/walk but i can't target monsters with CTRL.

HaxZykox.

**Comment by HaxZykox** [comment]
Anyone hot to treat this ticket please =D ? I saw 2/3 tickets about minimap in "Pending Release"

**Comment by DubbleClick** [comment]
picked it up, I'm checking for walk, run or target atm to still capture mouse inputs for those events even if click through is enabled

@3vcloud this can be default behaviour, right? I would assume everyone would still want to be able to target even with clickthrough enabled

**Comment by 3vcloud** [comment]
Yeh think default would be fine, targeting is defaulted to control anyway so it’s safe to assume players holding that key when clicking the map want to target

**Comment by DubbleClick** [comment]
can close with with the next release btw, I still added a commit for the behaviour in outposts
