### ISSUE TITLE
Hide builds in explorable will also hide in outpost

### ISSUE THREAD

**Issue by franneck94** [HasKha/GWToolboxpp#655]
Hi,

the setting "Hide Build windows when entering explorable area" for the BuildsWindow and the HeroBuildsWindow does not work properly.

Steps to reproduce the issue:

1. Tick the setting in an outpost
2. Enter an explorable => BuildWindow is not displayed which is correct at this moment
3. Leave the explorable and go back to an outpost => BuildWindow is still not displayed => Bug

I will do a PR for this.

Greetings.

**Comment by 3vcloud** [comment]
Sounds like its working perfectly to me

**Comment by franneck94** [comment]
So it is intended that the window will not displayed anymore after leaving the "first" outpost?

**Comment by 3vcloud** [comment]
Its intended to hide the window when you enter an explorable area, from what you've said that's exactly what it does

**Comment by franneck94** [comment]
I would expect to see the window again in the next outpost.

**Comment by 3vcloud** [comment]
OK, but that's not what this does - its meant to get rid of the chaff from drafting your team together once you're ready to play. If you want to show your builds window when entering an outpost just bind a hotkey to it
