### ISSUE TITLE
Right click to move camera broken

### ISSUE THREAD

**Issue by chypriote** [HasKha/GWToolboxpp#656]
Hello, I think the recent PR (#654) introduced a camera error, I am now unable to use right click to move the camera when building from dev.  
I tried building from master and did not reproduce the error, I also did not have that problem with previous builds on dev.

**Comment by 3vcloud** [comment]
Yep, turn it off in settings

**Comment by chypriote** [comment]
Got it wrong, PartyStatistics wasn't the problem, but [this commit](https://github.com/HasKha/GWToolboxpp/commit/d048811581e0cda866ad1420f9ef0e0bbbeb1307). I'm guessing that's the one you were talking about ?

**Comment by 3vcloud** [comment]
No it wasn't the PR, it was that commit yeh - turn it off in settings
