### ISSUE TITLE
New party statistics window crashes the game

### ISSUE THREAD

**Issue by HasKha** [HasKha/GWToolboxpp#658]
Repro steps: be in a party with other players, in an outpost. Open party statistics, expand another player (not your own).

**Comment by 3vcloud** [comment]
My fault for not testing the new module before merging it in

**Comment by DubbleClick** [comment]
@3vcloud this actually still crashes the game when I try to expand the section of a hero (I didn't try with non-heros)

**Comment by 3vcloud** [comment]
Just tried this without problems, can you retry?

**Comment by DubbleClick** [comment]
Still crashes, I will fix it later
