### ISSUE TITLE
windows 11 

### ISSUE THREAD

**Issue by RogueSpike** [HasKha/GWToolboxpp#660]
i recently installed windows 11 and i reinstalled gwtoolbox after not playing guildwars  for a while it seems to install and run but it wont appear in guildwars i was wondering if anyone had any suggestions on how to fix this issue

**Comment by etidahouse** [comment]
Hello,

You need to install directx in windows 11
Link : [https://www.microsoft.com/en-US/download/details.aspx?id=35](https://www.microsoft.com/en-US/download/details.aspx?id=35 )

After installation, this worked for me

Regards

**Comment by RogueSpike** [comment]
Hey thank you for the reply I figured it put but I appreciate it

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
