### ISSUE TITLE
Unable to open Reroll window on dev

### ISSUE THREAD

**Issue by chypriote** [HasKha/GWToolboxpp#667]
Hello, 
I've noticed a few weeks ago that opening the Reroll window would cause a crash of GWToolbox and the game. I first thought that was coming from my own devs, but after rebuilding from the up to date dev branch today, I am also reproducing this error, anytime I click on "Reroll" in the main window, toolbox+the game crash.

Crash dump file => https://we.tl/t-zHBYKtmXed

**Comment by 3vcloud** [comment]
Fixed on dev
