### ISSUE TITLE
Reapply appropriate Title command not applying Lightbringer in Yatendi Canyons

### ISSUE THREAD

**Issue by Janitsu** [HasKha/GWToolboxpp#672]
While using the "Reapply appropriate Title" command, it will not apply the title "Lightbringer" when available when zoning into Yatendi Canyons. It will also not apply any other title. Tested this by going out of Chantry of Secrets as well as trying to use the hotkey to apply it while in the area.

**Comment by 3vcloud** [comment]
https://github.com/HasKha/GWToolboxpp/commit/47b2a843805c5aa9141b8d26b33f66432b8b2d5d
