### ISSUE TITLE
[Enhancement Request] Add HotKey to turn sound on or off

### ISSUE THREAD

**Issue by Mike-Carton** [HasKha/GWToolboxpp#682]
Add a _toggle_ HotKey to turn sound on or off. This can mimic the effect of the following:

**ON Setting**
Press F11
Select "Sound" Tab
Move "Master Volume" slider all the way to the right

**OFF Setting**
Press F11
Select "Sound" Tab
Move "Master Volume" slider all the way to the left

**Good to have**
Remember the position of the "Master Volume" slider when switching from "ON" to "OFF"; when switching back from "OFF" to "ON", restore the previous position instead of just moving the slider all the way to the right.

**Comment by 3vcloud** [comment]
Chat commands e.g. `/volume 100` for master volume, `/volume effects 60` for effects volume

**Comment by 3vcloud** [comment]
https://github.com/HasKha/GWToolboxpp/commits/a74093e400b133fbbb2fb49c6a841340cd09aa60
