### ISSUE TITLE
Update ImGui to newest version

### ISSUE THREAD

**Issue by Zvendson** [HasKha/GWToolboxpp#684]
Can be found here:
https://github.com/ocornut/imgui

If possible, create also another TB branch where ImGui runs with docking.

**Comment by HasKha** [comment]
We need to be careful with the docking branch. I'm using it for other projects, and while it's great, the API is still evolving. It's not merged to main for a reason. For example, it may break or produce unexpected behaviors with toolbox widgets.

**Comment by BearsMan** [comment]
I will 100% agree with @HasKha here

**Comment by Zvendson** [comment]
I would already be satisfied if ImGui gets updated first.

As another enhancement: Instead of adding the docking in the main, you can also add a toolbox branch to include docking as well.
