### ISSUE TITLE
include a DLL_PROCESS_DETACH to deinitialize and destroy toolbox from other sources

### ISSUE THREAD

**Issue by Zvendson** [HasKha/GWToolboxpp#685]
https://github.com/HasKha/GWToolboxpp/blob/36a017dd073b05519213d4f79357f6a771b654d8/GWToolboxdll/main.cpp#L47

I want to be able to close toolbox from another module.
Shorthand: I wrote a base dll that always runs on gw startup and adds a bunch of base functions such as dynamically load and unload dlls.

**Comment by BearsMan** [comment]
Toolbox closes once hit the X in its own window so I think destorying it from other sources is a bad idea but thats just an opinion of mine

**Comment by Zvendson** [comment]
pressing the X does not trigger much: https://github.com/HasKha/GWToolboxpp/blob/master/GWToolboxdll/GWToolbox.h#L36
so implementing it shouldnt be hard.

There are several ways to solve that easily

**Comment by 3vcloud** [comment]
Avoid using `DllMain` for this, its too late in the cycle - exporting `Terminate` instead
