### ISSUE TITLE
Flash Guild Wars taskbar icon

### ISSUE THREAD

**Issue by UltraPower31** [HasKha/GWToolboxpp#686]
I really like the flash Guild Wars taskbar icon feature but it would be great if Guild Wars would not flash indefinitely but instead just glow orange after a few flashes, like discord for example.

**Comment by UltraPower31** [comment]
Thank you for trying to fix this. Unfortunately it still flashes indefinitely. But I saw that the same function FlashWindow() is in GameSettings.cpp as well.

**Comment by DubbleClick** [comment]
Pending release means that the issue has been fixed, but not yet released.

**Comment by UltraPower31** [comment]
I don't think I explained myself very well. I tested your fix and it doesn't work. But after applying your fix (flashInfo.uCount = 5) to the FlashWindow() function in GameSettings.cpp it did work. Since I'm only a scriptkiddie, I thought I let you know instead of trying to find out how to do a pull request.

**Comment by DubbleClick** [comment]
I#d missed that the first time around but got it covered in a subsequent commit. it will work in the release
