### ISSUE TITLE
Minimap - Custom circles colors

### ISSUE THREAD

**Issue by HaxZykox** [HasKha/GWToolboxpp#691]
Hello,

I'm creating a new ticket because i want to add custom circles with different colors on the minimap. Currently the circles remain white.

The objective is to be able to assist players or new players, for example at the DoA. For example, the location of SOH, EOE, etc. but I need to be able to put different colors to distinguish the roles.

HaxZykox.

**Comment by DubbleClick** [comment]
![image](https://user-images.githubusercontent.com/7896469/172865062-80779f26-c1fd-4fbb-925c-c21f0bbf93d8.png)

see #700
