### ISSUE TITLE
Hotkey Crashes In-Game

### ISSUE THREAD

**Issue by BearsMan** [HasKha/GWToolboxpp#698]
I believe my crashing and disconnect has to do with hot keys basically if I word this right whenever I press a hot key for say re apply title more than once or checks for ZM ZB and so on that if triggered too many times in my case it will close the game without a warning dialogue, I can make a video for you to see what is happening

**Comment by BearsMan** [comment]
[log.txt](https://github.com/HasKha/GWToolboxpp/files/8861993/log.txt)

**Comment by BearsMan** [comment]
[https://youtu.be/pYXjFncUD78](url)
[https://youtu.be/Rw5_S0QVBRw](url)

2 Videos to show proof I crash on Hotkeys I have and use for UA Res, Recall and Apply Title all on the same hot key in my case the middle scroll wheel

**Comment by BearsMan** [comment]
[https://www.twitch.tv/videos/1498277102](url)
[https://www.twitch.tv/videos/1498336302](url)

2 stream videos I did with some hotkeys disabled (Recall / UA etc

**Comment by 3vcloud** [comment]
Potentially caused by `WndProc` not being in the right place. Updated GWCA to `SendPacket` in the game loop.
