### ISSUE TITLE
CMake setup for hot reload

### ISSUE THREAD

**Issue by DubbleClick** [HasKha/GWToolboxpp#705]
Currently the solution produced by cmake is not hot reload compatible / not compiled with edit-and-continue. in the debug configuration I don't really know CMake well enough to tackle this and fall back to setting the necessary options time and time again.

**Comment by BearsMan** [comment]
if u are using VS2019 or earlier I believe Hot Reload will not work I know this because it was introduced during pre release of VS 2022 but I could be wrong

**Comment by DubbleClick** [comment]
#707
