### ISSUE TITLE
Messages from players on ignore still get through

### ISSUE THREAD

**Issue by halogod35** [HasKha/GWToolboxpp#708]
![Screenshot_9](https://user-images.githubusercontent.com/6503891/173207395-82736a71-b941-42ea-a427-acf3e733b14e.png)
![Screenshot_8](https://user-images.githubusercontent.com/6503891/173207323-c4266cce-4184-4cdf-9a5c-bafa33a92436.png)
Here is a screenshot demonstrating This Is Hex Mode on the ignore list, but is still shows up. (even with ctrl + spacebar commands)

GWToolbox Version: 5.14
Tested on: 

- Windows XP SP3
- Windows 8.1 Pro
- Windows 10 LTSC 1809

**Comment by DubbleClick** [comment]
#711 

Most of the time the game blocks the messages by itself though. Did you figure out a pattern to this? Either way, TB will make sure they're blocked now.

**Comment by halogod35** [comment]
I didn't realize it was a feature of GW. I ironically thought it was a GWToolbox feature that was starting to fail. 

I should report this to GW but I feel like you guys would fix the problem faster. I cannot seem to figure out when and where it starts and stops. I seems to be at random times. Other people seem to say the same thing about it being erratic.

**Comment by halogod35** [comment]
I've noticed that ignore works in towns and outposts but when you enter a completive mission, they show up through ignore.
