### ISSUE TITLE
Block experience pop-ups after killing enemies

### ISSUE THREAD

**Issue by Janitsu** [HasKha/GWToolboxpp#710]
An option to prevent the green text pop up upon gaining experience from killing enemies (or other sources). An example picture included. Reduces visual noise on the screen.

![Green experience pop up](https://user-images.githubusercontent.com/8763688/173242433-433a2fa3-2339-46a2-9633-61d22620a892.png)

**Comment by Hour-of-the-Owl** [comment]
this should also include the faction pop-ups
![image](https://user-images.githubusercontent.com/25005986/176949273-27adfe5b-9892-429f-bcb2-a6148ad69ed7.png)

**Comment by 3vcloud** [comment]
Looking at the gw code, turning this on when spiking could help with the lag when you kill multiple enemies on screen
