### ISSUE TITLE
effect durations messed up when moving between spirits

### ISSUE THREAD

**Issue by Hour-of-the-Owl** [HasKha/GWToolboxpp#717]
When you walk from within range of one spirit to a same one whose effect overlaps, the Effect Durations widget timer updates, but doesn't take both spirits into account, so it will often display the (incorrect) shorter duration. In this screenshot, you can see the EoE duration displayed as 24 seconds, even though the cooldown says I've just cast it, and I'm in range of both spirits:
![gw028](https://user-images.githubusercontent.com/25005986/176507966-f46baac6-8692-4fd3-a44c-6d191070f03d.jpg)
When you leave the range of one spirit but remain in range of the other, the spirit timer disappears completely, but the icon still appears on the GW effects monitor, so the timers will be displaced. In this screenshot, the EoE duration has disappeared, even though I'm obviously still in range, and the timers are displaced so the Windborne Speed timer appears on Air of Superiority, and the Air of Superiority timer appears on Call of the Eye:
![gw029](https://user-images.githubusercontent.com/25005986/176507987-6df0f57e-1faf-4165-8f33-2e6d12db550c.jpg)

**Comment by 3vcloud** [comment]
Will take a look, thanks

**Comment by 3vcloud** [comment]
https://github.com/HasKha/GWToolboxpp/commit/15931711c917e725e25b7d589f143074107b3718
