### ISSUE TITLE
Skillbar Effect Monitor doesnt show on certain attribute level

### ISSUE THREAD

**Issue by onochanx** [HasKha/GWToolboxpp#721]
"Effect Monitor" and "Paint skills according to effect duration" doesnt show if the skills governing attribute on activation is 7. 

Tested on different characters after a clean install with multiple, but not all schools and skills for ranks 0-19.
Skill "Intensity" at Sunspear Rank 7 works.

**Comment by RiftLurker** [comment]
Thank you for the report, it's already fixed in the next version (https://github.com/HasKha/GWToolboxpp/commit/4477008279918308cd9ba9d3a74c09ec1bfbc15f).
