### ISSUE TITLE
GWToolBox dosent launch after it asks for my character's name

### ISSUE THREAD

**Issue by greenbeetle420** [HasKha/GWToolboxpp#724]
I downloaded the latest version of ToolBox
After whitelisting it from my windows defender, c:/user:/appdata/local/gwtoolbox
and starting gwtoolbox.exe as admin ( and GW )
It opens itself and downloads, but after asking me on which character to open it on, it crashes. No error messages or nothing

**Comment by DubbleClick** [comment]
As listed in the troubleshooting options, install the directx end user runtime. 
https://www.microsoft.com/en-us/download/details.aspx?id=35

**Comment by greenbeetle420** [comment]
thanks !
