### ISSUE TITLE
age2 on age prints age2 first if used with GW::Chat::SendChat

### ISSUE THREAD

**Issue by DubbleClick** [HasKha/GWToolboxpp#734]
...but if you type in guild wars yourself, it prints after

I don't care whether it prints first or second, but it should be consistent

**Comment by 3vcloud** [comment]
Can't duplicate this problem using hotkey to send chat, can you confirm?

![image](https://user-images.githubusercontent.com/10796356/181454582-16d41151-2de6-402b-a127-1a5889e5c4e5.png)

**Comment by DubbleClick** [comment]
will try it with a hotkey later, but the on objective completion prints age2 first for me

**Comment by DubbleClick** [comment]
can confirm that with a hotkey it sends age followed by age2

**Comment by 3vcloud** [comment]
The only way this can happen is if you have auto age2 on age turned off

**Comment by DubbleClick** [comment]
> The only way this can happen is if you have auto age2 on age turned off

it's on the latest dev with both auto_age2_on_age and auto_age on completion turned on. I'll try to get another run completed with video using the new dev but it's tough to do runs when I can't talk to reapers to teleport.

**Comment by DubbleClick** [comment]
doesn't seem to happen anymore, at this point I'm not sure if I was high when I thought to have experienced this
