### ISSUE TITLE
[Bug] Dialogs window option checkbox in settings

### ISSUE THREAD

**Issue by DubbleClick** [HasKha/GWToolboxpp#741]
![image](https://user-images.githubusercontent.com/7896469/183299508-094518b0-82cd-4951-9f94-cd71358bcd16.png)

displays in a new line unlike all the other windows/widgets

**Comment by 3vcloud** [comment]
Checkbox is supposed to be visible without having to expand the setting aswell

**Comment by DubbleClick** [comment]
fixed in #752
