### ISSUE TITLE
[Feature request] Remove dead canthan summon from party

### ISSUE THREAD

**Issue by DubbleClick** [HasKha/GWToolboxpp#743]

**Comment by DubbleClick** [comment]
implemented in #744 

although I'm not yet sure If I wouldn't rather have it behave like other summons (leaving party as they despawn, could do that in the AgentRemove hook I think)

**Comment by RiftLurker** [comment]
I'd be perfectly fine with them just getting removed if they're dead and you're moving out of compass range.

**Comment by 3vcloud** [comment]
It’s not, you’d have to check every frame rather than having it event driven

**Comment by 3vcloud** [comment]
Ok I read your reply as implying that the agent remove packet wasn’t being received, good stuff!

**Comment by DubbleClick** [comment]
sorry, I meant they never despawn as long as you stay in range.

when you leave their range they trigger the AgentRemove hook... twice per agent

**Comment by DubbleClick** [comment]
implemented in 5.15
