### ISSUE TITLE
Minimap v5.15 - problems

### ISSUE THREAD

**Issue by HaxZykox** [HasKha/GWToolboxpp#746]
Hello everybody, 

Since 5.15, me and 2 guildmates have problem to show draw up on minimap, to select boo/rift from minimap and sometimes to target mobs but it's not always and we can't see the line for the SOH on minimap.

I did this ticket to see if it's only us or others players.

HaxZykox.

**Comment by 3vcloud** [comment]
Will look into map draw issue, thanks

**Comment by BearsMan** [comment]
the SoH marker is Definity broken
