### ISSUE TITLE
PartyStatistics Crash

### ISSUE THREAD

**Issue by franneck94** [HasKha/GWToolboxpp#763]
# Reproduce the crash

Being with at least one other real player in the party.
The other player has cast exactly one single skill in your range.
Opening the collapsing header for that player, the game will crash.
There is an assertion error inside the imgui Columns API.
Seems like having only a single column is the problem.

# Solution

Since we are using now a newer ImGui version we can use the tables API instead of the columns API.

I will do a PR for this.

**Comment by DubbleClick** [comment]
good idea, the columns API will likely be deprecated at some point
