### ISSUE TITLE
Closing gw with debug version injected leads to exception with abort/retry window

### ISSUE THREAD

**Issue by DubbleClick** [HasKha/GWToolboxpp#764]
low priority, but rather annoying

**Comment by DubbleClick** [comment]
Crashes with alt + f4 / taskbar close are fixed, little x in guild wars itself left to go

**Comment by 3vcloud** [comment]
still an issue?

**Comment by DubbleClick** [comment]
yes, clicking on the X in guild wars doesn't trigger the WM_CLOSE/SC_CLOSE WndProc

**Comment by 3vcloud** [comment]
https://github.com/HasKha/GWToolboxpp/commit/5f020ae5dae30e7bea2323aecb52f1d4e7291cf8
