### ISSUE TITLE
When a cutscene plays it freezes 

### ISSUE THREAD

**Issue by w-smith24** [HasKha/GWToolboxpp#767]
The game freezes when a cutscene plays and makes you exit the client.  This happens in every campaign.

**Comment by 3vcloud** [comment]
This is likely due to a hotkey being triggered on map load. Please send me your gwtoolbox.ini file privately on discord

**Comment by w-smith24** [comment]
What's your discord username?

**Comment by 3vcloud** [comment]
Jon [SNOW]#1816

**Comment by 3vcloud** [comment]
After debugging, may be an issue with umod/gwlauncher, works when using toolbox without these extras

**Comment by dragonofmercy** [comment]
Same problem, I've tested without gwlauncher it crash everytimes while the video is fading, I can try it at Boreas Seabed while talking to Elder Rhea to watch the intro video

**Comment by truekenny** [comment]
Using the same config, the game freezes with cutscenes with version 5.16, but does not freeze with version 5.14

**Comment by truekenny** [comment]
5.15 also freezes

**Comment by truekenny** [comment]
After a month of playing for version 6.0, there was not a single freeze.
