### ISSUE TITLE
Incorrect display of cyrillic

### ISSUE THREAD

**Issue by truekenny** [HasKha/GWToolboxpp#773]
Some skills in russian localization are translated, their names contain cyrillic.

![Снимок экрана 2022-08-24 114533](https://user-images.githubusercontent.com/3448197/186374292-e102d307-4941-4692-83d0-6170b53548bb.png)

**Comment by 3vcloud** [comment]
1. Go to toolbox settings > Open Settings Folder
2. Download https://github.com/HasKha/GWToolboxpp/raw/dev/resources/Font_Cyrillic.ttf and put into this folder
3. Restart toolbox
![image](https://user-images.githubusercontent.com/10796356/186399861-dd64e62e-debd-448e-a665-c95128583b8f.png)


Let me know if this sorts it

**Comment by truekenny** [comment]
Thanks a lot, problem solved.

![Снимок экрана 2022-08-24 141304](https://user-images.githubusercontent.com/3448197/186404933-5ccf33fd-2488-4f01-9b62-a3006334aa62.png)
