### ISSUE TITLE
installer fails to install dx end user run

### ISSUE THREAD

**Issue by DubbleClick** [HasKha/GWToolboxpp#777]
related to #758 

installs vcredist but never dx end user rubtimes which have to be installed manually

**Comment by 3vcloud** [comment]
I modified the wix the other day

**Comment by 3vcloud** [comment]
Oh the other thing is that gwtoolbox no longer ships with the dx dependency so the message pop up asking them to install it works again

**Comment by DubbleClick** [comment]
see #758 too

**Comment by DubbleClick** [comment]
no longer relevant as we got rid of the d3dx dependency
