### ISSUE TITLE
Crash on map change or cutscene in Eye of the North only

### ISSUE THREAD

**Issue by DavyRoodenburg** [HasKha/GWToolboxpp#778]
Hello,
Since the 5.15 update, I experience routine crashes when changing maps in Eye of the North.
No obvious pattern except it occurring in Eye of the North only.
The crash is basically just the screen freezing and asking if I want to wait or close, waiting for 2 hours had no effect.
I uninstalled and reinstalled toolbox, rebooted pc and all other standard step.

Any suggestions to take as this is an annoying effect but it doesn't seem to affect anyone else?

Thanks a lot!

**Comment by 3vcloud** [comment]
As a temporary workaround, disable the effect monitor plug-in on toolbox settings, save and then restart toolbox. Let me know if after disabling it you have issues

**Comment by DavyRoodenburg** [comment]
Hello Jon,

Thanks, that worked (so far). Knock on wood it keeps up.

Full EotN HM without a single crash.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by DavyRoodenburg** [comment]
Hello Jon,

Spoken too soon, crashed on second level of Destruction’s Depths.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: Davy ***@***.***>
Sent: Friday, 26 August 2022 11:06
To: ***@***.***>; ***@***.***>
Cc: ***@***.***>
Subject: RE: [HasKha/GWToolboxpp] Crash on map change or cutscene in Eye of the North only (Issue #778)

Hello Jon,

Thanks, that worked (so far). Knock on wood it keeps up.

Full EotN HM without a single crash.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by 3vcloud** [comment]
Ok, send me your gwtoolbox ini on discord ( Jon snow)

**Comment by BearsMan** [comment]
I know this is pending but other people besides me had crashes in Embark even without Toolbox a few weeks ago while using 5.15 as I remember we can only think its client related but I could be wrong
