### ISSUE TITLE
Loading Skill Bars

### ISSUE THREAD

**Issue by BearsMan** [HasKha/GWToolboxpp#779]
https://i.imgur.com/0SqTyy1.jpeg

if u look closely at the middle screen u will see that the ritualist bar I am loading for Urgoz does not load every single skill on the skill template instead it swaps it to Mesmer skills, I even tried loading the skill bar template using (K) Load Skill Bar with vanilla version as if lets say I did not have toolbox on and it still loaded that way for me

possibility to fix ?

**Comment by 3vcloud** [comment]
Not with a screenshot that small

**Comment by BearsMan** [comment]
https://i.imgur.com/8I6qXqk.jpeg

@3vcloud  here I replaced the old screenshot so its sent from my main display

**Comment by 3vcloud** [comment]
What is the build code?

**Comment by BearsMan** [comment]
OAKkYphkITe0A41U5kPIGDdJ0xFD

@3vcloud
