### ISSUE TITLE
Automated /stuck sending

### ISSUE THREAD

**Issue by DarkManic** [HasKha/GWToolboxpp#78]
Add an option to automatically send the /stuck command every X seconds, this interval time should be customisable. Reason for this is to improve the bad guild wars netcode and high latencies. Sometimes you don't know you are stuck and than it's to late to unstuck.

**Comment by HasKha** [comment]
This won't work. In order to be somewhat useful you need to spam /stuck so much that you'll get message suppressed. If you only spam it 1 or 2 times per second it's useless. Learn to watch the enemies to see when you get stuck :)
