### ISSUE TITLE
Lockpick use range short

### ISSUE THREAD

**Issue by K4tana** [HasKha/GWToolboxpp#790]
Previously, I could use lockpicks across any distance with my hotkey. Now i practically have to stand next to the chest to open it - which kinda defeats the purpose of the hotkey imho. Is it bugged? I have no idea why this was killed.

**Comment by gladiatordan** [comment]
It’s been alleged for a while that some types of direct-packet sends (dialogs, interacts, etc) which circumvent client UI mechanics are flagging accounts for suspicious behavior. In response to that, Jon and friends have been slowly migrating toward more UI interaction. So you won’t be able to open locked chests from compass range anymore. 

This was one of the features impacted by the latest builds. You can read up on it more in TB discord as it’s been discussed many times over the last few years.

**Comment by K4tana** [comment]
Ok that seems fair. However, I would suggest to build this as the default with an option to revert back to the old settings. This serves as a secure basis that some people can change at their own risk.

**Comment by 3vcloud** [comment]
This won't be coming back to toolbox
