### ISSUE TITLE
Pcons

### ISSUE THREAD

**Issue by HasKha** [HasKha/GWToolboxpp#8]
Originally reported by: **Anonymous**

---

Toolbox keeps spamming with my pcons, even if they are up.

---
- Bitbucket: https://bitbucket.org/ggori/gwtoolbox-plusplus/issue/8

**Comment by sfindow** [comment]
hello,  i encountered the same problem today, when suddenly toolbox started to spam through cons+pcons. Everything was fine before. I vqd an area totally fine but it started spamming when i rezoned in another area. 

Spammed pcons were: full consets, pumpkin pie, cupcakes, golden eggs, candy corn, red rocks, war supplies, alc...so actually everything :)

**Comment by HasKha** [comment]
> Spammed pcons were: full consets, pumpkin pie, cupcakes, golden eggs, candy corn, red rocks, war supplies, alc...so actually everything :)

were they all ticked?

**Comment by sfindow** [comment]
yes they were all ticked and pcons enabled.

**Comment by HasKha** [comment]
I'm going to close this since we haven't seen this issue in a long time. I could never reproduce it thought, so it might still be around.
