### ISSUE TITLE
Zipped file from recent 6.0 crashes (On Startup)

### ISSUE THREAD

**Issue by BearsMan** [HasKha/GWToolboxpp#805]
[crashes.zip](https://github.com/HasKha/GWToolboxpp/files/9649871/crashes.zip)

**Comment by BearsMan** [comment]
I also forgot to mention that whenever I log out to character select screen, the game freezes.

**Comment by 3vcloud** [comment]
https://github.com/HasKha/GWToolboxpp/commit/a6013079643fb42f8264e9465ce26bf78c4369e3
