### ISSUE TITLE
Minimap Lag when placing SoH

### ISSUE THREAD

**Issue by Zane1-2** [HasKha/GWToolboxpp#806]
After placing SoH it takes 0.5-1 sec for the marker to appear on the minimap. My ping is the same as always and I've specifically only encountered this on 6.0 seems fine on previous versions. Not consistent unfortunately but will try to get a video at some point. Has never happened on any previous tb version.

**Comment by BearsMan** [comment]
https://youtu.be/rF4_aeIGZwY

Here is a video I put together, regarding the little bit of lags and general, and with Shadow Of Haste being casted etc.

**Comment by BearsMan** [comment]
@3vcloud any news on this bug being fixed yet? Was just wondering?

**Comment by 3vcloud** [comment]
Related to https://github.com/HasKha/GWToolboxpp/issues/851
