### ISSUE TITLE
Custom Items in Pcon Window

### ISSUE THREAD

**Issue by Zane1-2** [HasKha/GWToolboxpp#810]
Allow users to add custom items to be shown in the Pcons Window.
Possible to just add items by ModelID?

**Comment by 3vcloud** [comment]
No, different items mean different things and have different behaviours and quantities. Think about your use case and consider instead whether we need to think about a `/withdraw [item_model_id] [quantity]` chat command

**Comment by 3vcloud** [comment]
https://github.com/HasKha/GWToolboxpp/issues/813
