### ISSUE TITLE
`/withdraw [model_id] [quantity]` chat command

### ISSUE THREAD

**Issue by 3vcloud** [HasKha/GWToolboxpp#813]
This chat command should count what is in inventory already i.e. if you already have 20 and you `/withdraw` 50, it'll only take 30 out of storage

**Comment by DubbleClick** [comment]
I'll make this `/withdraw quantity model_id1 model_id2 ...` instead as it allows to manage multiple items at once

**Comment by 3vcloud** [comment]
No, make a hotkey that does multiple commands

**Comment by DubbleClick** [comment]
oh, didn't see that until now - should we really introduce a rather situational hotkey to write multiple strings into chat?

**Comment by DubbleClick** [comment]
either way, the chat command should be trivial to refactor as the code is in InventoryManager so we can rename or change arguments easily

**Comment by 3vcloud** [comment]
Adding a variadic number of model ids means that it would be difficult to modify this command later to add more functionality, for example adding an extra arg to tell the system whether to warn the user if they dont have many left.

**Comment by DubbleClick** [comment]
I agree, but limiting it to only 1 argument will make usage extremely tedious. I don't think adding a special kind of hotkey just to make this usable is over the top, just using "Send Chat" command is enough

**Comment by DubbleClick** [comment]
note that extra arguments could still be added to the end if they aren't purely numeric, so passing something like "warn" at the end would still work

**Comment by HiImFlo** [comment]
Why not allow optional parameters that can be passed explicitely?

/withdraw modelid1 //implicitely assume quanitiy=250
/withdraw modelid1 quantity=50
/withdraw model_id_list=[modelid1,modelid2] quantity=50

**Comment by DubbleClick** [comment]
I've considered doing an input list but decided against it because we don't use that anywhere else. I've implemented the logic behind it in a generic enough way that Jon can change the chat command to his liking when he comes back. Could maybe make the command I created named /multirefill or something
