### ISSUE TITLE
Hide Character Names On-Screen Checkbox Will Not Stayed Checked Unless Clicked In Game (Does Not Save After Logging Back In

### ISSUE THREAD

**Issue by BearsMan** [HasKha/GWToolboxpp#821]
https://gyazo.com/20a50f1d4046640bb01e7c934b456ebc
https://i.imgur.com/0X3VG9F.jpeg
https://i.imgur.com/CvLNwUl.jpeg

If you look at the screen's I have provided usually the box for it is unchecked, if checked and you zone into a new map it will be checked. It could be worth looking into but just in case if not I will add issue here for you to have a look.

**Comment by DubbleClick** [comment]
[754036b](https://github.com/HasKha/GWToolboxpp/pull/817/commits/754036b29e9d446270d1d20753ae230ccfb3f360)

fixes the saving/loading issue but on first login nothing is obfuscated yet, only after the first map change
