### ISSUE TITLE
Obfuscator problems

### ISSUE THREAD

**Issue by DubbleClick** [HasKha/GWToolboxpp#822]
- when it's enabled at guild wars launch, freezes game at character select screen
- shows obfuscated mercenary names in add dialog, but normal name when added to party
![image](https://user-images.githubusercontent.com/7896469/194269229-4b65999b-a70c-4026-a723-0f40b51603e5.png)
![image](https://user-images.githubusercontent.com/7896469/194269529-9347daed-0f0e-48d7-80cb-877d25ccc585.png)
- shows unobfuscated name in guild hover 
![image](https://user-images.githubusercontent.com/7896469/194269856-e225286f-28b7-420e-b22d-a1dfd2a55478.png)

**Comment by 3vcloud** [comment]
Will sort, ta

**Comment by 3vcloud** [comment]
https://github.com/HasKha/GWToolboxpp/commit/478d21726910fa483b11bf05c19bb598784472d0
