### ISSUE TITLE
Crash when trying to talk to any NPC

### ISSUE THREAD

**Issue by BearsMan** [HasKha/GWToolboxpp#824]
[6.0-20221008-104424-6776-1368.zip](https://github.com/HasKha/GWToolboxpp/files/9739605/6.0-20221008-104424-6776-1368.zip)

When trying to talk with an NPC to say trying to sell stuff u no longer need etc, the game will send out a dialog info crash with the DMP I checked the debugger which read:

GWToolboxdll.dll	GWToolboxdll.dll	C:\Users\dronk\Downloads\GWLauncher\plugins\GWToolboxdll.dll	N/A	Yes	Cannot find or open the PDB file.		36	6.00.0.0	9/25/2022 5:45 PM	7B330000-7B77F000	6.0-20221008-104424-6776-1368.dmp		

I highly doubt I am probably the only one, during Speedruns, etc. I am fine.

**Comment by 3vcloud** [comment]
Can't copy this issue and crash dump isn't helping much, might  need a video or something

**Comment by BearsMan** [comment]
I'll try to make one when I get back for u @3vcloud

**Comment by BearsMan** [comment]
https://youtu.be/lN09Ha0MeZs

Video Link for u @3vcloud

**Comment by BearsMan** [comment]
Note: I should have added the other crash I had in Marketplace near KC, I can add a video for that too if needed

**Comment by BearsMan** [comment]
https://www.youtube.com/watch?v=9TX0w0ax5I4

@3vcloud this one does not have the crash dump on it
