### ISSUE TITLE
hide item description bug

### ISSUE THREAD

**Issue by Zane1-2** [HasKha/GWToolboxpp#832]
Depending on when you press alt (before or after hovering over the item) sometimes the item description isn't shown.
For the Shield in a weapon set to show up you need to move your mouse on to the item set back off and on again for the description to appear. Also the item description of a shield then is still visible after letting go of alt.

https://youtu.be/uKKJIZOSrkM

**Comment by 3vcloud** [comment]
Glad you added a link to youtube here, you've mentioned nowhere that the bug only happens when you equip the item/slot that you're hovering over!
