### ISSUE TITLE
Hero Builds: Change of the second profession for heroes sometimes does not occur

### ISSUE THREAD

**Issue by truekenny** [HasKha/GWToolboxpp#834]
https://www.youtube.com/watch?v=QuzVMJLhNG4

In the video: I use three test builds:
the first (w/mesmer) and second (w/monk) builds switch professions automatically, but the third (w/ritualist) does not.
If you manually set the ritualist profession and load the third build, then the skills will be loaded into the hero panel.

The problem does not always reproduce. When changing the city, other builds may refuse to switch the profession, others will earn.
To reproduce the problem, if all builds work, then you need to change city.

In version 5.14, I did not encounter such a problem.

Tested builds for Goren:
W/Me OQUCI8wzJAna6me5gMQRhUD
W/Mo OQMS44KPclAA/w67zwr4D4B
W/Rt OQgiUxh8wVCAJXC24UaKOHmA

**Comment by 3vcloud** [comment]
Looks like you've found a GW bug (feature?) where the list of heros in the party search window don't match up to the party window when you change a hero's secondary profession.

![image](https://user-images.githubusercontent.com/10796356/198679552-ed1a5ba0-b5a0-4690-9839-99f07ea04cee.png)

When the map is changed, this info is properly updated so isn't a problem.

Fixed for next version, thanks
