### ISSUE TITLE
Minimap docking: optimise agent circle positions

### ISSUE THREAD

**Issue by DubbleClick** [HasKha/GWToolboxpp#836]
we should draw perfectly on top of the regulars compasses enemies/allies.

it's a tiny bit off as it is

**Comment by 3vcloud** [comment]
![image](https://user-images.githubusercontent.com/10796356/201047176-63a36ceb-eb98-4348-a04a-72509ad97729.png)
Nope

**Comment by DubbleClick** [comment]
https://youtu.be/436y9gCHA9c

check the minimap around the skeles

**Comment by 3vcloud** [comment]
Yep, same as the offset for NPCs in the above image; the bitmap loaded in GW for the agents isn't 100% accurate but because the offset doesn't change with orientation or distance, the toolbox minimap is bang on

**Comment by DubbleClick** [comment]
We should at least introduce a setting to overlay on top of the games sprites - or disable the games sprites entirely, because the way it is now looks silly.
