### ISSUE TITLE
Patch auto-login to work without character name

### ISSUE THREAD

**Issue by DubbleClick** [HasKha/GWToolboxpp#839]
would likely want to patch this with gw launcher, but if you create a patch in tb I can port it over :>

**Comment by 3vcloud** [comment]
Related to https://github.com/HasKha/GWToolboxpp/issues/840 but a bit harder to implement due to sections of code that check for presence of charname

**Comment by DubbleClick** [comment]
If that's easier, fine by me.

**Comment by 3vcloud** [comment]
https://github.com/HasKha/GWToolboxpp/commit/984ee56a8622f52cc9aed99987fe0041be21a349

Not a simple patch I'm afraid, but works well when loaded at launch
