### ISSUE TITLE
Crashing on Version 6 - Arcolinux, wine 7.22

### ISSUE THREAD

**Issue by antoniorussell** [HasKha/GWToolboxpp#846]
[6.0-20221219-23.zip](https://github.com/HasKha/GWToolboxpp/files/10263553/6.0-20221219-23.zip)
Here is the crash files, hope it helps you folks to solve the issue, great mod for a great game. cheers.

**Comment by 3vcloud** [comment]
Fixed https://github.com/GregLando113/GWCA/commit/6b49cc58b76a970e77366b50ee49e22beb958981
