### ISSUE TITLE
Version 6.x - Obfuscator - (Hide Character Name In-Game Issue, I was able to narrow it down).

### ISSUE THREAD

**Issue by BearsMan** [HasKha/GWToolboxpp#849]
I may have found an issue that causes the screen to freeze at login after switching characters, I was able to narrow it down, would you like me to put an issue in Github, and/or I can post a screenshot of the area I found that caused it?

https://gyazo.com/ae2ef9b0ad638ca4d4754f5046dae5be
https://gyazo.com/894c35d7bdb79a4c28e1f78aef8b8443

If Hide Character Name In-Game is checked you log out to switch to another character the game screen will freeze. (Game is in Windowed-Borderless Mode.

**Comment by BearsMan** [comment]
@3vcloud @DubbleClick have a look when able

**Comment by DubbleClick** [comment]
You don't need to ping us, we're subscribed to the repository.

**Comment by 3vcloud** [comment]
Can't cause this freeze, run gw without any other mods and retry

**Comment by BearsMan** [comment]
I will look it to running it without mods and get back to you on that

**Comment by BearsMan** [comment]
https://youtu.be/f69lOQc4F6Y - This one has the mods running via GW Launcher (we can ignore this one!)
https://youtu.be/Z2zPqsMzfUU - second video - we will use this (this is run without mods and gw launcher via Steam

**Comment by BearsMan** [comment]
I found to replicate it was to keep using the arrow keys left and right as fast as possible to force a freeze  at least that’s how I did it

**Comment by BearsMan** [comment]
Here is another test one when typing in my password, yes I do have it hidden so that can't see the email or password during login.

https://youtu.be/bBaVGFQuhms

**Comment by BearsMan** [comment]
I did one final test in a video with the option enabled on screen: here is a video link: https://youtu.be/-JP6eyUoq0o
