### ISSUE TITLE
[v6.2] Item context menu bugs

### ISSUE THREAD

**Issue by kazerniel** [HasKha/GWToolboxpp#853]
Opening the item context menu only works occasionally in explorable areas, and not at all in outposts.

When it does work, it just keeps opening the context menu for the first item I right-clicked on, even if I try other items afterwards.

It also opens around the middle of my screen rather than under the item.

**Comment by 3vcloud** [comment]
Have you got the mouse fix turned off in mouse settings?

**Comment by kazerniel** [comment]
Oh so that's what that was for :o
