### ISSUE TITLE
Where exactly is the settings folder?

### ISSUE THREAD

**Issue by XFlashAllianceX** [HasKha/GWToolboxpp#855]
I tried adding the install file to "C:\Users\username\AppData\Local\GWToolboxpp". When I start the game, it begins writing in "C:\Users\Documents\GWToolboxpp". Is the document folder the default or can I change where the program saves my settings?

**Comment by DubbleClick** [comment]
Documents\GWToolboxpp is the toolbox folder, Documents\GWToolboxpp\<ComputerName> is the settings folder. These cannot be changed.

**Comment by XFlashAllianceX** [comment]
> Documents\GWToolboxpp is the toolbox folder, Documents\GWToolboxpp<ComputerName> is the settings folder. These cannot be changed.

TY.
