### ISSUE TITLE
GWToolbox++ Crash!

### ISSUE THREAD

**Issue by jonathanjogensjo** [HasKha/GWToolboxpp#857]
Hi!

When trying to save settings or exiting GWtoolbox it crashes. Do you know why and is there a solution?

Don't seem to be able to add the crash DMP-file since it is not supported by github.

Kind regards,
Jonathan

**Comment by BearsMan** [comment]
> Hi!
> 
> When trying to save settings or exiting GWtoolbox it crashes. Do you know why and is there a solution?
> 
> Don't seem to be able to add the crash DMP-file since it is not supported by github.
> 
> Kind regards, Jonathan

You have to zip the latest DMP-file and copy paste it to github

**Comment by jonathanjogensjo** [comment]
[6.3-20221229-125416-14368-7152.zip](https://github.com/HasKha/GWToolboxpp/files/10319523/6.3-20221229-125416-14368-7152.zip)
