### ISSUE TITLE
Crashes while playing

### ISSUE THREAD

**Issue by vopi61** [HasKha/GWToolboxpp#858]
GW crashes while doing various things. This starts after updating to GWToolbox 6.2. Now i am up to version 6.4. The last crash happened while identifying items. Unfortunatly i cant upload the dumpfile here.

**Comment by BearsMan** [comment]
compress as a ZIP file

**Comment by BearsMan** [comment]
> GW crashes while doing various things. This starts after updating to GWToolbox 6.2. Now I am up to version 6.4. The last crash happened while identifying items. Unfortunately i cant upload the dump file here.

Compress it as a ZIP file.

**Comment by ResetGT** [comment]
[6.4-20230102-104747-4392-12652.zip](https://github.com/HasKha/GWToolboxpp/files/10332559/6.4-20230102-104747-4392-12652.zip)

**Comment by ResetGT** [comment]
Happened when I right clicked "Identify all items"

**Comment by CosmicGates** [comment]
Crashing on injection immediately today. Crashing also with the Windows 10 notification toast windows when someone DMs you and the Guild Wars window is not in focus or Alt+Tabbed. Also just randomly crashes

**Comment by 3vcloud** [comment]
> Crashing on injection immediately today. Crashing also with the Windows 10 notification toast windows when someone DMs you and the Guild Wars window is not in focus or Alt+Tabbed. Also just randomly crashes

Please send me a crash dump on discord for the PM crash

**Comment by CosmicGates** [comment]
> 

sure, where are dumps located

**Comment by vopi61** [comment]
my dumps were under GWToolbox directory/"Computername"/crashes
