### ISSUE TITLE
Make minimap rotate at the same rate as the default compass

### ISSUE THREAD

**Issue by HasKha** [HasKha/GWToolboxpp#87]
Since a lot of users are currently using the minimap as an overlay to the original one, it would make sense to improve that experience. 

Hard requirement: finding the minimap structure in the client and minimap rotation

things to change:

* [x] Make the minimap rotate with the default compass
* [x] Allow click-through at all times except for ctrl+click

Anything else? We don't need to automatically match position/size, and all components can be disabled automatically by setting their alpha to 0.

**Comment by HasKha** [comment]
Note: those should be two independent options. Click-through by itself is enough to enable some usages such as D2-like overlay map

**Comment by jnvsor** [comment]
> Allow click-through at all times except for ctrl+click

Not sure if this is a regression but this is not working currently. There is currently no combination of settings that allows you to both Ctrl+Click to target something on the map (Or Alt+Click to move) and flag heroes with the original controls at the same time.

With "Allow mouse click-through" on you can flag heroes but can't target/move, and vice-versa if it's off

**Comment by DubbleClick** [comment]
I'd also welcome an option to turn off camera smoothing ingame and on the default compass instead.

**Comment by 3vcloud** [comment]
Done https://github.com/HasKha/GWToolboxpp/commit/27f9d3e2394ab8df23e24e5c5e9e7b9fe8360bc8
