### ISSUE TITLE
Game is constantly crashing

### ISSUE THREAD

**Issue by cjechurchill** [HasKha/GWToolboxpp#878]
The game crashes whenever I go through an instance. The game freezes and this window pops up 
How do I attach an image. Why are things so complicated.....

**Comment by BearsMan** [comment]
> The game crashes whenever I go through an instance. The game freezes and this window pops up How do I attach an image? Why are things so complicated.....

Take a screenshot from where it saves to it should be in ```Documents/Guild Wars/Screens``` and drag it in GitHub issue here

**Comment by BearsMan** [comment]
The other question is? What happened while you were playing the game (does the client just close randomly without a dialogue window or anything?

**Comment by cjechurchill** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/63122552/217866831-f7a47bed-c5ea-43f0-bc2e-6838cf6d30bd.png)

**Comment by cjechurchill** [comment]
Crash logs here 
[WinZip Backup2023-02-09-16-08-17.zip](https://github.com/HasKha/GWToolboxpp/files/10699111/WinZip.Backup2023-02-09-16-08-17.zip)
