### ISSUE TITLE
Look into luxon/kurz skill switch bug

### ISSUE THREAD

**Issue by 3vcloud** [HasKha/GWToolboxpp#882]
Hello people, I've encountered a weird phenomenon, when loading templates that contain a kurz/lux pve skill, the skill bar locks up : impossible to remove or change anything. Anyone had a similar glitch? Only thing I can do is load a random bar with no kurz/lux skill, then it unlocks and I need to build the bar from scratch. Also changing outpost does the trick. I used to have no problem with tb 5.15, then it updated and I can't roll back anymore.

https://discord.com/channels/223619617048756224/224695376102293514/1077218247809712209

**Comment by DubbleClick** [comment]
tried to reproduce on 2 accounts, no luck :/

**Comment by DubbleClick** [comment]
Game doesn't register that it's typing and a hotkey blocks the action being sent through to gw...

**Comment by 3vcloud** [comment]
Please make an issue for the typing thing, I’ll sort it
