### ISSUE TITLE
Change overlapped target on minimap

### ISSUE THREAD

**Issue by AlexandrePalo** [HasKha/GWToolboxpp#891]
Hi,

I would like to propose a new feature that I think may be very useful in some areas. Please let me know if this is already possible by another way.

When you "CTRL + left click" on the toolbox minimap, you can select something. However, the selection looks quite random when a lot of enemies are overlapping. On several softwares you can quickly switch to another close target by "CTRL + left click" on the area. Thus, you right click until you've selected the target you want. 

This would be useful for instance in Urgoz or DoA, where selecting the correct agent on the minimap within large groups can be an hassle even if you've set up custom colors.

For instance, in a CAD software :

![2023-04-21-12-52-37](https://user-images.githubusercontent.com/18114533/233620190-5916eb1a-8d2b-47d7-9446-854b976cdfd3.gif)

**Comment by DubbleClick** [comment]
The minimap selects the target that's closest to the minimap position you're clicking on. It's not "random".

As for targeting closest enemy to the one you currently have targeted, we could make that a chat command. You could bind it to a hotkey then.

**Comment by AlexandrePalo** [comment]
Yeah I knew it was the closest of course but looks random when you compare how close enemies can be and the precision you can have with a mouse. 

An hotkey would be perfect, as long as you can change quickly to another foe 🙂

**Comment by 3vcloud** [comment]
Nope, this would cycle between 2 enemies until they move and would still be just as useless. Keeping a record of what you've already clicked on or targetted would also be a bit of a headache, just use tab in game to do the best you can with it
