### ISSUE TITLE
Obfuscator auto crash without dialog box or pop up 

### ISSUE THREAD

**Issue by BearsMan** [HasKha/GWToolboxpp#895]
I might be wrong about this part, and I do have screenshots. I just need to do a video test but whenever I have Obfuscation turned on, the character will lag out for maybe 2-3 seconds then the game will instantly crash without a dialog pop-up window with an issue for the fix. The best way I found to not auto crash is to play with Obfuscator turned off and then, it may be fine, or it may not. Let me do a video test to be sure. I will attach screenshots here as well.
![gw071](https://user-images.githubusercontent.com/34116754/233839987-c7a92b9b-a593-4158-bc38-6dcd46a73714.jpg)
![gw072](https://user-images.githubusercontent.com/34116754/233839989-860d487d-b8d1-4218-87f4-bb6fbf770f86.jpg)

I will do a video test via OBS and send another submission to make sure I am not crazy lol!!!! 😂 Anyways have a nice day!

**Comment by BearsMan** [comment]
Here is the first test I just did with Obfuscation turned on and you will see that the game did instantly [crash.](https://youtu.be/S-B4pr-zQpM)

**Comment by BearsMan** [comment]
I am making a video to see if I can reproduce the issue. This is with Obfuscation turned on in-game, and you will see that the game will lag a bit and then it will crash. [https://youtu.be/S-B4pr-zQpM](URL)

**Comment by DubbleClick** [comment]
Sorry, but 1) I have no idea what's going on in this 0.3 fps video and 2) I can't replicate it or most of the other crashes you're having. I assume this is just co-play of the 23101320 mods you have running in the game, especially if you don't get a crash dump.

**Comment by BearsMan** [comment]
https://youtu.be/hsV5BstqCvI - This was run without Obfuscation but yea just close this. I will test something else. [https://youtu.be/hsV5BstqCvI](url)
