### ISSUE TITLE
Save "Lock Position" and "Lock Size" for Damage and Bonds

### ISSUE THREAD

**Issue by AnonymousII** [HasKha/GWToolboxpp#90]
Please make Toolbox save the settings "Lock Position" and "Lock size" for both Damage and Bonds Monitor (under Settings) - whenever I restart Toolbox or press "Load Now" in Settings it resets both settings to enabled, even if I disable them and press "Save Now".

Whenever someone pops a summon stone or an ally appears in the party window I need to move bonds / damage monitor so that the right bar is next to the right name in the party window - resetting the "Lock Position" option after each restart of Toolbox / GW manually is annoying :(

**Comment by HasKha** [comment]
both those widgets are meant to be placed next to your party window and match it while your party changes. Why do you need to move it when summoning stones are used?

The only extreme case I can think of, is in uwsc where the allied window becomes huge, but I think most uw people just collapse the allies, and toolbox has an option to not expand bond monitor to allies.

**Comment by HasKha** [comment]
on a separate note, bond and damage monitors should not have "lock size" toggle at all, since it has no effect (it allows to drag the size, which gets reset anyway to adapt for party size).

**Comment by AnonymousII** [comment]
The "Lock Size" Option indeed makes no sense for Damage / Bonds monitor and should be removed, yes.

For the "Lock Position" option it depends on the position of the party window whether you have to move Damage / Bonds monitor or not when summoning stones / allies appear: When you place the party window on the bottom (like in default gw settings) it grows upwards, so when an ally is added at the bottom the party members are shifted upwards, but the damage / bonds monitor doesnt move. 

![damagemonitor](https://cloud.githubusercontent.com/assets/27740061/25151452/fa739a5a-2485-11e7-99ac-330a09f05eab.jpg)

So having the party window at the bottom you have to move Damage / bonds monitor up whenever an ally / stone appears in the party window to put the bonds/damage next to the right players. (Of course the party window can be placed on top of the screen but im just used to having it on the bottom)

**Comment by HasKha** [comment]
Pretty sure the default is on the right, in the middle, and the issue of growing upwards is exactly why the vast majority don't keep it at the bottom :)

However, I understand the issue. I'll think about it.

**Comment by HasKha** [comment]
removed 'lock size', made 'lock position' saved and loaded.
