### ISSUE TITLE
Cursor disappears

### ISSUE THREAD

**Issue by Lemaggo** [HasKha/GWToolboxpp#900]
For about 1 week and I do not know exactly what it is.
When I play and open TB, my cursor just disappears after a random time. Sometimes after 5 minutes and sometimes after 1 hour.
I can still hover over objects and select them, but it's more luck than skill. 
There is no particular trigger that does this.
Sometimes in the inventory, sometimes in the middle of the DOA run. 

Thanks for Help... TB is amazing!

**Comment by DubbleClick** [comment]
set cursor size back to default (32) in toolbox settings

**Comment by Lemaggo** [comment]
Hey DubbleClick,

thanks for the quick feedback. 
the cursor size was 29 and i have reset it.

Many thanks already.
