### ISSUE TITLE
A few requests

### ISSUE THREAD

**Issue by YungRocks** [HasKha/GWToolboxpp#903]
Here's a short list of features I would like to see in Toolbox :)

- Calling target (default: Ctrl + Space) changes pet's stance to Attack. A feature all Beastmaster players would appreciate I believe.
- Similarly to the damage meter, a healing meter to compare healers' performance.
- When the player uses a skill (in general, or maybe only if pinged), all heroes that have this skill equipped get microed to use it too. Would be useful for Junundu Tunnel for one, and also for people wanting some funny gameplay like "everyone uses Barrage _now_".

That's it for now folks! Thanks for this great toolbox.

(I don't seem to be able to add a label..? Sorry about that)

**Comment by franneck94** [comment]
3. Is most likely too much of a cheat ;)
But 1. is a really good point

**Comment by DubbleClick** [comment]
Oh yeah number 3 is a no-go.

As for number 1, don't pets start attacking when you call a target even when they're in guard mode?

**Comment by YungRocks** [comment]
> As for number 1, don't pets start attacking when you call a target even when they're in guard mode?

They do attack whoever you attack, but with a delay (about 5s to adapt to your target with just Guard and calls but instant retargetting with Attack stance), and with more limitations than Attack stance. For instance, you cannot make a pet on Guard attack a foe that is out of the aggro bubble with calls only, whereas with Attack stance you can make the pet run up to a foe that is out of even spellcasting range.

**Comment by 3vcloud** [comment]
We can translate this to:

1. allow a hotkey for pet behaviour 
2. Should be an issue on its own to discuss
3. Create ( or double check if we’ve already done it) a hotkey to trigger a hero to use a skill by skill id, not just skillbar position
 
Then you’ll be able to create hotkey(s) to do this stuff

**Comment by DubbleClick** [comment]
number 1 is implemented with a hotkey

number 2 is worth it's own issue if this is still important to you

number 3 is still too botlike for me
