### ISSUE TITLE
Crashing when selecting The Ascalon Settlement quest

### ISSUE THREAD

**Issue by Clad-Vesto** [HasKha/GWToolboxpp#904]
Hello, I had a few crashes happen yesterday with .dmp generated whenever I would select the quest "The Ascalon Settlement". The game would not crash if Toolbox wasn't running, but the issue was reproducible from restarting my PC.

Workaround was simply to just not run toolbox until the quest was finished but thought it was worth mentioning anyway.

**Comment by BearsMan** [comment]
Zip the dump file and add it here it needs to be compressed as a zip first before you add it in

**Comment by Clad-Vesto** [comment]
[CladVesto-crashes.zip](https://github.com/HasKha/GWToolboxpp/files/11592932/CladVesto-crashes.zip)
I added the three dump files that were generated each time.
