### ISSUE TITLE
Some Items are invisable

### ISSUE THREAD

**Issue by Lemaggo** [HasKha/GWToolboxpp#909]
Hey Guys, 

at some point, random items mostly unsaleabe one, just going invisable. (I attached a Screen)
The item is on the spot were the blue colour is
![rin lost](https://github.com/HasKha/GWToolboxpp/assets/134084164/cfbb242c-6183-4856-b281-73fe2e4d86f0)

Thanks for helping

**Comment by DubbleClick** [comment]
Are you sure that this is related to toolbox? I've never encountered invisible items, except when my gw.dat was broken.

**Comment by Lemaggo** [comment]
Oh lol, you right. 
![rin da](https://github.com/HasKha/GWToolboxpp/assets/134084164/6d2b72b5-2feb-400f-b879-9018d23be85e)
i was just wondering, when i started TB, the item disappears. But i happens either, when i move the item without TB. 

You mean i have to fix the gw.dat?

Thanks for your reply!

**Comment by BearsMan** [comment]
For the gw.dat make sure that you update your GW client, even if you think there may not be any updates. This is helpful just in case.

**Comment by Lemaggo** [comment]
How can i update them? 

Thanks for your help

**Comment by DubbleClick** [comment]
Delete your gw.dat and let guild wars download it again

**Comment by Lemaggo** [comment]
Done it, but things are getting worse. 
But i found out, that GW Launcher caused it. 
I startet withouth Launcher and now everything runs normal. 

Thanks for your help anyway!

**Comment by DubbleClick** [comment]
You're most definitely using a super old version of gw launcher then and still hat the .dat "fix" enabled. That broke and was removed many years back.
