### ISSUE TITLE
Show player names in Bond Monitor

### ISSUE THREAD

**Issue by AnonymousII** [HasKha/GWToolboxpp#91]
Please add an option to show the player / npc names in each line of the bond monitor (maybe make it configurable so people can enable/disable it themselves) - during a run it would be a lot faster to see which player / npc has which bonds if you got a name next to the bonds line - especially when people use summon stones or allies appear in the party window you always have to move bond monitor next to the player names to keep an overview over which player has which bonds. (if Toolbox cant read out the names afterwards just read out the target name when casting the bond)

In the damage monitor the same option would be helpful but its most important in bonds monitor.

**Comment by HasKha** [comment]
Bond monitor is meant to be placed next to your party window and match it's height. The party window itself shows the name. Adding names seem useless duplication of information to me. Again I don't understand the issue with moving, but let's discuss that in #90

**Comment by AnonymousII** [comment]
the most elegant solution to all the damage / bonds monitor moving issues would probably be a custom party window showing damage and bonds in extra columns next to the names (merging party window, damage monitor and bonds monitor into one new "party window" that replaces the default party window during the run)- so whatever you do and wherever you place the new party window the columns are always automatically in the right place without manual moving, position settings / position adjust on fullscreen etc (but the effort is probably too high for this - although it would be a nice feature :) ). 
Only adding the names in each monitor is probably really just redundant information once there is a convenient solution to keep the bars / bonds next to the players in the party window like in #90

**Comment by HasKha** [comment]
I agree, but I have no plans to implement a party window. Closing this.
