### ISSUE TITLE
Bugs to be repaired

### ISSUE THREAD

**Issue by BearsMan** [HasKha/GWToolboxpp#919]
[6.10-20230806-072508-21368-19324.zip](https://github.com/HasKha/GWToolboxpp/files/12269267/6.10-20230806-072508-21368-19324.zip)

I may have found a bug when selecting hero builds in the toolbox hero build window. I did also find out that it was not being loaded when checking the file at start of TB
[log.txt](https://github.com/HasKha/GWToolboxpp/files/12269270/log.txt)
added my  log document file too.

**Comment by BearsMan** [comment]
[6.10-20230806-162333-20196-2192.zip](https://github.com/HasKha/GWToolboxpp/files/12270366/6.10-20230806-162333-20196-2192.zip)

This crash here may be related but it crashes instantly on launch as well, unless running a fresh copy of GWToolbox.ini file

**Comment by adituv** [comment]
The first issue seems to be that clicking "Copy" in the hero builds window while no hero teambuilds are defined causes a hard crash, is this right?

The second issue I had a look inside the crash dump but can't figure it out.  It's a Gw.exe crash nested 32 calls deep from a packet handler, and VS is showing the address of the packet as the invalid memory address 0x137.

**Comment by BearsMan** [comment]
The first one is the one I noticed.

**Comment by BearsMan** [comment]
> The first issue seems to be that clicking "Copy" in the hero builds window while no hero team builds are defined causes a hard crash, is this right?
> 
> The second issue I had a look inside the crash dump but can't figure it out. It's a Gw.exe crash nested 32 calls deep from a packet handler, and VS is showing the address of the packet as the invalid memory address 0x137.

The first one is a hard crash when loading TB through the game.

**Comment by BearsMan** [comment]
> The first issue seems to be that clicking "Copy" in the hero builds window while no hero team builds are defined causes a hard crash, is this right?
> 
> The second issue I had a look inside the crash dump but can't figure it out. It's a Gw.exe crash nested 32 calls deep from a packet handler, and VS is showing the address of the packet as the invalid memory address 0x137.

It also freezes TB Load at Launch when I use my settings I copied from my flash drive, I have one for all of my hotkeys, etc. another for a fresh copy (no hotkeys, etc.

**Comment by DubbleClick** [comment]
> The second issue I had a look inside the crash dump but can't figure it out. It's a Gw.exe crash nested 32 calls deep from a packet handler, and VS is showing the address of the packet as the invalid memory address 0x137.

Unfortunately bears is running approximately 493 modifications, which makes it nigh impossible to tell whether the crash was related to toolbox or not. This doesn't sound like it is.

I haven't had any crashes with the hero build window, but if that's actually a consistent crash it should be easy enough to fix. Will look at it tomorrow.

**Comment by BearsMan** [comment]
> > The second issue I had a look inside the crash dump but can't figure it out. It's a Gw.exe crash nested 32 calls deep from a packet handler, and VS is showing the address of the packet as the invalid memory address 0x137.
> 
> 
> 
> Unfortunately bears is running approximately 493 modifications, which makes it nigh impossible to tell whether the crash was related to toolbox or not. This doesn't sound like it is.
> 
> 
> 
> I haven't had any crashes with the hero build window, but if that's actually a consistent crash it should be easy enough to fix. Will look at it tomorrow.

I tested the hero build window press, and it did crash with that.

**Comment by BearsMan** [comment]
After running some tests of my own, it only freezes for me on launch when I open TB with my main account via GW Launcher, all the other accounts that I have added to my account list work fine on launch. I just need to find out why it freezes on launch on my main account. I can provide a screenshot if required.

Picture of main account launch and instant freeze: 
![image](https://github.com/HasKha/GWToolboxpp/assets/34116754/5bffe73b-4096-48ab-8337-d00d75874fe1)
I even did a test when using the vanilla version of the game with it and the same thing happen.

**Comment by BearsMan** [comment]
I also fixed the Obfuscater issue for me as well.

**Comment by BearsMan** [comment]
> I was able to fix the freeze issue, as it turns out the ini I had was broken, so I decided to re-write my ini from scratch. I just copy-pasted the hotkeys I had over to the new ini

Nvm I think it may have broken again.

**Comment by DubbleClick** [comment]
Fixed the herobuild copy
