### ISSUE TITLE
Toolbox fails to download files

### ISSUE THREAD

**Issue by HasKha** [HasKha/GWToolboxpp#92]
Rarely, toolbox fails to download files. Happens for a few users, but consistently.

The most obvious symptom is not being able to see icons in the pcons window, but icons are also missing from materials and toolbox windows. 

**In order to fix it, first try to launch Guild Wars as admin (or, if you launch it through another program, launch that program as admin). If that doesn't work, use the launcher here, once: https://github.com/HasKha/GWToolboxpp/releases/tag/2.0-launcher.**

I am interested if anyone has any information on this. Only thing I know is that the log shows no error (only a list of "downloading http...". 

If you want to test if downloading works correctly for you, just rename your /img/ folder to /img_old/, and re-launch toolbox. 

This issue is important to solve quickly because the same download system is used for auto-updates.

**Comment by reduf** [comment]
This issue start occuring after we made the dll download the ressources. It use to be the launcher.
It might come from the fact that `Gw.exe` isn't launched in admin mode and hence, the dll that inherit from the executable right, fail to download the ressources on some sytstems.

To inject the dll on thoses systems you probably needed to have admin rights and for this reason, didn't have the issue.

If someone has this problem, it will be nice to test with `Gw.exe` launched in admin and tell us if it works.

**Comment by ritlew** [comment]
I don't see icons. After running both in admin mode on Win10 I still don't see them. I also can't find an images folder.

**Comment by ritlew** [comment]
Yep, I can confirm this. The folders are made in the GW directory, but they try to download into my AppData.

**Comment by ritlew** [comment]
This fixed it for me, should I make a pull request or do you guys think it's something else?

https://github.com/ritlew/GWToolboxpp/commit/9698b6c9765e81a4284f37f3cafed4bc2879a9c5

**Comment by HasKha** [comment]
Interesting, yes that makes sense, I forgot to add the settings folder path. Don't make a PR with that. I'll check everywhere EnsureFolderExists to be sure.

**Comment by HasKha** [comment]
this should be fixed
