### ISSUE TITLE
The dll does not cleanup properly on unloading

### ISSUE THREAD

**Issue by quetzalsly** [HasKha/GWToolboxpp#920]
When pressing the close button, the expected behavior is for the dll to unload itself, while cleaning up all hooks and memory allocations. Unfortunately it seems the skill icons do not get properly cleaned up. Unloading and then reloading into the same gw.exe instance results in the console being spammed with:

Failed to load skill image, Unknown D3D error.

This leads me to believe its not cleaning up the d3d texture allocations somewhere.

**Comment by DubbleClick** [comment]
This doesn't appear to be related to toolbox cleaning up, it would be able to create the textures again just fine even, if they were still in use.

What's the error code after "Unknown D3D error: 0x1234"?

Most likely explanation is that the images just don't exist in your folder and it throws the error messages the first time you load tb too.

**Comment by 3vcloud** [comment]
You’re correct that toolbox doesn’t free textures, and depending on your graphics card, it’ll keep some of them in memory even after gw is closed. We use (should be using) d3d managed pool when creating the textures. Although it does say in the docs that you don’t need to recreate these textures across a device reset, it doesn’t say that you don’t need to free them when your application closes, but I suspect it would have undefined results if you tried

**Comment by DubbleClick** [comment]
As far as I understand, the resources do not necessarily get freed even when the application closes. The system manages this memory as needed and copies it back into an area that is accessible by the current d3d device when necessary.

I don't think we *should* free anything here.

**Comment by DubbleClick** [comment]
closed due to no further replies
