### ISSUE TITLE
Reroll bugged with empty character slot

### ISSUE THREAD

**Issue by adituv** [HasKha/GWToolboxpp#929]
When rerolling to a character before the current character in the character select screen, where there is an empty character slot before the target character, reroll gets stuck trying to navigate to the new character.

In my case, I currently have Mesmer, [Empty], Assassin, Elementalist, [...].  If I am on the Elementalist and `/reroll assassin`, the cursor keeps alternating between the Mesmer and the empty character slot; this happens naturally in-game by pressing right, so I think that fixing this would require changing the way a character is selected for reroll.  I originally considered also trying to scroll with left, but I believe this would still fail in the case of e.g. Mesmer, [Empty], Assassin, Elementalist, [Empty], Monk.

The relevant code is in [RerollWindow.cpp:L450](https://github.com/HasKha/GWToolboxpp/blob/32ec904b78a1deba6dc0b7533d3e04883854e123/GWToolboxdll/Windows/RerollWindow.cpp#L450).

**Comment by DubbleClick** [comment]
I don't have a free char slot to test this one, but I'll see if I can fix it and ask you to test :)

**Comment by BearsMan** [comment]
I can make a free slot on an
alt and test it.

**Comment by DubbleClick** [comment]
#fa84f17aed55d3b31817416b290045a1c96d6426

**Comment by DubbleClick** [comment]
#fa84f17

**Comment by DubbleClick** [comment]
why on earth can't I reference commits with their tag anymore

https://github.com/HasKha/GWToolboxpp/commit/fa84f17aed55d3b31817416b290045a1c96d6426

**Comment by adituv** [comment]
While that commit fixes my original case, it does not fix the case where there are two empty slots not next to each other.  I can't find any combination of key presses that can cross empty slots in a configuration like AXBBXA.  You can either select the A's or the B's with the arrow keys depending on which side you're on, but can't cross the X.  I suspect a full fix will require reverse engineering work on the login screen to select a character by index directly rather than using virtual keypresses.

**Comment by DubbleClick** [comment]
alright, fixed
