### ISSUE TITLE
"/target Merchant" now targets any allied NPC

### ISSUE THREAD

**Issue by kazerniel** [HasKha/GWToolboxpp#931]
Not sure when it broke, but I'm reasonably certain that in mid-May it still allowed to target by partial name like that.

Edit: the above works in outposts, in explorable areas it interestingly targets heroes, but not allied NPCs

**Comment by 3vcloud** [comment]
Is this on current release or dev?

**Comment by DubbleClick** [comment]
Just tested this, only targets merchants for me.

**Comment by BearsMan** [comment]
I just tested on the current release and it targets merchants for me.

**Comment by DubbleClick** [comment]
After the edit it becomes pretty obvious: MERChant and MERCenary Hero.

**Comment by DubbleClick** [comment]
(I.e: closed it because I see no reason to "fix" this. The only merchants you get in explorable areas are fro. Summoning Stones and this only triggers on Mercenary Heros. To change this behaviour we'd have to loop through all agents and rank them by string difference, which would very inefficient.)

**Comment by kazerniel** [comment]
No I mean it literally changed behaviour between May and now. (public version)

In outposts it used to only target NPCs with Merchant in the name. Now it targets the closest regardless of name. (I haven't tested it in explorable areas before it broke.)

**Comment by DubbleClick** [comment]
I cannot reproduce that. /target merch in outposts only targets the closest merchant for me. I haven't tried it non-outposts yet.

**Comment by kazerniel** [comment]
Is there some kind of log I can send? TB says it's up to date with v6.10, and everything else seems to work as normal.

**Comment by kazerniel** [comment]
Ok, figured it out, I was using the wrong hotkey that happened to be GW's own hotkey for targeting nearest ally 🤦‍♂️ This is what I get for taking a few months off from the game 😅

Sorry for the trouble!

**Comment by DubbleClick** [comment]
Well that explains it x)

**Comment by 3vcloud** [comment]
Be sure to check the “block key in guild wars” button when it’s relevant to your hotkey
