### ISSUE TITLE
Transmotarget lacks proper documentation. 

### ISSUE THREAD

**Issue by JohnForsgren** [HasKha/GWToolboxpp#935]
Issue: Only documentation for Transmotarget appears to be here: 
gwtoolbox.com/commands
and the guide for how transmotarget works doesn't seem to work. For example, in Lion's Arch i select an NPC and use the command: 
/transmotarget Lionguard
But i just get "Unknown transmo: 'Lionguard'". I get the same result for all other attempts i make. 
It says in the "commands"-guide i linked that you should have the NPC name. Is it referring to ID? If so, the guide doesn't specify where to find that.

**Comment by 3vcloud** [comment]
Check the help section of the toolbox settings window for available npc names

**Comment by JohnForsgren** [comment]
Ok thanks, I found it now! Great job with the tool, but it seems it could be easier to find. Would be nice if it at least specified in the documentation that you can find the current available list by hoovering specifically over the question mark at this place in the help-section.
