### ISSUE TITLE
Feature Request: Include some documentation for Animations 

### ISSUE THREAD

**Issue by JohnForsgren** [HasKha/GWToolboxpp#936]
I have written a simple python script that allows me to quickly go through the animations available with "/Animation me <id>" 
Current data for the animations [with id 1-2076] have is (approx)  
1-150 = mesmer skills
150-160 = Conditions
160-290 = Necro skills
300-420 = Elementalist skills
420-440 = Special animations
440-580 = Monk skills
etc

I assume that this data is already located somewhere, but i have not found any documentation on this. It would be great if the documentation on the website included some sort of info, or place where people could upload data.

**Comment by DubbleClick** [comment]
If you would like to compile a list, sure. I don't think we have any documentation on it.

**Comment by 3vcloud** [comment]
This is a gwca issue, not toolbox

**Comment by JohnForsgren** [comment]
Ok, but could you please provide a link in your documentation that links to a place at gwca where people can read and/or upload this data?
It would make the tool feel a lot more useful if there was some sort of info like this, rather than 2000 unknown animations. 

Right now there is no documentation or mention of external libraries/API:s at all, neither in the website or in the toolbox help window inside the app. 
(I'm still very impressed with the app and the work you are doing, just saying.)

**Comment by DubbleClick** [comment]
> Ok, but could you please provide a link in your documentation that links to a place at gwca where people can read and/or upload this data?

There isn't one. If you compile a list, we'll be happy to add them in an enum to GWCA and reference that on the website. Keep in mind, that the documentation on the website is rather incomplete and outdated, though. Most features are seen in toolbox settings and in the release notes/history.

> Right now there is no documentation or mention of external libraries/API:s at all, neither in the website or in the toolbox help window inside the app.

It's mentioned in the readme & contributing files of this repository and very extensively in the code. It's not relevant to users what libraries are used and/or how they work.

**Comment by JohnForsgren** [comment]
Okay, I have compiled a list now; it is not by any means complete, but it gives a solid overview and includes most of the "important" features (i.e the coolest animation). Although it isn't complete, I think the users should have access to something like this, since it is not super useful to just have 2070 completely unknown animations with no explaination. 
https://wiki.guildwars.com/wiki/User:Gelbrekt/Animation_IDs
