### ISSUE TITLE
Bright Red Enemy Targets on Toolbox Minimap Turn Dark Red After Interaction

### ISSUE THREAD

**Issue by ComeAtMeSideways** [HasKha/GWToolboxpp#938]
I just started using the Toolbox minimap a few days ago and I'm noticing my enemy targets on said map are turning to dark red from bright red after I auto attack or use a skill on the target, or one of my teammates, spirits, minions, summons, or pets has attacked or used a skill on any target in the current group being attacked. My Guild Wars brain is hard wired to see "red until dead" and it's very confusing keeping track of what's dead and what's not.

Bug or feature or am I missing a setting somewhere I can toggle?

Thanks

**Comment by BearsMan** [comment]
![Screenshot 2023-09-09 160309](https://github.com/HasKha/GWToolboxpp/assets/34116754/6ca9529d-c277-4a8d-8865-e939b70f4fcc)
![Screenshot 2023-09-09 160324](https://github.com/HasKha/GWToolboxpp/assets/34116754/60198bdf-a934-4a9f-8423-b39b6f658cac)


Do you mean this or something different?

**Comment by ComeAtMeSideways** [comment]
No the targets are still hostile. I have bright red and dark red hostile targets on the Toolbox minimap. Makes for a very confusing engagement scenario with enemy groups.

Thanks

**Comment by 3vcloud** [comment]
Toolbox automatically reduces the colour by a factor when an enemy drops below 90%, and I’m not sure that there’s a way to change that atm

**Comment by ComeAtMeSideways** [comment]
OK thanks, that explains it. Appreciate your kindness and assistance..

Ryan

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by ComeAtMeSideways** [comment]
Hey thanks guys, this is awesome, really appreciate it!

Ryan

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by BearsMan** [comment]
> In the screenshot Bearsman posted earlier, the second to last "Agent Damaged modifier" causes this. Setting all values to zero of that custom color should remove it.

That is correct.
