### ISSUE TITLE
tb gone

### ISSUE THREAD

**Issue by chiroaki** [HasKha/GWToolboxpp#95]
i wanted to look around in the features of the toolbox, when i changed the font or the hud scale , i dont know exactly what happend but tb is running but i cant see it anymore 
is there anyway to reset it ?'

**Comment by HasKha** [comment]
You may have set the global scale or alpha really small. Find your settings folder (check here for info https://haskha.github.io/GWToolboxpp/settings#storage) and either manually edit the entries in `theme.ini` or completely delete `theme.ini` to reset it.

**Comment by chiroaki** [comment]
nope there is no theme.ini

**Comment by HasKha** [comment]
then try `/tb reset` and `/show settings`

**Comment by chiroaki** [comment]
well i guess its too small

**Comment by chiroaki** [comment]
i cant see it   when i make mistake like / show setting it says  GWToolbox++:Cannot find blablalbla

**Comment by chiroaki** [comment]
cant you send me the theme.ini?

**Comment by HasKha** [comment]
theme.ini is empty by default. 

make sure you're looking in the settings folder (the folder where `GWToolbox.dll` is in) and try deleting, in this order, `theme.ini`, `interface.ini`, and `GWToolbox.ini`. It will reset your toolbox, but should solve your issue.

**Comment by chiroaki** [comment]
Only folder i have for toolbox is:
GWToolbox
in there is the file GWToolbox.ini  and keys.ini  nothing else  deleting the folder doesnt solve the issue

**Comment by chiroaki** [comment]
great ty
