### ISSUE TITLE
Travel pane severely crippled by 6.11

### ISSUE THREAD

**Issue by Bu11etmagnet** [HasKha/GWToolboxpp#954]
* Favourites can't be used. The "Go" button was replaced with a "Select", which does nothing.
* "Travel to..." does not accept keys. Before 6.11, opening "Travel To..." and pressing R would jump to Raisu Palace (alphabetically the first outpost name beginning with R). Now, opening "Travel To..." and pressing R starts the character running. This means that the outpost list has to be scrolled manually.

**Comment by 3vcloud** [comment]
Ok, will remove travel window for next version to fix the issue, thanks

**Comment by BearsMan** [comment]
This should be closed, since it is fixed in the 6.12 release. https://github.com/HasKha/GWToolboxpp/releases/tag/6.12_Release
