### ISSUE TITLE
Add option to hide the new elite skills in the completion window

### ISSUE THREAD

**Issue by franneck94** [HasKha/GWToolboxpp#958]
Would be good if we would have a tickbox to hide these "newish" elite skills in the completion window since these are not required for the elite skill title.

**Comment by 3vcloud** [comment]
The completion window isnt for tracking title progress, it’s for tracking character progress. Despite that, don’t these skills count toward the title anyway?

**Comment by adituv** [comment]
They do count, but in excess of the title's requirements.  Capping the 10 of them lets you skip 10 other skills in each of Tyria, Cantha and Elona for the title.  I don't really see the point in hiding them.

**Comment by franneck94** [comment]
Ah okay I didn't know that they count in that case.
