### ISSUE TITLE
Auto Load Builds

### ISSUE THREAD

**Issue by ExcrementSniffer** [HasKha/GWToolboxpp#96]
Any chance on the Builds widget can add option to auto load a build tempplate of your choice when in xxxx town?
If there is any other dummies like me that forget to change builds when doing different dungeonsc's....
If its even worth doing ^^

**Comment by reduf** [comment]
It is definitly not worth doing and probably undesired.
The builds widget is meant to ping a teambuild, not to save your personnal build / load them.

**Comment by HasKha** [comment]
Agree with reduf. I can see why you want this, but my opinion is that it would also be confusing to configure, easy to have bugs and unwanted behavior, and appealing to a small minority of users. 

The build panel does the job of pinging teambuilds to chat, this would be something entirely different. 

We won't implement this, sorry.
